### PR TITLE
Fix: ledger no request keys context

### LINKED ISSUE #4682: Signing in with hardware wallet sometimes results in "No LedgerRequestKeysContext found" if bitcoin app is on instead of stacks
signing in at stacks.gamma.io while the ledger has the bitcoin app active will result in this error

image

Switching to the stacks app on the ledger device results in the expected behavior.

### LINKED ISSUE #4786: Ledger "unexpected application error!" after clicking the account to connect with "No LedgerRequestKeysContext found"
Reproduce with these steps 
1. Sign out wallet
2. Connect wallet to Stacks with Ledger, so account balance shows in the extension
3. Then disconnect the ledger device from computer
4. Sign in to a dapp for example lockstacks.com
5. Select account to connect with
6. See error:

image

To fix issue: connect Ledger Device to your computer again, start the Stacks app on the Ledger device then try again. 

I think instead of this error the wallet should show better guidance for the user.

### LINKED ISSUE #4863: Refactor repeating signing code into generic hook
Much code is duplicated between the transaction signing steps for both Bitcoin and Stacks.

This can be improved using a shared hook similar to RequestKeys flow

### PR DESCRIPTION
**Pull request by edgarkhanzadian**
> Try out this version of Leather — [Extension build](https://github.com/leather-wallet/extension/actions/runs/7797558088), [Test report](https://leather-wallet.github.io/playwright-reports/fix/ledger-no-request-keys-context)

- Fixes #4682 and #4786 by using location state for chain name in ledger connect error, as it sometimes doesn't have access to LedgerRequestKeysContext
- Fixes #4863, refactored a good chunk of code into useLedgerSignTx hook and TxSigningFlow provider.

Here's some testing of different scenarios:

https://github.com/leather-wallet/extension/assets/22010816/773cb55d-b17e-45b7-b981-5bb806917872

Note: will squash commits together after approval

### CODE REVIEW

**Comment by edgarkhanzadian** [comment]
@314159265359879 , please, let me know if there are any other scenarios worth testing on this branch.

File: src/app/features/ledger/generic-flows/tx-signing/use-ledger-sign-tx.ts [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+      onSuccess?.();
+    } catch (e) {
+      setAwaitingDeviceConnection(false);
+      if (e instanceof Error && checkLockedDeviceError(e)) {
+        setLatestDeviceResponse({ deviceLocked: true } as any);
+        return;
+      }
+
+      ledgerNavigate.toErrorStep(chain);
+      return app?.transport.close();
```
Comment (kyranjamie) [inline src/app/features/ledger/generic-flows/tx-signing/use-ledger-sign-tx.ts]: Don't we wanna do this in `finally`? Should run after success too, no?

File: src/app/features/ledger/generic-flows/tx-signing/use-ledger-sign-tx.ts [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+      if (isVersionOfLedgerStacksAppWithContractPrincipalBug(response)) {
+        navigate(RouteUrls.LedgerOutdatedAppWarning);
+        const response = await hasUserSkippedBuggyAppWarning.wait();
+
+        if (response === 'cancelled-operation') {
+          ledgerNavigate.cancelLedgerAction();
+          return;
+        }
+      }
+    }
```
Comment (kyranjamie) [inline src/app/features/ledger/generic-flows/tx-signing/use-ledger-sign-tx.ts]: How could we pass in this check from the Stacks-specific use of this hook, such that `useLedgerSignTx` knows less about any given chain? Could we pass in as a callback? An optional `afterConnect()` passed in?

**Review by kyranjamie — COMMENTED** [review]
Really nice refactor. Been wanting to get this done for ages!

File: src/app/features/ledger/generic-flows/tx-signing/use-ledger-sign-tx.ts (hunk 2 above)
Comment (edgarkhanzadian) [reply src/app/features/ledger/generic-flows/tx-signing/use-ledger-sign-tx.ts]: Done! Used an optional function `passesAdditionalVersionCheck` for that purpose

File: src/app/features/ledger/generic-flows/tx-signing/use-ledger-sign-tx.ts (hunk 1 above)
Comment (edgarkhanzadian) [reply src/app/features/ledger/generic-flows/tx-signing/use-ledger-sign-tx.ts]: Good point!

**Comment by 314159265359879** [comment]
> @314159265359879 , please, let me know if there are any other scenarios worth testing on this branch.

I believe you covered them, very nice!

**Review by kyranjamie — APPROVED** [review]
Great job @edgarkhanzadian 

Please rebase the merges before merging

**Review by fbwoolf — APPROVED** [review]
