### PR TITLE
fix: overlapping activity list text

### LINKED ISSUE #1756: Overlapping message in Activity tab
User is testing a PR build:v2.18.0.975

User notices upon testing the WW using the Stacks test app,there were a overlapping of activity details in the tab
Attaching the screenshot for perusal
overlapping activity details

### LINKED ISSUE #1789: fix misalignment on the activity feed's balance
The activity feed's balance number(?) are misaligned on the right

Screen Shot 2021-10-08 at 09 32 48

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/2308785093).

This PR fixes text on the activity list that is overlapping.

Screen Shot 2022-05-03 at 1 37 57 PM

cc/ @kyranjamie @fbwoolf @beguene @He1DAr

### CODE REVIEW

**Review by beguene — APPROVED** [review]

**Review by kyranjamie — APPROVED** [review]

File: src/app/components/tx-item.tsx [hunk 1]
```diff
@@ -288,9 +289,9 @@ export const TxItem = ({ transaction, ...rest }: TxItemProps) => {
       >
         <TxItemIcon transaction={transaction} />
         <SpaceBetween flexGrow={1}>
-          <Stack spacing="base-tight">
+          <Stack spacing="base-tight" whiteSpace="nowrap">
             <Title as="h3" fontWeight="normal">
-              {getTxTitle(transaction)}
+              {truncateText(getTxTitle(transaction), 20)}
```
Comment (landitus) [inline src/app/components/tx-item.tsx]: Wouldn't it be better if we truncate and show the ellipsis [purely with CSS](https://css-tricks.com/flexbox-truncated-text/)? I have reservations to remove characters as it makes the transaction less readable (by humans and screen readers). If we do it via CSS we truncate based on available white space: for ex. in the full tab view truncation will not be needed unless the screen width is reduced.

Additionally, I think we should add a tooltip on hover to the truncated elements only. The tooltip would display the full text so that it's readable on screen. 

See the example below
CleanShot 2022-05-05 at 18 56 26@2x

**Review by landitus — DISMISSED** [review]

File: src/app/components/tx-item.tsx (hunk 1 above)
Comment (fbwoolf) [reply src/app/components/tx-item.tsx]: Yep, I can change to using CSS and add a tooltip, np.

Comment (Eshwari007) [reply src/app/components/tx-item.tsx]: Will wait for the new changes as mentioned to be implemented prior to QA testing

> Yep, I can change to using CSS and add a tooltip, np.

Will wait for the new changes as mentioned to be implemented prior to QA testing

**Comment by fbwoolf** [comment]
@landitus I have changed this to just using CSS and added the tooltip (just when the ellipsis are added), when you get a sec pls review and approve if can. Thanks!

Screen Shot 2022-05-06 at 11 54 03 AM

**Comment by landitus** [comment]
@fbwoolf I've review this again and found:
- I see some letters being cut off, like when using the overflow-hidden property. 
- In the full tab since we are still truncating text that could easily fit the screen. I suspect it's because of the row elements' flexbox properties.

CleanShot 2022-05-06 at 19 51 55@2x

**Comment by fbwoolf** [comment]
> @fbwoolf I've review this again and found:
> 
I removed the `maxWidth` so the ellipsis aren't applied in full page view, ~~but I am not seeing the cut off text locally. I haven't changed anything here with height ...do you see that in prod? Trying to reproduce it.~~

The tooltip is not consistently showing on resizing the full page view so I will fix that (which seems like an edge case). Applying the tooltip is being done in a lifecycle hook that isn't updating on resizing the window. I'll fix it so it does.

EDIT: I see the cropped text now, nvm.

**Comment by landitus** [comment]
Thanks @fbwoolf. lmk when you want me review this again

**Comment by fbwoolf** [comment]
Diving into this a bit further, I've realized there are several components handling the transaction row in the activity list ...so, yet again, this has become a slightly larger refactor effort in order to address simple UI fixes appropriately. 😆  But, it will be in a much better place when done.

**Comment by fbwoolf** [comment]
@landitus @kyranjamie can you circle back and check this again when you are free. I did a lot of work to clean up these components. I prob didn't address everything, but at least the activity transaction row is in a better place. I restructured some things so that the `increase fee` button doesn't shift things around ...and I reused components in order to remove duplicated code. I could prob make another pass thru it all, but it was a mess! 😅  A lot of this is just pulling loads of components out of one file.

File: src/app/components/transaction/components/stacks-transaction-icon.tsx [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+import { Tx } from '@app/common/api/transactions';
+import { getTxSenderAddress } from '@app/store/accounts/account-activity.utils';
+
+import { TransactionTypeIcon } from './transaction-type-icon';
+import { TransactionIconWrapper } from './transaction-icon-wrapper';
+
+interface StacksTransactionIconProps {
+  transaction: StacksTransaction;
+}
+export function StacksTransactionIcon({ transaction, ...rest }: StacksTransactionIconProps) {
```
Comment (kyranjamie) [inline src/app/components/transaction/components/stacks-transaction-icon.tsx:14]: There are no other `...rest` props

File: src/app/components/transaction/components/transaction-icon.tsx [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+import { Tx } from '@app/common/api/transactions';
+import { StxIcon } from '@app/components/icons/stx-icon';
+
+import { TransactionTypeIcon } from './transaction-type-icon';
+import { TransactionIconWrapper } from './transaction-icon-wrapper';
+
+interface TransactionIconProps {
+  transaction: Tx;
+}
+export function TransactionIcon({ transaction, ...rest }: TransactionIconProps) {
```
Comment (kyranjamie) [inline src/app/components/transaction/components/transaction-icon.tsx:13]: Same here, there are no other typed other props

File: src/app/components/transaction/components/transaction-title.tsx [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+  const ref = useRef<HTMLDivElement | null>(null);
+  const [isEllipsisActive, setIsEllipsisActive] = useState(false);
+
+  useEffect(() => {
+    const element = ref.current!;
+    setIsEllipsisActive(element?.scrollWidth > element?.clientWidth);
+    const onResize = () => setIsEllipsisActive(element?.scrollWidth > element?.clientWidth);
+    window.addEventListener('resize', onResize);
+    return () => window.removeEventListener('resize', onResize);
+  }, []);
```
Comment (kyranjamie) [inline src/app/components/transaction/components/transaction-title.tsx]: This seems like something that should be turned into its own `useOnResizeListener` hook.

Also, are we _sure_ there's no way to do this without listening for resize events in js? There's no CSS-only solution? cc/ @andresgalante

Comment (fbwoolf) [reply src/app/components/transaction/components/transaction-title.tsx]: I did do quite a bit of searching around on this and followed suggestions, would be interested to know if there is another way?

File: src/app/components/transaction/components/stacks-transaction-icon.tsx (hunk 2 above)
Comment (fbwoolf) [reply src/app/components/transaction/components/stacks-transaction-icon.tsx:14]: Thanks, I'll look over all this again today too.

Comment (fbwoolf) [reply src/app/components/transaction/components/stacks-transaction-icon.tsx:14]: These did originally extend `BoxProps` so I'll add it back.

**Comment by timstackblock** [comment]
@fbwoolf all test are passing

**Comment by landitus** [comment]
@fbwoolf this is looking A-MAZING!! It's a huge improvement to how the line items are laid out.

I found 2 comments so far:
- We could add more margin (like 32px) to the minimum distance between elements
- In the Activity tab, the numbers are bolder than before.

CleanShot 2022-05-10 at 22 06 42@2x

**Comment by fbwoolf** [comment]
> @fbwoolf this is looking A-MAZING!! It's a huge improvement to how the line items are laid out.
> 
> I found 2 comments so far:
> 
> * We could add more margin (like 32px) to the minimum distance between elements
> * In the Activity tab, the numbers are bolder than before.
> 
Fantastic, thanks for the feedback! I'll fix. I noticed the font weight but don't remember changing anything on that so will look. It is using a `<Title />` component I think that defaults to a font weight of 500. I will fix!

**Comment by fbwoolf** [comment]
Ok, those 2 things should be fixed on the new build.

Note: I decided to use a media query to hide the increase fee button at 355px bc it starts to run into the status text. I'm not sure anyone will ever run into that, but let me know if that isn't what you want.

**Review by kyranjamie — APPROVED** [review]

**Comment by landitus** [comment]
> Note: I decided to use a media query to hide the increase fee button at 355px bc it starts to run into the status text. I'm not sure anyone will ever run into that, but let me know if that isn't what you want.

I will test that use case (I didn't before)

**Comment by fbwoolf** [comment]
@landitus any chance you are finished with design review on this one? I'd love to get it merged if possible. I moved quite a few files around so just want to get it merged asap.

**Comment by landitus** [comment]
Will review now

**Comment by landitus** [comment]
Thanks @fbwoolf.

Noticed 2 things:
- I haven't been able to see the tooltip consistently.
- The increase fees button lost a bit of styles which made it look a bit nicer and more polished, specially on hover. I believe the previous button is a tad taller, has a shadow and a hover style animating the shadow. This is not a big stopper for merging, but would be nice to capture those styles to re-apply them later as they were good to begin with.

CleanShot 2022-05-11 at 19 13 57@2x

**Comment by fbwoolf** [comment]
> * I haven't been able to see the tooltip consistently.
> * The increase fees button lost a bit of styles which made it look a bit nicer and more polished, specially on hover. I believe the previous button is a tad taller, has a shadow and a hover style animating the shadow. This is not a big stopper for merging, but would be nice to capture those styles to re-apply them later as they were good to begin with.
> 
- ~~The tooltip has been consistent for me, so not sure on that?~~
- I see what broke on this ...fixed now! Will let QA test it again on dev once merged.
- I changed the styling on purpose but can put back if want?

EDIT: DM'd w/ @landitus and will put the original styles back on the button!

**Review by landitus — APPROVED** [review]
This looks amazing @fbwoolf ! Tooltips work perfectly and the restored button styles look great. Thank you! 🙏
