### PR TITLE
fix: fix routing issues with send flow

### LINKED ISSUE #5145: Send STX form is crashing
When starting to work on [this](https://github.com/leather-wallet/extension/issues/5133), I realised that the send STX flow is crashing with:
```
Unexpected Application Error!
Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
    at formSip10TxSummary (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:186214:48)
    at formReviewTxSummary (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:186188:14)
    at StacksSendFormConfirmation (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:201968:7)
    at renderWithHooks (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:280887:18)
    at updateFunctionComponent (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:284165:20)
    at beginWork (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:286178:16)
    at beginWork$1 (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:292003:14)
    at performUnitOfWork (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:291134:12)
    at workLoopSync (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:291043:5)
    at renderRootSync (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:291011:7)
```

It also tries to move to the wrong route for `confirm` -> `/send/stx/confirm/confirm` 

I tested and it's not happening on `main` but it is on the `dev` branch

### PR DESCRIPTION
**Pull request by pete-watters**
> Try out Leather build cc1aa60 — [Extension build](https://github.com/leather-wallet/extension/actions/runs/8480946356), [Test report](https://leather-wallet.github.io/playwright-reports/fix/5145/send-stx-form), [Storybook](https://fix-5145-send-stx-form--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=fix/5145/send-stx-form)

This PR fixes issues with the `send` flow not moving past `Continue`. I guess these problems were introduced in the containers PR although I thought that area was well tested manually and covered by automated tests. 

I will investigate improving the tests but opening this PR right away as otherwise sending any tokens is not working.

### CODE REVIEW

File: src/app/pages/send/send-crypto-asset-form/hooks/use-send-form-navigate.ts [hunk 1]
```diff
@@ -82,8 +84,7 @@ export function useSendFormNavigate() {
         name,
         tx,
       }: ConfirmationRouteStacksSip10Args) {
-        return navigate('confirm', {
-          replace: true,
+        return navigate(`${location.pathname}/confirm`, {
```
Comment (pete-watters) [inline src/app/pages/send/send-crypto-asset-form/hooks/use-send-form-navigate.ts:87]: The previously working relative paths now fail so I am using the `location.pathname` to prepend this route. 

I think this may have stopped working as to move the `Continue` button to the footer, we had to change the form to use `props.handleSubmit()`

e.g. in `BtcSendForm`:

```
  return (
            <Form>
              <Card
                footer={
                  <Footer variant="card">
                    <Button
                      data-testid={SendCryptoAssetSelectors.PreviewSendTxBtn}
                      onClick={() => props.handleSubmit()}
                      type="submit"
                    >
                      Continue
                    </Button>
                    <AvailableBalance balance={formatMoney(btcBalance.balance)} />
                  </Footer>
                }
              >
                <CardContent dataTestId={SendCryptoAssetSelectors.SendForm}>
                  <AmountField
    
```

Before we had a lot of nested components doing this that drilled down a lot to a `preview-button` component

**Review by kyranjamie — APPROVED** [review]
