### PR TITLE
fix: backup old wallet salt key to gaia using background script

### LINKED ISSUE #2238: Periodic Incorrect appPrivateKey Derivation
## Expected behavior:

- The same wallet + app domain would always create the same app private key.

## Actual behavior:

- Sometimes the app private key changes unexplicably or is different across browsers. This is usually "fixed" if you uninstall Hiro and restore your wallet. But after normal browser usage over an unspecified period of time, the derived app private key can change. Very puzzling, and I have not been able to identify a pattern, other than that I have witnessed this behavior in Chrome and Brave (but not Firefox, at least not yet) on an Apple Mac Mini M1 machine.

### PR DESCRIPTION
**Pull request by beguene**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/1962887358).

This PR uses background script to handle the backup
closes #2238

Previous PR https://github.com/hirosystems/stacks-wallet-web/pull/2286

@fbwoolf I moved the logic to the background message handler
Since we only have the secret key, I recreated the wallet with the secret key instead of using the WalletState which is not accessible in the background.

### CODE REVIEW

File: src/background/background-backup-wallet-salt-handler.ts [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+    logger.error('Error: Received background script msg from ' + sender.url);
+    return;
+  }
+  logger.info(message);
+  switch (message.method) {
+    case InternalMethods.ShareInMemoryKeyToBackground: {
+      const { secretKey } = message.payload;
+      await backupWalletSaltForGaia(secretKey);
+      break;
+    }
```
Comment (kyranjamie) [inline src/background/background-backup-wallet-salt-handler.ts]: Is there any reason to do this in a separate message handler, rather than adding this to the handler in `backgroundBackupWalletSaltHandler`.

The gist of `backgroundMessageHandler` is that it's a catch all for background msgs (if we have hundreds of events, maybe we'll need to rethink that, though for this small change, I'd just amend the existing `ShareInMemoryKeyToBackground` action)

Comment (beguene) [reply src/background/background-backup-wallet-salt-handler.ts]: I thought it will be more decoupled this way. And then we will just remove this extra handler when we won't need it (in a couple of months) without touching the "ShareInMemory..." logic. Wdyt ?

Comment (kyranjamie) [reply src/background/background-backup-wallet-salt-handler.ts]: That makes sense, though now we have to duplicate the source validation.

Up to you.

Comment (beguene) [reply src/background/background-backup-wallet-salt-handler.ts]: I will change it

File: src/background/background-backup-wallet-salt-handler.ts [hunk 2]
```diff
@@ -0,0 +1,88 @@
+import { logger } from '@shared/logger';
+import { gaiaUrl } from '@shared/constants';
+import { createWalletGaiaConfig, generateWallet } from '@stacks/wallet-sdk';
+import { GaiaHubConfig, uploadToGaiaHub } from '@stacks/storage';
+import { decryptContent, encryptContent, getPublicKeyFromPrivate } from '@stacks/encryption';
+import { fetchPrivate } from '@stacks/common';
+
+interface WalletDataMigrationConfig {
+  version: string;
+  oldWalletSalt: string;
```
Comment (fbwoolf) [inline src/background/background-backup-wallet-salt-handler.ts]: Is there something more descriptive we can use here than `old`? I'm losing track of what all the salt versions are here.

File: src/background/background-backup-wallet-salt-handler.ts [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+const walletMigrationVersion = '1.0';
+
+async function storeToGaia(configPrivateKey: string, gaiaHubConfig: GaiaHubConfig, salt: string) {
+  const migrationData: WalletDataMigrationConfig = {
+    version: walletMigrationVersion,
+    oldWalletSalt: salt,
+  };
+  const publicKey = getPublicKeyFromPrivate(configPrivateKey);
+  const encrypted = await encryptContent(JSON.stringify(migrationData), { publicKey });
+  await uploadToGaiaHub(
```
Comment (He1DAr) [inline src/background/background-backup-wallet-salt-handler.ts]: should we handle upload failure?

File: src/background/background-backup-wallet-salt-handler.ts [hunk 4]
```diff
@@ -0,0 +1,88 @@
+import { logger } from '@shared/logger';
```
Comment (fbwoolf) [inline src/background/background-backup-wallet-salt-handler.ts]: Curious about this file now as separate from `backup-old-wallet-salt.ts`, do they need to be separate or named in a way that they can be one file? I def don't think `background` needs to be in the file name here?

File: src/background/background-backup-wallet-salt-handler.ts [hunk 5]
```diff
@@ -0,0 +1,88 @@
...
+  } catch (error) {
+    logger.error(error);
+    return null;
+  }
+}
+
+const walletMigrationFilename = 'wallet-migration-data.json';
+const walletMigrationVersion = '1.0';
+
+async function storeToGaia(configPrivateKey: string, gaiaHubConfig: GaiaHubConfig, salt: string) {
```
Comment (He1DAr) [inline src/background/background-backup-wallet-salt-handler.ts]: should we use different naming for the salt arg here?

File: src/background/background-backup-wallet-salt-handler.ts (hunk 2 above)
Comment (beguene) [reply src/background/background-backup-wallet-salt-handler.ts]: Basically this is not the current wallet salt (so can't use `salt`), and it might not always be the previous one (can't use `previousSalt`). I can't use a specific date since it depends on the day the user updates its wallet and we don't know in advance. I can use the current wallet version appended.
like `salt_v3.2.0` wdyt ?

File: src/background/background-backup-wallet-salt-handler.ts (hunk 3 above)
Comment (beguene) [reply src/background/background-backup-wallet-salt-handler.ts]: Yes indeed ! I will add something.

File: src/background/background-backup-wallet-salt-handler.ts (hunk 4 above)
Comment (beguene) [reply src/background/background-backup-wallet-salt-handler.ts]: Agree, I will club them together then and rename. Yes background should be removed.

File: src/background/background-backup-wallet-salt-handler.ts (hunk 5 above)
Comment (beguene) [reply src/background/background-backup-wallet-salt-handler.ts]: I think salt is fine here, this is what we want to store. I don't want to add the version also here in the name and neither use 'old'. If you have any suggestion let me know otherwise I will keep `salt`.

File: src/background/background-backup-wallet-salt-handler.ts (hunk 2 above)
Comment (fbwoolf) [reply src/background/background-backup-wallet-salt-handler.ts]: Thinking on this, would it be better to be more specific, like `walletSaltThatGeneratesIncorrectAppKey`?

**Comment by fbwoolf** [comment]
@aulneau @yknl for reference, this is the current PR open to review.

File: src/background/background-backup-wallet-salt-handler.ts (hunk 2 above)
Comment (beguene) [reply src/background/background-backup-wallet-salt-handler.ts]: Yes that works better ! I will use it thanks !

File: src/background/background-backup-wallet-salt-handler.ts (hunk 5 above)
Comment (fbwoolf) [reply src/background/background-backup-wallet-salt-handler.ts]: I posted my last comment in the wrong place, sorry, meant to do here ...Again, you could use this here `walletSaltThatGeneratesIncorrectAppKey`?

Comment (beguene) [reply src/background/background-backup-wallet-salt-handler.ts]: I will also use this `walletSaltThatGeneratesIncorrectAppKey` here then.

File: src/background/backup-old-wallet-salt.ts [hunk 6]
```diff
@@ -0,0 +1,108 @@
+const walletSaltBackup = 'wallet-salt-backup';
+
+export function backupOldWalletSalt() {
```
Comment (fbwoolf) [inline src/background/backup-old-wallet-salt.ts:10]: Sorry to nit naming, but I feel like using `Incorrect` rather than `Old` here and in the file name would make more sense?

**Review by fbwoolf — APPROVED** [review]
Going to approve this with one last comment. I also feel like we need at least one more approval before we merge/release it.

File: src/background/backup-old-wallet-salt.ts (hunk 6 above)
Comment (beguene) [reply src/background/backup-old-wallet-salt.ts:10]: `backupIncorrectWalletSalt` is actually incorrect. It's the appPrivateKey derived from it that is incorrect, not the salt.
Note that this code is ephemeral, so it will be removed in maybe 1 month.

Comment (fbwoolf) [reply src/background/backup-old-wallet-salt.ts:10]: O right, confused for a sec ...haha. 👍

**Review by He1DAr — APPROVED** [review]
