### PR TITLE
fix: display of JSON mime type inscriptions

### LINKED ISSUE #3533: Ensure inscriptions of mimetype JSON have line breaks
image

Is this because there are no spaces in the json?

### PR DESCRIPTION
**Pull request by alter-eggo**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/wallet/actions/runs/4994561822).

Closes #3533

### CODE REVIEW

**Comment by alter-eggo** [comment]
Screenshot 2023-05-16 at 20 27 16

File: src/app/features/collectibles/components/bitcoin/inscription-text.tsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ export function InscriptionText({
       key={inscriptionNumber}
       onClickCallToAction={onClickCallToAction}
       onClickSend={onClickSend}
-      content={query.data}
+      content={JSON.stringify(JSON.parse(query.data), null, 2)}
```
Comment (kyranjamie) [inline src/app/features/collectibles/components/bitcoin/inscription-text.tsx]: This will throw an error if it isn't legit JSON, so we first need a safety check with try catch

Comment (alter-eggo) [reply src/app/features/collectibles/components/bitcoin/inscription-text.tsx]: fixed

**Review by kyranjamie — APPROVED** [review]
Good improvement 👍🏼
