### PR TITLE
fix: show stx transfers from contract call

### LINKED ISSUE #1432: All token (send and receive) values should be viewable on Activity Tab
Screen Shot 2021-07-13 at 12 33 14 PM
Screen Shot 2021-07-13 at 12 33 20 PM
Environment:Testnet

Actual scenario:
User is only able to view -numeric values of Stacks token when it was send,however user is not able to view the - numeric values of other tokens when its send via the Activity tab
User is not able to view the receive activity for other tokens as well

Expected results:
User is supposedly to view all numeric values of send and receive of all the tokens(not just Stacks)

Attached the screenshot of the issue
Screen Shot 2021-07-13 at 12 26 16 PM

### LINKED ISSUE #1460: Show activity for tokens transferred via contracts
User tried to send Stella token and Rocket token between two accounts
User also send STX token between another two accounts

All of the transfers were super fast and it was successful
However,user notices in the accounts where Stella and Rocket tokens were send and received,the activity tab is empty

Attaching the screenshot for perusal
cc @aulneau @beguene @timstackblock 
Screen Shot 2021-07-20 at 12 17 44 PM
Screen Shot 2021-07-20 at 12 17 57 PM
Screen Shot 2021-07-20 at 12 18 12 PM
Screen Shot 2021-07-20 at 12 18 19 PM

### LINKED ISSUE #1713: STX Transfer from contract not showing or showing incorrectly in wallet
stx transfers, triggered within contract, don't show in web wallet activity stream and show with incorrect amount in desktop wallet.  

See 0x3a71f352639625737fa9377e1e0c5c8c65afc98772130fc1f0c1ee447734a6a1 for example the stx transfer from 
STX transfer of 0.3 STX from SP4DYYK99BZS7S95KYYEJAJE5VJ21F57M4NS0Q5F to SP4DYYK99BZS7S95KYYEJAJE5VJ21F57M4NS0Q5F
shows in desktop wallet as 0.1369 STX - the same amount as the gas fee charged to the buyer?

and this tx: 0x3b378fa6c80e471045cbee17ee33c3c3c5589904f0da0a35a3715036900fef7d
the 0.25 to SP162D87CY84QVVCMJKNKGHC7GGXFGA0TAR9D0XJW
(event 0) is not showing in the activity tab of web wallet of this address.

## Details

Network: mainnet
Contract: SP3QSAJQ4EA8WXEDSRRKMZZ29NH91VZ6C5X88FGZQ.thisisnumberone-v2
Client libs: 
    "@stacks/connect": "^6.2.0",
    "@stacks/network": "^2.0.1",
    "@stacks/storage": "^2.0.1",
    "@stacks/transactions": "^2.0.1",

## Screenshots

Screenshot 2021-09-16 at 08 40 43

Screenshot 2021-09-16 at 08 42 55

Desktop wallet receives the gas fee amount (should receive 0.25 stx)?
Screenshot 2021-09-16 at 08 21 42

### PR DESCRIPTION
**Pull request by beguene**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/ux/actions/runs/1398656887).

Fixes #1713. 
Shows all internal STX transfers triggered within contracts.
Those transfers txs are reconstructed from the contract events info and fetched from the api endpoint /transactions_with_transfers
and then merged with existing confirmed transactions. Those STX transfers are sorted to appear after the contract call (above the contract call row in the activity list)

stx-transfer-2

cc/ @aulneau @kyranjamie @fbwoolf

### CODE REVIEW

File: src/store/accounts/api.ts [hunk 1]
```diff
@@ -171,6 +175,30 @@ export const accountTransactionsUnanchoredClient = atomFamilyWithInfiniteQuery<
...
+    });
+    return result as PaginatedResults<AddressTransactionWithTransfers>;
+  },
+  {
+    refetchInterval: QueryRefreshRates.MEDIUM,
+    refetchOnMount: 'always',
+    refetchOnReconnect: 'always',
+    refetchOnWindowFocus: 'always',
+  }
+);
```
Comment (kyranjamie) [inline src/store/accounts/api.ts]: Could we just use react query directly, rather than getting deeper involved in the wrapper library?

File: src/store/accounts/account.hooks.ts [hunk 2]
```diff
@@ -30,6 +36,25 @@ export function useCurrentAccountAvailableStxBalance() {
...
+  return contractCallTxs
+    .map(tx =>
+      tx.stx_transfers.map(transfer => ({
+        ...tx.tx,
+        tx_id: tx.tx.tx_id,
+        sender_address: transfer.sender,
+        token_transfer: { amount: transfer.amount },
+        tx_type: 'token_transfer',
+      }))
+    )
```
Comment (kyranjamie) [inline src/store/accounts/account.hooks.ts]: I'd strongly advise against this. This breaks the type system as many of the other properties of `MempoolTransaction | Transaction` aren't actually there. This is effectively tricking the type system, which will be really confusing to any developer who has to touch this later (and could well result in runtime errors not caught at compile time).

We should think of another way to format the list of txs that doesn't involve creating a "matching" type

**Review by kyranjamie — CHANGES_REQUESTED** [review]
image

Dates are now sorted backwards, too.

**Comment by kyranjamie** [comment]
Perhaps we can replace use of the `/transaction` endpoint altogether, as all the information we need is in the `transaction_with_transfers` one anyway.

This way, we could avoid adding a new query, and any logic to try and merge transactions together. Instead updating the store to save the different response type (which includes the whole tx in addition to the transfers).

File: src/store/accounts/api.ts (hunk 1 above)
Comment (beguene) [reply src/store/accounts/api.ts]: Sure I will refactor and use react-query.

File: src/common/date-utils.ts [hunk 3]
```diff
@@ -30,3 +30,14 @@ export function displayDate(txDate: string): string {
...
+export function isoDateToLocalDateSafe(isoDate: string) {
+  let result;
+  try {
+    result = isoDateToLocalDate(isoDate);
+  } catch (e) {
+    console.log(isoDate);
+    console.log(e);
+  }
+  return result;
+}
```
Comment (kyranjamie) [inline src/common/date-utils.ts]:
```suggestion
export function isoDateToLocalDateSafe(isoDate: string) {
  try {
    return isoDateToLocalDate(isoDate);
  } catch (e) {
    console.log(isoDate);
    console.log(e);
  }
}
```

no need to redeclare right?

File: src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+const QUERY_OPTIONS = {
+  refetchInterval: QueryRefreshRates.MEDIUM,
+  refetchOnMount: 'always',
+  refetchOnReconnect: 'always',
+  refetchOnWindowFocus: 'always',
+};
+
+export function useGetAccountTransactionsWithTransfer(reactQueryOptions: UseQueryOptions = {}) {
+  const principal = useCurrentAccountStxAddressState();
+  const networkUrl = useCurrentNetworkState().url;
```
Comment (kyranjamie) [inline src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts]:
```suggestion
  const { url } = useCurrentNetworkState();
```

File: src/common/transactions/transaction-utils.ts [hunk 5]
```diff
@@ -15,6 +15,25 @@ import {
...
+import { stacksValue } from '@common/stacks-utils';
+import { BigNumber } from 'bignumber.js';
+
+type Tx = MempoolTransaction | Transaction;
+
+export type StxTransfer = {
+  amount: string;
+  sender?: string;
+  recipient?: string;
+};
```
Comment (kyranjamie) [inline src/common/transactions/transaction-utils.ts]:
```suggestion
export interface StxTransfer {
  amount: string;
  sender?: string;
  recipient?: string;
};
```

Generally we stick to `interface` unless we're composing higher level types

File: src/components/popup/transaction-list.tsx [hunk 6]
```diff
@@ -1,22 +1,26 @@
...
-interface TransactionListProps {
-  txsByDate: ReturnType<typeof createTxDateFormatList>;
+interface TransactionWithTransferListProps {
+  txs: AddressTransactionWithTransfers[];
 }
-export function TransactionList({ txsByDate }: TransactionListProps) {
+
+export function TransactionWithTransferList({ txs }: TransactionWithTransferListProps) {
+  // Group txs by date
+  const txsByDate = useMemo(() => (txs ? createTxDateFormatList(txs) : []), [txs]);
```
Comment (kyranjamie) [inline src/components/popup/transaction-list.tsx]:
```suggestion
  const txsGroupedByDate = useMemo(() => (txs ? createTxDateFormatList(txs) : []), [txs]);
```

If `txsByDate` isn't clear enough, let's just rename the variable, rather than adding a comment.

File: src/components/popup/transaction-list.tsx [hunk 7]
```diff
@@ -1,22 +1,26 @@
...
+      {txsByDate.map(({ date, displayDate, txs }, index) => (
         <Box key={date}>
           <Text textStyle="body.small" color={color('text-caption')}>
             {displayDate}
           </Text>
           <Stack mt="base-loose" spacing="loose">
-            {txs.map(tx => (
-              <TxItem transaction={tx} key={tx.tx_id} />
+            {txs.map(atx => (
+              <TxWithTransferItem transaction={atx} key={atx.tx.tx_id + index} />
```
Comment (kyranjamie) [inline src/components/popup/transaction-list.tsx]: Why do we need to add the index here?

File: src/components/popup/tx-item.tsx [hunk 8]
```diff
@@ -126,6 +101,120 @@ const SpeedUpButton = ({
...
+      title={title}
+      caption={caption}
+      value={value}
+      onClick={() => handleOpenTxLink(parentTx.tx.tx_id)}
+      icon={iconWrapper}
+    />
+  );
+};
+
+export const TxWithTransferItem: React.FC<TxWithTransferItemProps & BoxProps> = ({
```
Comment (kyranjamie) [inline src/components/popup/tx-item.tsx]: This component, and its corresponding interface, has confusing names.

It isn't necessarily a TxWithTransferItem, it may well be a regular transaction. If we're building a component that supports both, I would omit this information altogether. This is just the component that displays a transaction.

File: src/components/popup/tx-item.tsx [hunk 9]
```diff
@@ -126,6 +101,120 @@ const SpeedUpButton = ({
...
+  transaction,
+  ...rest
+}) => {
+  if (!transaction) return null;
```
Comment (kyranjamie) [inline src/components/popup/tx-item.tsx]: When will it ever be null? Passing a possibly null transaction prop should be a type error. It's the parent component's job to make sure that it isn't null.

File: src/components/popup/tx-item.tsx [hunk 10]
```diff
@@ -126,6 +101,120 @@ const SpeedUpButton = ({
...
+
+  if (!isAddressTransactionWithTransfer(transaction))
+    return <TxItem transaction={transaction as Tx} {...rest} />; // This is a normal Transaction or MempoolTransaction
+
+  const transact = transaction as AddressTransactionWithTransfers;
```
Comment (kyranjamie) [inline src/components/popup/tx-item.tsx]: typo?

File: src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts [hunk 11]
```diff
@@ -0,0 +1,43 @@
...
+  const { accountsApi } = useAccountsApi();
+  const fetch = () => {
+    if (!principal) return;
+    return accountsApi.getAccountTransactionsWithTransfers({
+      principal,
+      limit: DEFAULT_LIST_LIMIT,
+    });
+  };
+
+  return useQuery(['accountNonce', principal, networkUrl], fetch, {
```
Comment (kyranjamie) [inline src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts]: copy/paste

File: src/components/popup/transaction-list.tsx [hunk 12]
```diff
@@ -1,22 +1,26 @@
...
+import { TxWithTransferItem } from './tx-item';
 
-interface TransactionListProps {
-  txsByDate: ReturnType<typeof createTxDateFormatList>;
+interface TransactionWithTransferListProps {
+  txs: AddressTransactionWithTransfers[];
 }
-export function TransactionList({ txsByDate }: TransactionListProps) {
+
+export function TransactionWithTransferList({ txs }: TransactionWithTransferListProps) {
```
Comment (kyranjamie) [inline src/components/popup/transaction-list.tsx]: RE naming here, the notion of "transactions with transfer" is really an API implementation detail the the wallet's presentation of a tx list doesn't need to be concerned with. Let's keep the name as it was?

File: src/common/transactions/transaction-utils.ts [hunk 13]
```diff
@@ -119,3 +138,107 @@ export const generateSTXTransferTx = ({
...
+export function txHasTime(tx: Tx) {
+  return !!(
+    ('burn_block_time_iso' in tx && tx.burn_block_time_iso) ||
+    ('parent_burn_block_time_iso' in tx && tx.parent_burn_block_time_iso)
+  );
+}
+
+export const isAddressTransactionWithTransfer = (
+  transaction: AddressTransactionWithTransfers | Tx
+) => 'tx' in transaction;
```
Comment (kyranjamie) [inline src/common/transactions/transaction-utils.ts]:
```suggestion
export function isAddressTransactionWithTransfer (
  transaction: AddressTransactionWithTransfers | Tx
): transaction is AddressTransactionWithTransfers {
  return 'tx' in transaction;
}
```

We can give the type system more information here, which I think means we can avoid the type casting in the component. Also formatted as function declaration in line with rest of file.

**Review by kyranjamie — COMMENTED** [review]
This is a much better approach, thanks @beguene—

I have many comments, but these are mostly around naming

File: src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts [hunk 14]
```diff
@@ -0,0 +1,43 @@
...
+    enabled: !!principal || !!networkUrl,
+    ...reactQueryOptions,
+  });
+}
+
+export function useAccountTransactionsWithTransfer() {
```
Comment (fbwoolf) [inline src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts]: Should this always be plural throughout? `useAccountTransactionsWithTransfers`

Comment (fbwoolf) [reply src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts]: This is plural, so makes sense to me to keep it plural `accountsApi.getAccountTransactionsWithTransfers`?

File: src/components/popup/tx-item.tsx [hunk 15]
```diff
@@ -126,6 +101,120 @@ const SpeedUpButton = ({
...
+
+  // Show transfer only for contract calls
+  if (transact.tx.tx_type !== 'contract_call')
+    return <TxItem transaction={transact.tx} {...rest} />;
+
+  return (
+    <>
+      <TxTransfers transaction={transact} />{' '}
+      {/* Show all the other transfers (made with a contract_call) */}
+      <TxItem transaction={transact.tx} {...rest} />
```
Comment (fbwoolf) [inline src/components/popup/tx-item.tsx]: These returns are all a bit confusing and the code comments aren't helping me understand what is happening, can you clarify? It seems to be returning the same `<TxItem />`?

Comment (beguene) [reply src/components/popup/tx-item.tsx]: I moved the comment above.
TxTransfers are just the internal stx transfers displayed above the 'real' transaction. TxTransfers does not return TxItem  but a new kind of activity  ```<StxTransferItem/>```

File: src/components/popup/transaction-list.tsx (hunk 7 above)
Comment (beguene) [reply src/components/popup/transaction-list.tsx]: Indeed this is not needed anymore.

File: src/components/popup/tx-item.tsx (hunk 8 above)
Comment (beguene) [reply src/components/popup/tx-item.tsx]: Changed to TxView (TxItem is still used elsewhere)

File: src/components/popup/tx-item.tsx (hunk 9 above)
Comment (beguene) [reply src/components/popup/tx-item.tsx]: removed

File: src/components/popup/tx-item.tsx (hunk 15 above)
Comment (beguene) [reply src/components/popup/tx-item.tsx]: Actually the prettier moved the position of my comments 😞

File: src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts [hunk 16]
```diff
@@ -0,0 +1,43 @@
...
+  const principal = useCurrentAccountStxAddressState();
+  const { url: networkUrl } = useCurrentNetworkState();
+  const { accountsApi } = useAccountsApi();
+  const fetch = () => {
+    if (!principal) return;
+    return accountsApi.getAccountTransactionsWithTransfers({
+      principal,
+      limit: DEFAULT_LIST_LIMIT,
+    });
+  };
```
Comment (kyranjamie) [inline src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts]: With react query, don't you need to pull in the values from the fetcher from the `queryKey` of the fetcher?

File: src/components/popup/tx-item.tsx [hunk 17]
```diff
@@ -126,6 +101,112 @@ const SpeedUpButton = ({
...
+  );
+};
+
+const TxItemRow: React.FC<{
+  title: string;
+  value: number | string | null;
+  caption?: string;
+  icon: JSX.Element;
+  onClick?: () => Window | null;
+}> = ({ title, caption, value, icon, onClick, ...rest }) => {
```
Comment (kyranjamie) [inline src/components/popup/tx-item.tsx]: This is really just a preference for readability, but in most places we extract the type to `<nameOfComponet>Props`. I think it'd be helpful to keep to this pattern. What do you think?

```suggestion
interface TxItemRowProps {
  title: string;
  value: number | string | null;
  caption?: string;
  icon: JSX.Element;
  onClick?: () => Window | null; // also what's this type? It doesn't return window or null? Should probs be `void`
}
const TxItemRow: React.FC<TxItemRowProps> = ({ title, caption, value, icon, onClick, ...rest }) => {
```

File: src/components/popup/tx-item.tsx [hunk 18]
```diff
@@ -126,6 +101,112 @@ const SpeedUpButton = ({
...
+      value={value}
+      onClick={() => handleOpenTxLink(parentTx.tx.tx_id)}
+      icon={iconWrapper}
+    />
+  );
+};
+
+export const TxView: React.FC<TxViewProps & BoxProps> = ({ transaction, ...rest }) => {
+  if (!isAddressTransactionWithTransfer(transaction))
+    return <TxItem transaction={transaction as Tx} {...rest} />; // This is a normal Transaction or MempoolTransaction
```
Comment (kyranjamie) [inline src/components/popup/tx-item.tsx]: is the `as Tx` needed here, with the addition of the `transaction is` in `isAddressTransactionWithTransfer`?

**Review by kyranjamie — APPROVED** [review]
LGTM @beguene. Good work.

Please investigate the react query comment. Other comments relate to consistency.

Interested to get your and @fbwoolf's input on how we can keep component definitions consistent. I'd promote that we follow the rule where components are _always_ defined in this format, rather than mixing different styles.

```tsx
interface ComponentNameProps extends BoxProps {
  prop: string;
}
export const ComponentName: FC<ComponentNameProps> = () => {};
export const ComponentName = (props: ComponentNameProps) => {};
```

The second variant might be better as using `FC` assumes there will be children, when there might not be.

File: src/components/popup/tx-item.tsx (hunk 18 above)
Comment (beguene) [reply src/components/popup/tx-item.tsx]: Indeed this is not needed !

File: src/components/popup/tx-item.tsx (hunk 17 above)
Comment (beguene) [reply src/components/popup/tx-item.tsx]: Yes this is better

File: src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts (hunk 16 above)
Comment (beguene) [reply src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts]: In my case there is no need,  I use onSuccess which passes the data directly
https://github.com/blockstack/stacks-wallet-web/blob/feat/show-stx-transfer-amount-from-contract/I1713/src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts#L38
We could do it differently though.

**Comment by beguene** [comment]
> LGTM @beguene. Good work.
> 
> Please investigate the react query comment. Other comments relate to consistency.
> 
> Interested to get your and @fbwoolf's input on how we can keep component definitions consistent. I'd promote that we follow the rule where components are _always_ defined in this format, rather than mixing different styles.
> 
> ```tsx
> interface ComponentNameProps extends BoxProps {
>   prop: string;
> }
> export const ComponentName: FC<ComponentNameProps> = () => {};
> export const ComponentName = (props: ComponentNameProps) => {};
> ```
> 
> The second variant might be better as using `FC` assumes there will be children, when there might not be.

Yes this makes sense, let's try keeping this naming convention. I agree let's keep it simple, without the FC.

File: src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts (hunk 16 above)
Comment (kyranjamie) [reply src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts]: No it's okay:

```
 useQuery(['todos'], fetchAllTodos)
 useQuery(['todos', todoId], () => fetchTodoById(todoId))
 useQuery(['todos', todoId], async () => {
   const data = await fetchTodoById(todoId)
   return data
 })
 useQuery(['todos', todoId], ({ queryKey }) => fetchTodoById(queryKey[1]))
```

I was thinking we need to do the last way, but as long as `principal` is in the config it's okay

File: src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts [hunk 19]
```diff
@@ -0,0 +1,43 @@
...
+import { PaginatedResults } from '@common/types';
+
+const QUERY_OPTIONS = {
+  refetchInterval: QueryRefreshRates.MEDIUM,
+  refetchOnMount: 'always',
+  refetchOnReconnect: 'always',
+  refetchOnWindowFocus: 'always',
+};
+
+export function useGetAccountTransactionsWithTransfer(reactQueryOptions: UseQueryOptions = {}) {
```
Comment (fbwoolf) [inline src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts]: Can you coordinate the pluralization throughout your code overall so I know if this is 1 transfer or many? I still am unsure? I see it in different places used as singular and in other places as plural.

File: src/components/popup/tx-item.tsx [hunk 20]
```diff
@@ -126,7 +93,125 @@ const SpeedUpButton = ({
   );
 };
 
-export const TxItem: React.FC<TxItemProps & BoxProps> = ({ transaction, ...rest }) => {
+interface TxTransfersProps {
+  transaction: AddressTransactionWithTransfers & BoxProps;
+}
```
Comment (kyranjamie) [inline src/components/popup/tx-item.tsx]:
```suggestion
interface TxTransfersProps extends BoxProps {
  transaction: AddressTransactionWithTransfers;
}
```

File: src/components/popup/tx-item.tsx [hunk 21]
```diff
@@ -126,7 +93,125 @@ const SpeedUpButton = ({
...
+      icon={iconWrapper}
+    />
+  );
+};
+
+interface TxViewProps {
+  transaction: AddressTransactionWithTransfers | Tx;
+}
+
+export const TxView = ({ transaction, ...rest }: TxViewProps & BoxProps) => {
```
Comment (kyranjamie) [inline src/components/popup/tx-item.tsx]:
```suggestion
interface TxViewProps extends BoxProps {
  transaction: AddressTransactionWithTransfers | Tx;
}
export const TxView = ({ transaction, ...rest }: TxViewProps) => {
```

File: src/components/popup/tx-item.tsx [hunk 22]
```diff
@@ -126,7 +93,125 @@ const SpeedUpButton = ({
...
+      <TxItem transaction={transaction.tx} {...rest} />
+    </>
+  );
+};
+
+interface TxItemProps {
+  transaction: Tx;
+}
+
+export const TxItem = ({ transaction, ...rest }: TxItemProps & BoxProps) => {
```
Comment (kyranjamie) [inline src/components/popup/tx-item.tsx]:
```suggestion
interface TxItemProps extends BoxProps {
  transaction: Tx;
}
export const TxItem = ({ transaction, ...rest }: TxItemProps) => {
```

File: src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts [hunk 23]
```diff
@@ -0,0 +1,43 @@
...
+  const { accountsApi } = useAccountsApi();
+  const fetch = () => {
+    if (!principal) return;
+    return accountsApi.getAccountTransactionsWithTransfers({
+      principal,
+      limit: DEFAULT_LIST_LIMIT,
+    });
+  };
+
+  return useQuery(['account/transactionsWithTransfers', principal, networkUrl], fetch, {
```
Comment (kyranjamie) [inline src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts]: You can pull this in from the enum right?

File: src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts [hunk 24]
```diff
@@ -0,0 +1,43 @@
...
+import { PaginatedResults } from '@common/types';
+
+const QUERY_OPTIONS = {
+  refetchInterval: QueryRefreshRates.MEDIUM,
+  refetchOnMount: 'always',
+  refetchOnReconnect: 'always',
+  refetchOnWindowFocus: 'always',
+};
+
+export function useGetAccountTransactionsWithTransfers(reactQueryOptions: UseQueryOptions = {}) {
```
Comment (kyranjamie) [inline src/common/hooks/account/use-account-transactions-with-transfers.hooks.ts]: We only use this below, so we shouldn't export this fn (yet) right?

File: src/common/stacks-utils.ts [hunk 25]
```diff
@@ -75,3 +75,8 @@ export function validateAddressChain(address: string, currentNetwork: Network) {
 }
 
 export const getTicker = (assetName: string) => assetName.slice(0, 3).toUpperCase();
+
+export const amountToDecimals = (value: number | string | BigNumber, decimals: number = 2) => {
```
Comment (kyranjamie) [inline src/common/stacks-utils.ts]: What's the relevance of 2 decimals, and why do we want this as a default vs being explicit every time?

File: src/common/transactions/transaction-utils.ts [hunk 26]
```diff
@@ -119,3 +146,119 @@ export const generateSTXTransferTx = ({
...
+    return atx.tx.tx_status === 'success' || atx.tx.tx_status.includes('abort');
+  });
+}
+
+export function createTxDateFormatList(txs: AddressTransactionWithTransfers[]) {
+  return formatTxDateMapAsList(groupTxsByDateMap(filterDuplicateTx(txs)));
+}
+
+export const getTxCaption = (transaction: Tx) => {
+  if (!transaction) return null;
```
Comment (kyranjamie) [inline src/common/transactions/transaction-utils.ts]:
```suggestion
```

This function should not need to check for null. The compiler will tell us.

File: src/common/transactions/transaction-utils.ts [hunk 27]
```diff
@@ -119,3 +146,119 @@ export const generateSTXTransferTx = ({
...
+export const getTxTitle = (tx: Tx) => {
+  switch (tx.tx_type) {
+    case 'token_transfer':
+      return 'Stacks Token';
+    case 'contract_call':
+      return tx.contract_call.function_name;
+    case 'smart_contract':
+      return getContractName(tx.smart_contract.contract_id);
+    case 'coinbase':
+      return `Coinbase ${(tx as CoinbaseTransaction).block_height}`;
```
Comment (kyranjamie) [inline src/common/transactions/transaction-utils.ts:262]: Is this type cast necessary? The types use discriminating unions, so here it should know it's a coinbase tx type. If not there is something wrong.

Comment (beguene) [reply src/common/transactions/transaction-utils.ts:262]: I just moved this function in this file, not sure why that why there. But if I remove it does not type.

**Comment by beguene** [comment]
@Eshwari007 @timstackblock This is ready for QA. It fixes issue #1432 and #1460 (for stx transfers) and #1713 for token transfers. A lot has changed in the activity list, so you can focus your test around that area.

**Comment by Eshwari007** [comment]
@beguene Will test and keep you posted on my findings.
