### PR TITLE
fix: refactor primary chain

### LINKED ISSUE #4016: Add validation of subnet IDs

### PR DESCRIPTION
**Pull request by janniks**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/wallet/actions/runs/5610259162).

- refactors for validating subnet and working with the correct chain id in different code paths

### Explanation
I added a "primary" chain id (which is the parent network, if one is available).
The primary chainId/network is the one used for address detection, transaction version etc. (mainly the checks for mainnet/testnet).
The actual chainId is used mainly for signing (and thus is on the network object constructed from the user-provided url.

I hope this makes sense. It will likely not hold up once nested subnets emerge (which isn't too soon I hope)

### CODE REVIEW

**Comment by fbwoolf** [comment]
Thanks @janniks!

**Comment by fbwoolf** [comment]
Curious here, why use `primary` and `parent` interchangeably, rather than introducing `subnet` to distinguish the new sub networks? Trying to do CR and understand the changes.

**Comment by janniks** [comment]
That sounds better 😅 Not sure how I landed on this. I can rename chainId to subnetChainId and parentChainId back to the original chainId

**Review by kyranjamie — COMMENTED** [review]
Agree with Fara on primary/parent naming mismatch, otherwise this works. Are other changes needed?

**Comment by janniks** [comment]
Yep, great point. This evolved with my understanding of the different IDs.

Rewrote to use subnetChainId -- works a lot cleaner. I had an additional incorrect assumption, so a bunch of other stuff changed. Added comments to explain.

lmk if the add-network function is getting too big and you want more thoughtful refactors.
lmk if I should rebase to a readable history, or if you'll merge/squash anyway.

**Review by fbwoolf — APPROVED** [review]
Thanks for making the changes @janniks, this makes sense to me now. 👍 Looks good.

File: src/app/features/message-signer/add-network/add-network.tsx [hunk 1]
```diff
@@ -23,18 +23,22 @@ import {
   useNetworksActions,
 } from '@app/store/networks/networks.hooks';
 
+/**
+ * The **peer** network ID.
+ * Not used in signing, but needed to determine the parent of a subnet.
+ */
+enum NetworkID {
```
Comment (kyranjamie) [inline src/app/features/message-signer/add-network/add-network.tsx]: Can this name reflect that it's a `PeerNetworkId`?

**Review by hugoclrd — APPROVED** [review]
Tested with https://api.subnets.testnet.hiro.so. I was able to successfully broadcast transaction 🙌 
Thanks

**Review by kyranjamie — APPROVED** [review]
Outstanding rename comment, but approach LGTM

**Comment by markmhendrickson** [comment]
@janniks Do you want to make more changes here before merging or is this ready to release?

**Comment by janniks** [comment]
I think we're good to go on this one. Can be merged ✌🏻
