### PR TITLE
fix: only show errors when field not in focus, closes #3766

### LINKED ISSUE #3766: Prevent inadvertent display of send form validation errors
It seems that if the user focuses then blurs the amount or recipient fields in the BTC send form, their validation errors appear instantly even without having entered a value.

We shouldn't show these errors unless the user blurs with a non-empty value that's invalid.

Notice how it affects selecting one's own account for recipient having already focused the field.

https://github.com/hirosystems/wallet/assets/28991/d4b0e093-2edc-4c6e-a128-8f479ab4dd8e

https://github.com/hirosystems/wallet/assets/28991/72b6e283-93e3-49f8-8d48-0cbe8d6b8861

### PR DESCRIPTION
**Pull request by pete-watters**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/wallet/actions/runs/5600673862).

This PR fixes issue https://github.com/hirosystems/wallet/issues/3766

I tried a few solutions in this PR but this is the cleanest I found.

https://github.com/hirosystems/wallet/pull/4021

The fix makes sure we only show validation errors if a field is invalid and not in focus. 

Otherwise, if a user focuses then unfocuses on a field(`touches` the field) , when they next return an error shows until they un focus and the validation can re-run and clear the error

### CODE REVIEW

**Review by kyranjamie — APPROVED** [review]
Nice one Pete. Let's try it. 

I reckon there might be some cases where this isn't the behaviour we want, but probably works fine for our form as is atm

File: src/app/common/form-utils.ts [hunk 1]
```diff
@@ -9,6 +9,10 @@ export function useShowFieldError(name: string) {
   const form = useFormikContext();
   const [_, meta] = useField(name);
   const isDirty = useIsFieldDirty(name);
```
Comment (pete-watters) [inline src/app/common/form-utils.ts:11]: This change means we won't show an error until the user un-focuses from the field. Validation will still run `onBlur` but the error won't be shown until they un-focus:

https://github.com/hirosystems/wallet/assets/2938440/8565e810-bc06-498c-9b99-56674c1e3d11

Without this fix, we show an error immediately as they are focused and entering any value, correct or not:


https://github.com/hirosystems/wallet/assets/2938440/3c2c57f0-723f-4e6f-bfae-47de7ddf8722
