### PR TITLE
fix: sign message oncancel

### LINKED ISSUE #2444: onCancel doesn't fire on message signing screen consistently
Only the "cancel" button seems to fire the onCancel handler correctly. see video:

https://user-images.githubusercontent.com/11803153/169530520-0e083fbe-7f22-4e98-80f9-aa270e30577b.mp4

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/2480182728).

This PR should fix `onCancel` not firing when a user closes the popup during message signing.

Screen Shot 2022-06-10 at 2 32 24 PM

cc/ @kyranjamie @fbwoolf @beguene

### CODE REVIEW

File: src/app/components/container/container.tsx [hunk 1]
```diff
@@ -24,8 +28,17 @@ function UnmountEffectSuspense() {
       await handleCancelTransaction();
     } else if (!!authRequest) {
       cancelAuthentication();
+    } else if (signatureRequest && tabIdInt) {
```
Comment (aulneau) [inline src/app/components/container/container.tsx]: if tabIdInt === 0, this will be false

Comment (fbwoolf) [reply src/app/components/container/container.tsx]: Hello! Thx, will fix. 😄

**Review by beguene — APPROVED** [review]
