### PR TITLE
fix: prevent form submit on tooltip click, ref #5258

### LINKED ISSUE #5258: Prevent submission when selecting info icon in send flow for available balance
I'm not sure why it currently submits the form but it does:

https://github.com/leather-wallet/extension/assets/28991/11d25d42-3bdb-4dcc-94c5-f9fa97653ca3

### PR DESCRIPTION
**Pull request by pete-watters**
> Try out Leather build 2013e29 — [Extension build](https://github.com/leather-wallet/extension/actions/runs/8756256332), [Test report](https://leather-wallet.github.io/playwright-reports/fix/5258/stop-send-submit-on-tooltip-click), [Storybook](https://fix-5258-stop-send-submit-on-tooltip-click--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=fix/5258/stop-send-submit-on-tooltip-click)

This PR stops the send form submit from triggering when clicking on the tooltip icon.

### CODE REVIEW

File: src/app/ui/components/containers/footers/available-balance.tsx [hunk 1]
```diff
@@ -18,7 +18,11 @@ export function AvailableBalance({
         <styled.span color="ink.text-subdued" textStyle="caption.01">
           Available balance
         </styled.span>
-        <BasicTooltip label={balanceTooltipLabel} side="top">
+        <BasicTooltip
+          label={balanceTooltipLabel}
+          side="top"
+          onClickTrigger={e => e.preventDefault()}
```
Comment (kyranjamie) [inline src/app/ui/components/containers/footers/available-balance.tsx]: If you set `asChild`, it won't be a button and would avoid this

IMO `asChild` should be default (regarldess of accessibility concerns)

Comment (pete-watters) [reply src/app/ui/components/containers/footers/available-balance.tsx]: Thanks, I didn't know that. It's much cleaner. 

I held off making it default for now

**Review by kyranjamie — APPROVED** [review]
