### PR TITLE
fix: refactor error label to align icon and make text consistent size

### LINKED ISSUE #4166: fix icon alignment for send form validation errors
Image

### PR DESCRIPTION
**Pull request by pete-watters**
> Try out this version of Leather — [download extension builds](https://github.com/leather-wallet/extension/actions/runs/6747160197).

This PR refactors the `ErrorLabel` component so that the text and icon line up correctly. 

It also standardises the font size and colour we are using

Screenshot 2023-11-03 at 12 29 40
Screenshot 2023-11-03 at 12 27 38
Screenshot 2023-11-03 at 12 24 21
Screenshot 2023-11-03 at 12 21 55
Screenshot 2023-11-03 at 12 21 46

### CODE REVIEW

**Review by kyranjamie — APPROVED** [review]

File: src/app/components/error-label.tsx [hunk 1]
```diff
@@ -1,24 +1,26 @@
...
-      <Box
-        size="1rem"
-        color={color('feedback-error')}
-        as={FiAlertCircle}
-        position="relative"
-        strokeWidth={1.5}
-      />
-      <Box>{children}</Box>
-    </Stack>
+      <FiAlertCircle size="1rem" />
```
Comment (fbwoolf) [inline src/app/components/error-label.tsx]: This should be swapped out for our new icons. We should be replacing all Fi icons we come across, correct? There is an `AlertIcon` to use here.

**Review by fbwoolf — APPROVED** [review]

File: src/app/components/error-label.tsx (hunk 1 above)
Comment (pete-watters) [reply src/app/components/error-label.tsx]: Thanks, I can swap that out
