### PR TITLE
fix: default to first account when signing in on gamma as useCurrentS…

### LINKED ISSUE #5683: Account Select header not shown on Gamma for STX purchases with empty account
On Gamma, if you have a new empty wallet and try to purchase a STX NFT the approval popup header is blank as it cannot access the STX current account. 

I discovered this when working on https://github.com/leather-io/extension/pull/5671

Steps to reproduce:
- Create a new wallet
- Login to `gamma` with leather 
- try and buy an NFT with the wallet 

You will see an approval screen similar to this with an empty header:
Screenshot 2024-07-24 at 12 15 38

We should add a fallback so that if there is no account available yet (as its a new empty wallet) we instead show the Leather logo

### PR DESCRIPTION
**Pull request by pete-watters**
> Try out Leather build d5b9d4c — [Extension build](https://github.com/leather-io/extension/actions/runs/10217309874), [Test report](https://leather-io.github.io/playwright-reports/fix-5683-gamma-account-header), [Storybook](https://fix-5683-gamma-account-header--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=fix-5683-gamma-account-header)

This PR fixes a bug with the popup header on Gamma where:

-  if you have a new empty wallet
- you try to purchase a STX NFT 
- the approval popup header is blank 
- as it cannot access the STX current account

### CODE REVIEW

File: src/app/features/current-account/current-account-name.tsx [hunk 1]
```diff
@@ -20,9 +20,7 @@ function AccountNameTitle({ children, ...props }: HasChildren & BoxProps) {
 }
 
 const AccountNameSuspense = memo((props: BoxProps) => {
-  const currentAccount = useCurrentStacksAccount();
   const { data: name = 'Account' } = useCurrentAccountDisplayName();
-  if (!currentAccount || typeof currentAccount.index === 'undefined') return null;
```
Comment (pete-watters) [inline src/app/features/current-account/current-account-name.tsx:25]: This seems un-necessary as we show a fallback default and always have at least one account to show

**Comment by markmhendrickson** [comment]
@alter-eggo @kyranjamie could one of you review today so we can include in https://github.com/leather-io/extension/pull/5726?

**Review by alter-eggo — APPROVED** [review]

**Review by kyranjamie — APPROVED** [review]
