### PR TITLE
fix: show spinner when activity is loading

### LINKED ISSUE #2276: Add loading state for the Activity list
The activity list has a slight delay before displaying the transactions to the user. It now displays the empty state for a brief period of time, but this looks like a bug. By adding a skeleton loading state to the transaction list, we enhance the UX by presenting a better loading experience.

### PR DESCRIPTION
**Pull request by edu-stx**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/3369651362).

Based off of https://github.com/hirosystems/stacks-wallet-web/pull/2744, which should be merged first.

Fixes https://github.com/hirosystems/stacks-wallet-web/issues/2276

image

### CODE REVIEW

**Comment by fbwoolf** [comment]
Did you by chance branch off your other PR before going back to dev? It appears all your punycode changes are here as well?

**Comment by fbwoolf** [comment]
Can you rebase this on dev?

File: src/app/features/activity-list/activity-list.tsx [hunk 1]
```diff
@@ -2,7 +2,7 @@ import { useMemo } from 'react';
 
 import { useGetAccountTransactionsWithTransfersQuery } from '@app/query/stacks/transactions/transactions-with-transfers.query';
 import { useGetBitcoinTransactionsByAddressQuery } from '@app/query/bitcoin/address/transactions-by-address.query';
-import { useStacksPendingTransactions } from '@app/query/stacks/mempool/mempool.hooks';
+import { useStacksPendingTransactionsQuery } from '@app/query/stacks/mempool/mempool.hooks';
```
Comment (fbwoolf) [inline src/app/features/activity-list/activity-list.tsx]: Typically, I was using `Query` in the naming only if it was the hook exposing the actual query.

Comment (fbwoolf) [reply src/app/features/activity-list/activity-list.tsx]: So, in this case, I would have changed `useAccountMempool` to `useAccountMempoolQuery` instead.

File: src/app/features/activity-list/activity-list.tsx [hunk 2]
```diff
@@ -11,14 +11,26 @@ import { SubmittedTransactionList } from './components/submitted-transaction-lis
 import { TransactionList } from './components/transaction-list/transaction-list';
 import { PendingTransactionList } from './components/pending-transaction-list/pending-transaction-list';
 import { convertBitcoinTxsToListType, convertStacksTxsToListType } from './activity-list.utils';
+import { LoadingSpinner } from '@app/components/loading-spinner';
```
Comment (fbwoolf) [inline src/app/features/activity-list/activity-list.tsx]: I try to keep aliased imports grouped together above local directory imports if possible.

File: src/app/common/persistence.ts [hunk 3]
```diff
@@ -11,7 +11,6 @@ export const queryClient = new QueryClient({
   defaultOptions: {
     queries: {
       cacheTime: PERSISTENCE_CACHE_TIME,
-      notifyOnChangeProps: ['data', 'error'],
```
Comment (fbwoolf) [inline src/app/common/persistence.ts:14]: It appears from this the better solution might be to change this to `tracked`?
https://tkdodo.eu/blog/react-query-render-optimizations

Comment (edu-stx) [reply src/app/common/persistence.ts:14]: Not sure how recently this update on the blog is, but at the end of the Tracked Queries section it says,

> Update: Starting with v4, tracked queries are turned on per default in React Query, and you can opt out of the feature with notifyOnChangeProps: 'all'.

We're using v4 right? So should be the same as removing this line.

Comment (fbwoolf) [reply src/app/common/persistence.ts:14]: Nice, I didn't see that update. 👍

File: src/app/features/activity-list/activity-list.tsx (hunk 1 above)
Comment (fbwoolf) [reply src/app/features/activity-list/activity-list.tsx]: For the record, I didn't see the entire query is being returned here from the hook so can ignore this.

Comment (edu-stx) [reply src/app/features/activity-list/activity-list.tsx]: If it helps can drop the `*Query` or rename to `*TransformedQuery`

File: src/app/query/stacks/mempool/mempool.hooks.ts [hunk 4]
```diff
@@ -36,13 +36,46 @@ function useAccountUnanchoredMempoolTransactions(address: string) {
...
   return useAccountUnanchoredMempoolTransactions(address ?? '').filter(
     tx => !!tx
   ) as MempoolTransaction[];
 }
 
+export function useStacksPendingTransactionsQuery() {
+  const address = useCurrentAccountStxAddressState();
+  const query = useAccountUnanchoredMempoolTransactionsQuery(address ?? '');
+  const newData = query.data.filter(tx => !!tx) as MempoolTransaction[];
+  return { ...query, data: newData };
```
Comment (kyranjamie) [inline src/app/query/stacks/mempool/mempool.hooks.ts]: Returns a new referential equality on every render

File: src/app/features/activity-list/activity-list.tsx (hunk 1 above)
Comment (kyranjamie) [reply src/app/features/activity-list/activity-list.tsx]: +1 to Fara's comment. Would keep with convention that only hooks that contain a `useQuery` use query naming

File: src/app/query/stacks/mempool/mempool.hooks.ts (hunk 4 above)
Comment (edu-stx) [reply src/app/query/stacks/mempool/mempool.hooks.ts]: To keep the same reference to `query` we can go for `query.data = newData` together with some type gymnastics to set the appropriate type in order to conserve the remaining query properties present in the `query` object. Alternatively, we can pick out a few properties from the query object, say `isInitialLoading`, `data`, and `error` to name a few, although in this case we'll always be coming back to this hook to edit its return value if a consumer ever needs more data from within the `query` object (which may be fine). So in this latter scenario the return value would change depending on what is needed by consumers.

Alternatively all of this can be moved into the component itself to have direct access to `query` and then we don't have to deal with the complexities of this intermediate hook, at the expense of making the component larger. 

What do you reckon is best? Maybe there are other options not described here?

Comment (kyranjamie) [reply src/app/query/stacks/mempool/mempool.hooks.ts]: Would avoid mutating the object.

I'd investigate either:
- parsing the response by passing in a configurable `select` to the query to handle
- return the data as a `useMemo`

Comment (edu-stx) [reply src/app/query/stacks/mempool/mempool.hooks.ts]: After investigating a little I came across `useAccountUnanchoredMempoolTransactions` that complicates refactoring due to its side effects and use of external state: the state and query object live in different files, so getting query data to the component that needs it would require significant refactoring.

@kyranjamie and i settled for not refactoring this too much as the implications of these side effects are not trivial to follow, and opting for analytics to keep track of how often the side effect occurs.

**Comment by edu-stx** [comment]
@kyranjamie @fbwoolf looking forward to merging this: any further changes you'd like to see?

**Review by fbwoolf — APPROVED** [review]

**Comment by kyranjamie** [comment]
Sorry for the slow response here, wonder if it makes sense to merge the ReactQuery refactor, and fix this with the `select` pattern. Let's discuss in kick off later today

**Comment by edu-stx** [comment]
@kyranjamie we can come back to this when the ReactQuery refactor is merged, allowing us to get this fix out faster and we can still chose whether to tackle any remaining work as part of the refactor or at a later time.
