### PR TITLE
fix: fix fund page responsiveness, refactor mediaQuery, closes #4188

### LINKED ISSUE #4188: Fix resizing on the buying step
Screenshot 2023-09-06 at 16 52 20
Screenshot 2023-09-06 at 16 49 34

-------------

**How it should look:**
Same as the old Hiro wallet before
Screenshot 2023-09-06 at 16 52 42

### PR DESCRIPTION
**Pull request by pete-watters**
> Try out this version of Leather — [download extension builds](https://github.com/leather-wallet/extension/actions/runs/6406323068).

This PR fixes the responsive view of the funding page:
https://github.com/leather-wallet/extension/assets/2938440/e4402fff-1bac-4656-8a12-9161b2dd30d7

I also made a couple of slight refactors to other pages, namely the account selector so I have included a visual of that also

### CODE REVIEW

File: src/app/components/account/account-list-item-layout.tsx [hunk 1]
```diff
@@ -42,7 +43,7 @@ export function AccountListItemLayout(props: AccountListItemLayoutProps) {
     ...rest
   } = props;
 
-  const [isNarrowViewport] = useMediaQuery('(max-width: 400px)');
+  const isBreakpointSm = useViewportMaxWidth('sm');
```
Comment (pete-watters) [inline src/app/components/account/account-list-item-layout.tsx]: I changed this so I can get rid of `useMediaQuery` from `@stacks/ui`.

Sometimes we define `isNarrowViewport` as `(max-width: 400px)` and other times `(max-width: 600px)`

File: src/app/pages/fund/components/fiat-providers-list.tsx [hunk 2]
```diff
@@ -35,12 +37,13 @@ export function FiatProvidersList(props: FiatProvidersProps) {
...
     <Grid
-      columnGap="auto"
+      columnGap="1.5rem"
       justifyContent="center"
       mt={['base', '48px']}
       p="0 3rem"
       rowGap="1.5rem"
-      templateColumns="repeat(auto-fill, minmax(270px, 1fr))"
+      placeItems="center"
+      gridTemplateColumns={isAtleastBreakpointMd ? 'repeat(4, 1fr)' : 'repeat(1, 1fr)'}
```
Comment (pete-watters) [inline src/app/pages/fund/components/fiat-providers-list.tsx]: I tried to set `gridTemplateColumns` with array syntax but I couldn't get it working properly. 


I'm not 100% on how our breakpoints work. Should I be able to use more than two in an array? Ideally here I would have 3 so we change from 1 to 2 to 4 columns

I thought it should work using this:
`gridTemplateColumns={['repeat(1, 1fr), 'repeat(2, 1fr)',  'repeat(4, 1fr)']`

This solution isn't exactly how design want it as we transition from 4 to 1 column, missing a view with 2 in the middle

File: src/app/pages/fund/fund.layout.tsx [hunk 3]
```diff
@@ -40,9 +40,7 @@ export function FundLayout(props: FundLayoutProps) {
           textAlign={['left', 'center']}
         >
           {/* TODO: Investigate removing / refactoring <PageTitle */}
-          <styled.h1 textStyle="heading.02">
-            {desktopViewport ? 'Let’s get STX into your wallet' : 'Get STX'}
-          </styled.h1>
+          <styled.h1 textStyle="heading.02">Let's get STX into your wallet</styled.h1>
```
Comment (pete-watters) [inline src/app/pages/fund/fund.layout.tsx]: In the latest design we show the full sentence here

Screenshot 2023-09-12 at 10 43 19

File: src/app/pages/home/components/account-info-card.tsx [hunk 4]
```diff
@@ -14,7 +15,7 @@ import { AccountActions } from './account-actions';
 
 export function AccountInfoCard() {
   const name = useCurrentAccountDisplayName();
-  const [isNarrowViewport] = useMediaQuery('(max-width: 600px)');
+  const [isNarrowViewport] = useMediaQuery(`(max-width: ${token('sizes.narrowViewPortMaxWidth')})`);
```
Comment (pete-watters) [inline src/app/pages/home/components/account-info-card.tsx]: I was going to refactor this to use `useViewportMaxWidth` and our sized tokens but we have no size for `600px`. 

Maybe `600px` here is outdated and it should be `md`? 

Do we need both `tokens.sizes` & `tokens.breakpoints`?

File: src/app/pages/fund/components/fiat-providers-list.tsx (hunk 2 above)
Comment (alter-eggo) [reply src/app/pages/fund/components/fiat-providers-list.tsx]: I believe this should work nice 🤔
```      
gridTemplateColumns={[
        'repeat(1, 1fr)',
        'repeat(1, 1fr)',
        'repeat(2, 1fr)',
        'repeat(3, 1fr)',
        'repeat(4, 1fr)',
      ]}
```

Comment (alter-eggo) [reply src/app/pages/fund/components/fiat-providers-list.tsx]: https://github.com/leather-wallet/extension/assets/46521087/8f03fa76-6485-4b4c-b0d1-b3d069a15ff9

File: src/app/pages/home/components/account-info-card.tsx (hunk 4 above)
Comment (alter-eggo) [reply src/app/pages/home/components/account-info-card.tsx]: I believe we can use `md` here, or better even delete and just use array:
`mr={['0px' , 'space.02']}`? smth like that

File: src/app/components/account/account-list-item-layout.tsx (hunk 1 above)
Comment (alter-eggo) [reply src/app/components/account/account-list-item-layout.tsx]: it has been written very fast and something was probably just copied as is, feel free to refactor to current breakpoint system

File: src/app/pages/home/components/account-info-card.tsx (hunk 4 above)
Comment (alter-eggo) [reply src/app/pages/home/components/account-info-card.tsx]: ~I think breakpoints is enough, no?~

Comment (alter-eggo) [reply src/app/pages/home/components/account-info-card.tsx]: hm, actually there might be some edge cases when we need that custom sizes as well, so prob better to keep them both

File: src/app/pages/fund/components/fiat-providers-list.tsx (hunk 2 above)
Comment (pete-watters) [reply src/app/pages/fund/components/fiat-providers-list.tsx]: Thanks for the help, I appreciate it! I had tried that but couldn't get it working. I'll try again 👍 

It could be as I am using the new grid from `leather-styles`. If that's not working so well we can revert or else code our own using normal CSS

Comment (alter-eggo) [reply src/app/pages/fund/components/fiat-providers-list.tsx]: I've used it in your branch 🤔

File: src/app/pages/fund/fund.layout.tsx (hunk 3 above)
Comment (kyranjamie) [inline src/app/pages/fund/fund.layout.tsx]: We want to remove the reference to STX altogether. @mica000 @markmhx

File: src/app/pages/home/components/account-info-card.tsx (hunk 4 above)
Comment (kyranjamie) [reply src/app/pages/home/components/account-info-card.tsx]: do we have to do the breakpoint at 600? Why not change it to something else?

File: src/app/components/account/account-list-item-layout.tsx (hunk 1 above)
Comment (kyranjamie) [reply src/app/components/account/account-list-item-layout.tsx]: Rather than adding the new max width breakpoint, couldn't we just invert the ternary? IMO if we can do mobile first only, that'd be better than mixing both mobile & desktop first approaches to responsive design.

File: src/app/pages/fund/components/fiat-providers-list.tsx (hunk 2 above)
Comment (pete-watters) [reply src/app/pages/fund/components/fiat-providers-list.tsx]: OK thanks, it must have been just me making a mistake 👍

File: src/app/pages/home/components/account-info-card.tsx (hunk 4 above)
Comment (pete-watters) [reply src/app/pages/home/components/account-info-card.tsx]: I can test it and see if we can do it at a different size using the `breakpoints` we have, thanks! 

Sometimes we need to use  `tokens.sizes` when specifying `maxWidth` but I think sometimes we are using them incorrectly as breakpoints. 

I'll spend some time checking and cleaning it up, thanks both 👏

File: src/app/components/account/account-list-item-layout.tsx (hunk 1 above)
Comment (pete-watters) [reply src/app/components/account/account-list-item-layout.tsx]: OK, thanks! I will review the code and improve it from a mobile first perspective

File: src/app/pages/fund/fund.layout.tsx (hunk 3 above)
Comment (markmhendrickson) [reply src/app/pages/fund/fund.layout.tsx]: We can go with `Let's get funds into your wallet` for now

**Comment by markmhendrickson** [comment]
@pete-watters is this ready for re-review?

**Comment by pete-watters** [comment]
> @pete-watters is this ready for re-review?

No not yet. I'll work on it tomorrow

File: src/app/pages/fund/fund.layout.tsx (hunk 3 above)
Comment (pete-watters) [reply src/app/pages/fund/fund.layout.tsx]: Updated

File: src/app/pages/fund/components/fiat-providers-list.tsx (hunk 2 above)
Comment (pete-watters) [reply src/app/pages/fund/components/fiat-providers-list.tsx]: Updated it with your code, thanks!

**Review by kyranjamie — APPROVED** [review]

File: src/app/components/account/account-list-item-layout.tsx [hunk 5]
```diff
@@ -54,35 +56,35 @@ export function AccountListItemLayout(props: AccountListItemLayoutProps) {
...
             ) : (
               balanceLabel
             )}
           </HStack>
-          <Stack alignItems="center" spacing="6px" isInline whiteSpace="nowrap">
+          <HStack alignItems="center" gap="space.02" whiteSpace="nowrap">
             <CaptionDotSeparator>
               <styled.span textStyle="caption.02">
-                {truncateMiddle(stxAddress, isNarrowViewport ? 3 : 4)}
+                {truncateMiddle(stxAddress, isBreakpointSm ? 4 : 3)}
```
Comment (pete-watters) [inline src/app/components/account/account-list-item-layout.tsx:81]: I don't think we need this `isBreakpointSm` part here. It's changing how much we truncate the address based on the viewport. 

It doesn't really make much difference as we can handle a longer address in each section. 

Current code:
Screenshot 2023-10-04 at 14 00 20

Setting it to `4` and no `isBreakpointSm`
Screenshot 2023-10-04 at 14 01 14

Comment (pete-watters) [reply src/app/components/account/account-list-item-layout.tsx:81]: @kyranjamie let me know what you think here

Comment (kyranjamie) [reply src/app/components/account/account-list-item-layout.tsx:81]: I would've been fine removing this

Comment (pete-watters) [reply src/app/components/account/account-list-item-layout.tsx:81]: OK, I'll remove it soon 👍
