### PR TITLE
fix: user should be able to buy stacks for stacks account

### LINKED ISSUE #4760: Fix buy screen when connected with Stacks via Ledger but not Bitcoin
Currently I get the below error if I'm not connected with both and try to visit.

Image

### PR DESCRIPTION
**Pull request by edgarkhanzadian**
Closes #4760 

https://github.com/leather-wallet/extension/assets/22010816/cfd5c78b-c85d-42fa-8e61-72c6d00d326d

https://github.com/leather-wallet/extension/assets/22010816/b467c183-1eb7-4776-b1f7-c0d5b88bb5de

> Try out this version of Leather — [Extension build](https://github.com/leather-wallet/extension/actions/runs/7462360895), [Test report](https://leather-wallet.github.io/playwright-reports/fix/ledger-stacks-buy)

### CODE REVIEW

File: src/app/pages/fund/util.ts [hunk 1]
```diff
@@ -0,0 +1,18 @@
+import { useStxBalance } from '@app/common/hooks/balance/stx/use-stx-balance';
+import { useNativeSegwitBalance } from '@app/query/bitcoin/balance/btc-native-segwit-balance.hooks';
+import { createStacksCryptoCurrencyAssetTypeWrapper } from '@app/query/stacks/balance/stacks-ft-balances.utils';
+import { useCurrentAccountNativeSegwitSigner } from '@app/store/accounts/blockchain/bitcoin/native-segwit-account.hooks';
+
+export function useBtcCryptoCurrencyAssetBalance() {
```
Comment (fbwoolf) [inline src/app/pages/fund/util.ts]: Not sure a hook should be in a `util` file? We have a pattern for handling hooks using `.hooks.ts`. Also, aren't these exposed for you in a shareable spot already? If not, I would refactor an existing hook, like `useStxBalance` to make available what you need but allow others to use it too? `useAllTransferableCryptoAssetBalances`?

Comment (edgarkhanzadian) [reply src/app/pages/fund/util.ts]: Good point! Moved those to the hooks folder

File: src/app/store/accounts/blockchain/bitcoin/native-segwit-account.hooks.ts [hunk 2]
```diff
@@ -90,6 +90,8 @@ export function useCurrentAccountNativeSegwitSigner() {
   return useNativeSegwitSigner(currentAccountIndex);
 }
 
+// TODO: as ledger users are able to have only stacks account on their devices, this hook throws an unnecessary error.
```
Comment (pete-watters) [inline src/app/store/accounts/blockchain/bitcoin/native-segwit-account.hooks.ts:93]: Is this correct? I have a BTC account connected?

File: src/app/common/hooks/balance/btc/use-btc-crypto-currency-asset-balance.ts [hunk 3]
```diff
@@ -0,0 +1,11 @@
+import { useNativeSegwitBalance } from '@app/query/bitcoin/balance/btc-native-segwit-balance.hooks';
+import { useCurrentAccountNativeSegwitSigner } from '@app/store/accounts/blockchain/bitcoin/native-segwit-account.hooks';
+
+export function useBtcCryptoCurrencyAssetBalance() {
+  const currentBtcSigner = useCurrentAccountNativeSegwitSigner();
+  // TODO: it would be better if we could skip providing the empty string to this hook.
```
Comment (pete-watters) [inline src/app/common/hooks/balance/btc/use-btc-crypto-currency-asset-balance.ts:6]: Can we refactor this now?

**Review by pete-watters — APPROVED** [review]
This code LGTM. Maybe we can also fix this UI bug I noticed in your video where:
- it says `title` as the title
- the icon alignment is not correct

Screenshot 2024-01-08 at 05 52 05

File: src/app/store/accounts/blockchain/bitcoin/native-segwit-account.hooks.ts (hunk 2 above)
Comment (edgarkhanzadian) [reply src/app/store/accounts/blockchain/bitcoin/native-segwit-account.hooks.ts:93]: Oh sorry, i'll update the comment. I meant that users can have only stacks account _connected_ to the wallet

**Comment by edgarkhanzadian** [comment]
@pete-watters oh right that screenshot is coming from an uncommited code :D i was playing a bit with radix callouts

File: src/app/common/hooks/balance/btc/use-btc-crypto-currency-asset-balance.ts (hunk 3 above)
Comment (edgarkhanzadian) [reply src/app/common/hooks/balance/btc/use-btc-crypto-currency-asset-balance.ts:6]: I tried it back then and it seemed like it would require quite a handful of code changes. I will see if i could do it now with a minimal amount of changes, if not will leave it for later

Comment (pete-watters) [reply src/app/common/hooks/balance/btc/use-btc-crypto-currency-asset-balance.ts:6]: OK great, thanks!

**Comment by pete-watters** [comment]
> @pete-watters oh right that screenshot is coming from an uncommited code :D i was playing a bit with radix callouts

haha OK don't worry about it so 😄

File: src/app/pages/fund/choose-asset-to-fund/choose-asset-to-fund.tsx [hunk 4]
```diff
@@ -44,12 +36,14 @@ export function ChooseCryptoAssetToFund() {
...
   const filteredCryptoAssetBalances = useMemo(
     () =>
-      cryptoCurrencyAssetBalances.filter(assetBalance =>
-        whenWallet({
-          ledger: checkBlockchainAvailable(assetBalance.blockchain),
-          software: true,
-        })
-      ),
+      cryptoCurrencyAssetBalances
+        .filter((assetBalance): assetBalance is CryptoAssetBalance => assetBalance != null)
```
Comment (kyranjamie) [inline src/app/pages/fund/choose-asset-to-fund/choose-asset-to-fund.tsx]: Can we avoid the single equals expressions here? I know this check also checks for undefined but is very unobvious. We don't use elsewhere in app. 

Could use `isDefined` instead?

**Review by kyranjamie — APPROVED** [review]

File: src/app/pages/fund/choose-asset-to-fund/choose-asset-to-fund.tsx (hunk 4 above)
Comment (edgarkhanzadian) [reply src/app/pages/fund/choose-asset-to-fund/choose-asset-to-fund.tsx]: Good point, done!
