### PR TITLE
fix: mark ui bugs

### LINKED ISSUE #4574: Mark's stacks/ui-removal visual feedback

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of Leather — [download extension builds](https://github.com/leather-wallet/extension/actions/runs/7012911934).

Fixes minor UI bugs.

### CODE REVIEW

**Comment by fbwoolf** [comment]
@markmhendrickson this is broken in prod too, I fixed but had to make the text really small to fit. Ok? cc @mica000 

Screenshot 2023-11-27 at 4 32 18 PM

**Comment by fbwoolf** [comment]
Fixed this too @markmhendrickson, sorry about that! It was hardcoded during the UI refactor. 🙃 

image

File: src/app/components/json.tsx [hunk 1]
```diff
@@ -4,6 +4,14 @@ import { Box } from 'leather-styles/jsx';
 
 import { isBigInt, isTypedArray } from '@shared/utils';
 
+export function parseJson(content: string) {
```
Comment (pete-watters) [inline src/app/components/json.tsx:7]: Nice refactor 👍

**Review by pete-watters — APPROVED** [review]
