### PR TITLE
fix: use routes over state for home tabs, closes #3518

### LINKED ISSUE #3518: Refactor: remove state for activity page, use route
Currently we use a jotai atom's state to toggle & persist the state of the homepage tabs.

I suggest we use routes to handle this state, as it relates to a place/location within the UI.

- Balance `/`
- Activity `/activity`

This also simplifies logic use throughout the app, such as navigating home _and_ changing this state, such as in the case when we broadcast a tx.

### LINKED ISSUE #4013: Refactor: remove state for choose page, use route
In the `choose-fee-tab` we are using state to manage the selected tab. We should refactor this to share the same logic that was introduced to the home tabs in issue #3518 PR #4001

### PR DESCRIPTION
**Pull request by pete-watters**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/wallet/actions/runs/5553897686).

## Description
This PR is a refactor to remove the use of state to track home page tabs in favour of routes. Routes should be used when we are working with a place or location in the APP

## Type of Change
- Refactor

## Testing information

This change can be tested by testing the HomePage and ensuring tab navigation between Balances and Activities is still working correctly

### CODE REVIEW

File: src/app/pages/home/components/home-tabs.tsx [hunk 1]
```diff
@@ -13,53 +14,54 @@ interface HomeTabsProps extends StackProps {
...
+      { slug: RouteUrls.Activities, label: 'Activity' },
+    ],
+    []
+  );
 
-  const { activeTab, setActiveTab } = useHomeTabs();
+  const getActiveTab = useCallback(
+    () => tabs.findIndex(tab => tab.slug === pathname),
+    [tabs, pathname]
+  );
```
Comment (pete-watters) [inline src/app/pages/home/components/home-tabs.tsx:32]: I'm not sure if we still want to trigger analytics here? I can add it. 

Now we will track a page view on the `/activities` route and can infer balances are seen at `/`

File: src/app/pages/home/components/home-tabs.tsx [hunk 2]
```diff
@@ -13,53 +14,54 @@ interface HomeTabsProps extends StackProps {
...
-                  {activity}
-                </Box>
-              )}
-            </SlideFade>
-          </Suspense>
-        )}
+        <Suspense fallback={<LoadingSpinner pb="72px" />}>
+          <SlideFade in={true}>
+            {styles => (
+              <Box style={styles} width="100%">
```
Comment (pete-watters) [inline src/app/pages/home/components/home-tabs.tsx]: I'm using a `pathname` switch here but it would probably be cleaner to use nested routes. 

I was a bit confused how to get this working properly and am open to improvement suggestions.

File: src/app/features/retrieve-taproot-to-native-segwit/retrieve-taproot-to-native-segwit.tsx [hunk 3]
```diff
@@ -41,8 +39,7 @@ export function RetrieveTaprootToNativeSegwit() {
         await delay(1200);
         toast.success('Transaction broadcasted succesfully');
         await delay(700);
```
Comment (pete-watters) [inline src/app/features/retrieve-taproot-to-native-segwit/retrieve-taproot-to-native-segwit.tsx:41]: I could do with some help manually testing this flow

Comment (kyranjamie) [reply src/app/features/retrieve-taproot-to-native-segwit/retrieve-taproot-to-native-segwit.tsx:41]: To test this e2e, you'll need to send some btc to a taproot address and this option will appear

File: src/app/pages/home/components/home-tabs.tsx (hunk 1 above)
Comment (kyranjamie) [reply src/app/pages/home/components/home-tabs.tsx:32]: Nope, this can be killed now that we're using routes

File: src/app/pages/home/components/home-tabs.tsx (hunk 2 above)
Comment (kyranjamie) [reply src/app/pages/home/components/home-tabs.tsx]: Don't fully understand what's going on here, but wonder if there's a way to achieve this routing set up with `<Outlet />`, with a routing structure where we describe the activity component on the route?

`<Route path={RouteUrls.Activities} element={<ActivityList />} />`?  

Home already has an outlet, and this might require you to move it to the tabs, but think that's okay? Worth trying to do it this way as I think that'd be more to the spec,  but if too difficult, this implementation is still an improvement.

This would be better as routes should have associated components, and this kinda emulates routes. Saw there's a warning about this

image

Comment (pete-watters) [reply src/app/pages/home/components/home-tabs.tsx]: Thanks @kyranjamie I'll check that out. I was trying to use sub-routes in home tabs but I was facing an issue where it kept re-directing back to `/`. 

I'll try again and also move the outlet and get rid of that warning, thanks!

File: src/app/features/balances-list/balances-list.tsx [hunk 4]
```diff
@@ -20,11 +22,12 @@ import { PendingBrc20TransferList } from '../pending-brc-20-transfers/pending-br
 import { BitcoinFungibleTokenAssetList } from './components/bitcoin-fungible-tokens-asset-list';
 import { StacksFungibleTokenAssetList } from './components/stacks-fungible-token-asset-list';
 
-interface BalancesListProps extends StackProps {
+interface BalancesListContextState {
   address: string;
 }
```
Comment (pete-watters) [inline src/app/features/balances-list/balances-list.tsx:28]: I removed `...props` from here as I couldn't see it doing anything. That could be incorrect though and I can re-add if needed

File: src/app/pages/home/components/home-tabs.tsx [hunk 5]
```diff
@@ -1,66 +1,51 @@
...
-          { slug: 'balances', label: 'Balances' },
-          { slug: 'activity', label: 'Activity' },
-        ]}
-        activeTab={activeTab}
-        onTabClick={setActiveTabTracked}
+        tabs={tabs}
+        activeTab={getActiveTab()}
+        onTabClick={setActiveTab}
         width={['100%', '193px']}
       />
```
Comment (pete-watters) [inline src/app/pages/home/components/home-tabs.tsx:45]: Now we are using routes, I couldn't notice the `SlideFade` doing anything anymore so I removed it. Similarly the `Flex` container here seems superfluous although that could be incorrect.

Here's how it looks now:

https://github.com/hirosystems/wallet/assets/2938440/1fd84a48-d95b-4e85-bf80-bced49e3a5d1

@mica000  - does this look OK to you or do we need a fade / some better animation here

File: src/app/components/tabs.tsx [hunk 6]
```diff
@@ -69,7 +69,7 @@ export function Tabs({
         {tabs.map((tab, index) => (
           <TabButton
             onClick={() => onTabClick(index)}
```
Comment (pete-watters) [inline src/app/components/tabs.tsx:72]: Proof that tests work and are valuable as this was causing test failures 😄

File: src/app/features/bitcoin-choose-fee/components/choose-fee-tabs.tsx [hunk 7]
```diff
@@ -16,7 +16,7 @@ interface ChooseFeeTabsProps extends StackProps {
 export function ChooseFeeTabs(props: ChooseFeeTabsProps) {
   const { feesList, customFee, ...rest } = props;
   const analytics = useAnalytics();
```
Comment (pete-watters) [inline src/app/features/bitcoin-choose-fee/components/choose-fee-tabs.tsx:18]: I guess I should open a new issue for this refactor?

File: src/app/pages/home/components/home-tabs.tsx [hunk 8]
```diff
@@ -1,66 +1,51 @@
...
+import { RouteUrls } from '@shared/route-urls';
+
 import { LoadingSpinner } from '@app/components/loading-spinner';
 import { Tabs } from '@app/components/tabs';
 
 interface HomeTabsProps extends StackProps {
-  balances: React.JSX.Element;
-  activity: React.JSX.Element;
+  children: React.JSX.Element;
 }
```
Comment (pete-watters) [inline src/app/pages/home/components/home-tabs.tsx:14]: When we are ready to use routes in `choose-fee-tab` we can share the code so that a `Tabs` component will accept `tabs` as a prop and `Outlet` as it's `children` and have a generic component

File: src/app/features/balances-list/balances-list.tsx (hunk 4 above)
Comment (fbwoolf) [reply src/app/features/balances-list/balances-list.tsx:28]: Yeah, I don't see any props being passed, so I think it makes sense to remove it.

File: src/app/features/bitcoin-choose-fee/components/choose-fee-tabs.tsx (hunk 7 above)
Comment (fbwoolf) [reply src/app/features/bitcoin-choose-fee/components/choose-fee-tabs.tsx:18]: Yep, good idea. 👍

File: src/app/pages/home/components/home-tabs.tsx (hunk 8 above)
Comment (fbwoolf) [reply src/app/pages/home/components/home-tabs.tsx:14]: Might make sense for you to just do that refactor next? @markmhx

File: src/app/pages/home/components/home-tabs.tsx [hunk 9]
```diff
@@ -1,66 +1,51 @@
...
+// TODO: Abstract this to generic RouteTab once choose-fee-tab updated
+export function HomeTabs({ children }: HomeTabsProps) {
+  const navigate = useNavigate();
+  const { pathname } = useLocation();
+
+  const tabs = useMemo(
+    () => [
+      { slug: RouteUrls.Home, label: 'balances' },
+      { slug: RouteUrls.Activities, label: 'activity' },
```
Comment (fbwoolf) [inline src/app/pages/home/components/home-tabs.tsx]: Just curious here, why plural? `RouteUrls.Activity`?

**Review by fbwoolf — APPROVED** [review]
Nice work @pete-watters, lgtm!

File: src/app/pages/home/components/home-tabs.tsx (hunk 9 above)
Comment (pete-watters) [reply src/app/pages/home/components/home-tabs.tsx]: It's an oversight, I'll change it to `RouteUrls.Activity`, thanks! 👍

File: src/app/pages/home/components/home-tabs.tsx (hunk 8 above)
Comment (pete-watters) [reply src/app/pages/home/components/home-tabs.tsx:14]: I created an issue for it #4013 and assigned it to myself. I'll tackle it once work has finished on the fee tab, it won't take long

**Review by alter-eggo — APPROVED** [review]
👍
