### PR TITLE
fix: remove gaia call when unlocking wallet

### LINKED ISSUE #1877: Reduce dependence on Gaia hub
In investigating #1732, I noticed that the wallet breaks if it cannot connect to its Gaia hub.

https://github.com/blockstack/stacks-wallet-web/pull/1870 fixes the most immediate problem: Handling the error cases, by failing silently, ensuring the wallet still works when Gaia is unavailable.

We can, and probably should, further reduce the reliance the wallet has on Gaia.

To explain further: "Creating an account" is simply generating another key. If the resulting address has no balance, nor activity, there is no way to "know" its was ever generated. So, if you were to create 10 accounts, delete, then restore your wallet, we can't know this ever happened. _Unless_ we persist somewhere. This is where Gaia is used. It's updated every time you create a new account.

Currently, we request the "generated account info" / `wallet-config.json` from Gaia on every wallet unlock. Which:
1. Slows down every wallet sign in
2. Adds a reliance on a separate web service

If I understand correctly, the only information we need is the index of the latest account generated. If so, a more resilient implementation might request Gaia on account restoration, but following that, manage this integer locally.

cc/ @hstove @aulneau is there more to the relationship wallet-sdk has to Gaia, in context of account generation?

---------------------------

Edit 2021-12-04: per some of the issues on slow wallet unlock times, I did 5 tests in either scenario:

```
Stable release:
5564ms

Stable release, Fast 3g network throttling:
9446ms

Without gaia dependence
4560ms
```

### PR DESCRIPTION
**Pull request by beguene**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/1602927371).

This PR removes Gaia dependency on unlock. The goal is to reduce the unlock time (see #2002 )
The Gaia wallet config is now stored in localStorage to not have to make a call to Gaia when not necessary.
The wallet config is stored on account creation and when importing an existing wallet (with seed) and setting the password.
I kept the old path (fetching Gaia on unlock) for the special case when the user updates the hiro wallet while being in 'lock' screen. In that case he won't have the locally stored wallet config. We can safely remove this path in a few months.
Besides I moved some code outside the big 'vaults.ts'

cc/ @kyranjamie @fbwoolf

### CODE REVIEW

File: src/common/wallet/wallet-config-helper.ts [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+import { gaiaUrl } from '@common/constants';
+import { logger } from '@common/logger';
+
+export function saveWalletConfigLocally(walletConfig: WalletConfig) {
+  persistOptional('walletConfig', JSON.stringify(walletConfig));
+  return walletConfig;
+}
+
+export async function getWalletConfig(wallet: Wallet | undefined) {
+  if (!wallet) return;
```
Comment (kyranjamie) [inline src/common/wallet/wallet-config-helper.ts]: Can the logic for when it's undefined be handled by the code invoking this function?

File: src/background/wallet/wallet-utils.ts [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+  const rootNode = await rootNodeFromSecretKey(secretKey);
+  if (!walletConfig) return [] as Account[];
+  return accountsFromWalletConfig(walletConfig, rootNode, salt);
+}
+
+export async function getWallet(
+  secretKey: string,
+  salt: string,
+  password: string
+): Promise<SDKWallet | undefined> {
```
Comment (kyranjamie) [inline src/background/wallet/wallet-utils.ts]: For consistency, could this be an object too, as above? Somewhat stylistic, but imo for readability, it's clearer to have a separate interface for the arguments, rather than defining it inline.

File: src/background/wallet/wallet-utils.ts [hunk 3]
```diff
@@ -0,0 +1,73 @@
+import { Account, deriveAccount, generateWallet, WalletConfig } from '@stacks/wallet-sdk';
+import { Wallet as SDKWallet } from '@stacks/wallet-sdk';
+import { mnemonicToSeed } from 'bip39';
+import { fromSeed } from 'bip32';
+import { BIP32Interface } from 'bitcoinjs-lib';
+
+function getSavedWalletConfig() {
+  const walletConfig = localStorage.getItem('walletConfig');
+  if (typeof walletConfig !== 'string') return;
+  return JSON.parse(walletConfig) as WalletConfig;
```
Comment (kyranjamie) [inline src/background/wallet/wallet-utils.ts]: This is an unsafe operation, will throw if the value is invalid JSON.

File: src/background/wallet/unlock-wallet.ts [hunk 4]
```diff
@@ -0,0 +1,32 @@
+import { decryptMnemonic } from '@background/crypto/mnemonic-encryption';
+import { getWallet } from './wallet-utils';
+
+export async function unlockWallet(
```
Comment (kyranjamie) [inline src/background/wallet/unlock-wallet.ts]: Would consider renaming this method. "Unlocking the wallet" is what we tell the user, but as far as this method goes, I'd use something more technically descriptive. `getDecryptedWalletDetails`?

File: src/common/storage.ts [hunk 5]
```diff
@@ -61,3 +61,11 @@ export function deleteTabForRequest(storageKey: StorageKey, request: string) {
   const key = getKeyForRequest(storageKey, request);
   localStorage.removeItem(key);
 }
+
+export function persistOptional(storageKey: string, value?: string) {
```
Comment (kyranjamie) [inline src/common/storage.ts]: In https://github.com/hirosystems/stacks-wallet-web/pull/2061 I've renamed this method to `setToLocalstorageIfDefined` as this is a really bad name. Perhaps we can rename here instead.

I think we can also remove the else (even more confusing that it removes that value).

**Review by kyranjamie — COMMENTED** [review]
Afaik, we only use Gaia to save the number of accounts generated. Is this correct? 

If so, wouldn't it be safer/easier to persist only the highest generated account index, rather than the entire Gaia config?

**Comment by beguene** [comment]
> Afaik, we only use Gaia to save the number of accounts generated. Is this correct?
> 
> If so, wouldn't it be safer/easier to persist only the highest generated account index, rather than the entire Gaia config?

Yes for accounts generated we can save the highest index, but we anyway have to make a call to Gaia when importing a wallet.
I store the full config so we can later optimise other parts of wallet relying on Gaia. By saving the full config, we don't need for example to fetch username again.

File: src/background/wallet/wallet-utils.ts [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+
+  const accounts = await getSavedWalletAccounts({
+    secretKey,
+    walletConfig,
+    salt,
+  });
+
+  if (accounts.length === 0) return wallet;
+
+  return { ...wallet, ...{ accounts } };
```
Comment (fbwoolf) [inline src/background/wallet/wallet-utils.ts]: What is the spread operator doing here? `...{ accounts }`

**Review by fbwoolf — APPROVED** [review]
Looks good @beguene 👍 . There is an empty file `src/common/hooks/get-wallet-config.ts`.

File: src/background/wallet/wallet-utils.ts (hunk 6 above)
Comment (beguene) [reply src/background/wallet/wallet-utils.ts]: Nice catch, this is not needed (reminiscence of an old code)

**Review by kyranjamie — APPROVED** [review]
