### PR TITLE
fix: only show swaps option on mainnet

### LINKED ISSUE #4687: Hide swaps option on testnet / any network other than mainnet
Since the ALEX SDK doesn't support it yet

### PR DESCRIPTION
**Pull request by edgarkhanzadian**
> Try out this version of Leather — [Extension build](https://github.com/leather-wallet/extension/actions/runs/7246863711), [Test report](https://leather-wallet.github.io/playwright-reports/fix/only-show-swaps-on-mainnet)

Closes #4687

https://github.com/leather-wallet/extension/assets/22010816/c4d30d6d-ae87-4b42-94d4-30b3c84d737a

### CODE REVIEW

**Review by pete-watters — APPROVED** [review]

File: src/app/pages/home/components/account-actions.tsx [hunk 1]
```diff
@@ -43,12 +48,14 @@ export function AccountActions(props: FlexProps) {
...
-        onClick={() => navigate(RouteUrls.Swap)}
-      />
+      {isMainnet && (
+        <ActionButton
+          data-testid={HomePageSelectors.SwapBtn}
+          icon={<SwapIcon />}
+          label="Swap"
+          onClick={() => navigate(RouteUrls.Swap)}
+        />
+      )}
```
Comment (kyranjamie) [inline src/app/pages/home/components/account-actions.tsx]: We have a `whenNetwork` helper you can use here to avoid the equality expression on L26

**Review by kyranjamie — APPROVED** [review]

**Comment by kyranjamie** [comment]
Please reference issue in the commit msg

File: src/app/pages/home/components/account-actions.tsx [hunk 2]
```diff
@@ -42,13 +49,17 @@ export function AccountActions(props: FlexProps) {
...
         />
       )}
-
-      <ActionButton
-        data-testid={HomePageSelectors.SwapBtn}
-        icon={<SwapIcon />}
-        label="Swap"
-        onClick={() => navigate(RouteUrls.Swap)}
-      />
+      {whenNetwork(networkType)({
```
Comment (fbwoolf) [inline src/app/pages/home/components/account-actions.tsx]: Why would this only be based on the `networkType` for bitcoin?

**Review by fbwoolf — CHANGES_REQUESTED** [review]
I don't understand why this change is conditional on the bitcoin network?

File: src/app/pages/home/components/account-actions.tsx (hunk 2 above)
Comment (kyranjamie) [reply src/app/pages/home/components/account-actions.tsx]: Perhaps my request was confusing here. `whenNetwork` just forwards to mainnet or testnet, but technically stacks works on chain id. As swaps is a Stacks feature, using bitcoin network types might be confusing (but works as bitcoin testnet === stacks testnet). 

Alternatively, we have `whenStacksChainId();` too

Comment (fbwoolf) [reply src/app/pages/home/components/account-actions.tsx]: Yeah, a bit confusing in code if don't know both are always the same, will that always be the case with network refactoring?

Comment (edgarkhanzadian) [reply src/app/pages/home/components/account-actions.tsx]: @fbwoolf good catch! Used `whenStacksChainId` to check stacks testnet

**Review by fbwoolf — APPROVED** [review]
