### PR TITLE
fix: Ledger - cancel properly and don't allow user to close non cancellable sections

### LINKED ISSUE #5143: Ledger routing issue when rejecting
When rejecting an action, and pressing the `×` button, the user is navigated to the homepage, rather than to the beginning of the signing flow.

This bug is likely caused by the `/*` routing used, breaking the `navigate('..')` action.

https://github.com/leather-wallet/extension/assets/1618764/223e4a49-6706-431c-8578-e8a56b4d5462

### PR DESCRIPTION
**Pull request by pete-watters**
> Try out Leather build 910a39d — [Extension build](https://github.com/leather-wallet/extension/actions/runs/9093404035), [Test report](https://leather-wallet.github.io/playwright-reports/fix/5143/ledger-routing), [Storybook](https://fix-5143-ledger-routing--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=fix/5143/ledger-routing)

This PR:
- fixes a bug with https://github.com/leather-wallet/extension/issues/5143
- builds on issue https://github.com/leather-wallet/extension/issues/4689
- re-works the Ledger dialogs to remove rather than disable a close action when users cannot close
- analyses when users should be able to close the dialog
- performs a refactor to extract `DialogHeader`-s to their own simpler implementation

## Summary by CodeRabbit

- **New Features**
  - Enhanced cancel functionality for ledger actions, allowing users to cancel actions more intuitively based on device connection status.

- **Improvements**
  - Updated header components for a more consistent user interface.
  - Improved logic for determining when actions can be canceled, providing a smoother user experience.
  
- **Bug Fixes**
  - Fixed issues related to the rendering of header components and action cancellation logic within various ledger-related flows.

- **Refactor**
  - Streamlined the logic for handling ledger actions, enhancing maintainability and readability of the codebase.

### CODE REVIEW

**Comment by pete-watters** [comment]
@coderabbitai review

File: src/app/ui/components/containers/headers/header.tsx [hunk 1]
```diff
@@ -8,11 +8,10 @@ import { ArrowLeftIcon, CloseIcon } from '@app/ui/icons';
 import { BigTitleHeader } from './components/big-title-header';
 import { HeaderActionButton } from './components/header-action-button';
 
-type HeaderVariants = 'page' | 'home' | 'onboarding' | 'dialog' | 'bigTitle' | 'fund';
+type HeaderVariants = 'page' | 'home' | 'onboarding' | 'bigTitle' | 'fund';
```
Comment (pete-watters) [inline src/app/ui/components/containers/headers/header.tsx:11]: I just made a new header for `Dialog` - `DialogHeader` to remove this extra variant here and  `isWaitingOnPerformedAction`

File: src/app/ui/components/containers/dialog/dialog.tsx [hunk 2]
```diff
@@ -9,12 +9,12 @@ import { pxStringToNumber } from '@shared/utils/px-string-to-number';
...
 export interface DialogProps {
   isShowing: boolean;
-  onClose(): void;
+  onClose?(): void;
 }
 interface RadixDialogProps extends DialogProps {
   children: ReactNode;
   footer?: ReactNode;
-  header: ReactElement<any, string | JSXElementConstructor<any>>;
+  header?: ReactElement<any, string | JSXElementConstructor<any>>;
```
Comment (pete-watters) [inline src/app/ui/components/containers/dialog/dialog.tsx:17]: I tried changing the type of this to `ReactNode` but I need these types as I am using `cloneElement` to clone the `header` passed to the `Dialog` and pass on the `onClose` action

File: src/app/pages/rpc-sign-bip322-message/rpc-sign-bip322-message.tsx [hunk 3]
```diff
@@ -29,13 +30,25 @@ function RpcSignBip322Message() {
...
-    isLoading,
+    isLoading: signBip322MessageIsLoading,
     onUserApproveBip322MessageSigningRequest,
     onUserRejectBip322MessageSigningRequest,
   } = useSignBip322Message();
 
+  const location = useLocation();
   const { chain } = useCurrentNetwork();
 
+  const [isLoading, setIsLoading] = useState(false);
```
Comment (pete-watters) [inline src/app/pages/rpc-sign-bip322-message/rpc-sign-bip322-message.tsx:41]: I added this code as if users:
- start signing this message
- hit `X` to cancel and go back
- when they go back to the correct place now `signBip322MessageIsLoading` stays stuck as loading so they cannot retry

File: src/app/features/ledger/hooks/use-ledger-navigate.ts [hunk 4]
```diff
@@ -141,15 +141,13 @@ export function useLedgerNavigate() {
       },
 
       cancelLedgerAction() {
-        // for send ordinal '..' brings you back to the `choose-fee` step but you lose context of the ordinal
-        const backLocation = location.pathname.match(RouteUrls.SendOrdinalInscription)
-          ? RouteUrls.Home
-          : '..';
+        // Use baseUrl to determine where to go on close
```
Comment (pete-watters) [inline src/app/features/ledger/hooks/use-ledger-navigate.ts:147]: This is the main fix for [5143](https://github.com/leather-wallet/extension/issues/5143). 

I tried making changes to our routing to remove `/*` and restructure things but had no luck and hit old bugs from the past. 

For Ledger, we have a base route that we then append dialog routes to. 

Here, when the user rejects we take the base url from location and send them back there. 


- So if they hit: ` /sign-bip322-message` 
- Then go to `/sign-bip322-message/connect-your-ledger`
- Then `/sign-bip322-message/awaiting-approval` 
- On close we now go back to `/sign-bip322-message`

File: src/app/features/ledger/flows/stacks-message-signing/ledger-stacks-sign-msg-container.tsx [hunk 5]
```diff
@@ -140,27 +140,20 @@ function LedgerSignStacksMsg({ account, unsignedMessage }: LedgerSignMsgProps) {
     }
   }
 
-  const allowUserToGoBack = get(location.state, 'goBack');
```
Comment (pete-watters) [inline src/app/features/ledger/flows/stacks-message-signing/ledger-stacks-sign-msg-container.tsx:143]: I removed this `allowUserToGoBack` as I can't find where `'goBack'` is set in the state and I don't think it's doing anything

File: src/app/features/ledger/utils/stacks-ledger-utils.ts [hunk 6]
```diff
@@ -88,8 +88,9 @@ export function signStacksTransactionWithSignature(transaction: string, signatur
 export function useActionCancellableByUser() {
   const { pathname } = useLocation();
   return (
-    pathname.includes(RouteUrls.DeviceBusy) ||
+    pathname.includes(RouteUrls.ConnectLedger) ||
```
Comment (pete-watters) [inline src/app/features/ledger/utils/stacks-ledger-utils.ts]: I made a change here to allow users to close the dialog if they are on:
- `ConnectLedger` 
- `ConnectLedgerError` 

I stopped allowing close if they are on the `DeviceBusy` route as this is when we are loading their keys so I don't think they should be able to close it

File: src/app/features/ledger/hooks/use-ledger-navigate.ts [hunk 7]
```diff
@@ -141,15 +141,13 @@ export function useLedgerNavigate() {
...
+        const baseUrl = `/${location.pathname.split('/')[1]}`;
 
-        return navigate(backLocation, {
+        return navigate(baseUrl, {
```
Comment (pete-watters) [inline src/app/features/ledger/hooks/use-ledger-navigate.ts:150]: @kyranjamie @edgarkhanzadian : As part of my work here I dug into trying to get specific actions to also cancel on the `Ledger` device but had no luck. Did either of you try that before? 

I see that we do close transport successfully when we have a successful transaction but I couldn't get it to work when the user has a cancelled transaction for example. 

During testing this, often I:
- initiated an action from Leather to Ledger
- cancelled the action on Leather
- observed my Ledger as locked but when I un-locked it was still awaiting my approval / rejection of the previous action

That meant that I was blocked from doing any other action until I unlocked my ledger and declined the previous action. 

I tried to use the `generic-ledger-utils` - `quitAppOnDevice` and also wrote my own similar code to try and exit out of these transactions but I couldn't get it working. 

It was failing with:
```
Failed to execute 'close' on 'USBDevice': An operation that changes interface state is in progress.
```

If I am interacting with Gamma for example, and start a JWT auth then close the Leather popup, the request stays open on my Ledger. 

I'm just curious if we have tried fixing this before as it would be a nice addition to exit the appropriate APP on Ledger if we are no longer performing an action.

**Comment by pete-watters** [comment]
@kyranjamie : Opening this as a DRAFT as I made some more changes I am not sure you will agree are improvements.  I can pick out the [change](https://github.com/leather-wallet/extension/pull/5353#discussion_r1594993336) to fix this specific bug as needed. I was using this as an exercise to help me get up to speed with our Ledger code. 

When working on changing the dialogs/containers, we agreed to remove the text that was saying [`Ledger device in use`](https://github.com/leather-wallet/extension/issues/4689) but kept a disabled `X`. With my dialog changes, users could still click outside of the dialog and have it closed which is not good. 

I have made changes so that when we are awaiting specific actions, the Dialog is not closable and we don't show a disabled `X`. This will stop the dialog from being able to be closed while certain things are happening:


https://github.com/leather-wallet/extension/assets/2938440/6b9977f7-b31e-4700-8404-cd563e828ed4

It's not perfect though as users can still close from this interim screen before accounts are loaded:
Screenshot 2024-05-09 at 09 52 21

If they do that, it continues to work but the UI flashes until the accounts are loaded trying to show `please-wait` from the `get-started` route

File: src/app/features/ledger/flows/stacks-tx-signing/ledger-sign-stacks-tx-container.tsx [hunk 8]
```diff
@@ -148,11 +150,9 @@ function LedgerSignStacksTxContainer() {
     hasUserSkippedBuggyAppWarning,
   };
 
+  const canClose = !awaitingDeviceConnection && canUserCancelAction;
```
Comment (kyranjamie) [inline src/app/features/ledger/flows/stacks-tx-signing/ledger-sign-stacks-tx-container.tsx]: Any way we can avoid the repetition of this expression?

File: src/app/features/ledger/hooks/use-ledger-navigate.ts (hunk 7 above)
Comment (kyranjamie) [reply src/app/features/ledger/hooks/use-ledger-navigate.ts:150]: > trying to get specific actions to also cancel on the Ledger device but had no luck

Afaik, to cancel an operation the best you can do is just close the USB connection with `transport.close()`. If an action is pending on the device, I don't think there's anything you can do (unless closing the connection manually cancels it? though not sure)

**Review by kyranjamie — COMMENTED** [review]
Thanks Pete. Will QA later, I've lost my USB-C cable

File: src/app/features/ledger/flows/stacks-tx-signing/ledger-sign-stacks-tx-container.tsx (hunk 8 above)
Comment (pete-watters) [reply src/app/features/ledger/flows/stacks-tx-signing/ledger-sign-stacks-tx-container.tsx]: Sure, I will refactor it 👍

**Comment by pete-watters** [comment]
> Thanks Pete. Will QA later, I've lost my USB-C cable

Thanks, no rush, just wanted to share WIP so far

File: src/app/features/ledger/hooks/use-ledger-navigate.ts (hunk 7 above)
Comment (pete-watters) [reply src/app/features/ledger/hooks/use-ledger-navigate.ts:150]: If you try and close the connection it errors with `Failed to execute 'close' on 'USBDevice': ..`

Thanks though, I was just looking to get some more knowledge on it

File: src/app/features/ledger/utils/generic-ledger-utils.ts [hunk 9]
```diff
@@ -120,3 +122,19 @@ export function checkLockedDeviceError(e: Error) {
     e?.message === LedgerConnectionErrors.DeviceLocked
   );
 }
+
```
Comment (pete-watters) [inline src/app/features/ledger/utils/generic-ledger-utils.ts:125]: I moved this logic to `generic` as it's for both Stacks and BTC. 

I noticed that we often return `awaitingDeviceConnection` from the ledger hooks and then we need to feed it into my new hook `useCancelLedgerAction`. 

For example`useLedgerSignTx` returns `awaitingDeviceConnection` which gets passed into `useCancelLedgerAction`. 


I experimented with instead pushing that logic into the hooks so that they return `canCancelLedgerAction` instead of `awaitingDeviceConnection` but going that route and I will need to also update `BaseLedgerOperationContext` which could be going a bit too far:
```
export interface BaseLedgerOperationContext {
  latestDeviceResponse: LatestDeviceResponse;
  awaitingDeviceConnection: boolean;
}
```

File: src/app/features/ledger/flows/stacks-tx-signing/ledger-sign-stacks-tx-container.tsx (hunk 8 above)
Comment (pete-watters) [reply src/app/features/ledger/flows/stacks-tx-signing/ledger-sign-stacks-tx-container.tsx]: @kyranjamie: I did a refactor to improve this [here](https://github.com/leather-wallet/extension/pull/5353/commits/01dbb335f608c41467c26f1e46efc6813d146025). 

I added some more notes [here](https://github.com/leather-wallet/extension/pull/5353/commits/01dbb335f608c41467c26f1e46efc6813d146025#r1599656683).

I'm going to do some more testing but let me know if you think the code looks OK or if I should keep going with the refactor

File: src/app/features/ledger/utils/generic-ledger-utils.ts [hunk 10]
```diff
@@ -120,3 +122,19 @@ export function checkLockedDeviceError(e: Error) {
...
+function useActionCancellableByUser() {
+  const { pathname } = useLocation();
+  return (
+    pathname.includes(RouteUrls.ConnectLedger) ||
+    pathname.includes(RouteUrls.ConnectLedgerSuccess) ||
+    pathname.includes(RouteUrls.ConnectLedgerError) ||
+    pathname.includes(RouteUrls.AwaitingDeviceUserAction)
+  );
+}
```
[the remark this answers is not in the document]
Comment (pete-watters) [reply src/app/features/ledger/utils/generic-ledger-utils.ts]: Thanks Bunny. I added a return type and changed the name. 

No need for a lengthy comment to clutter the code

File: src/app/features/ledger/utils/generic-ledger-utils.ts [hunk 11]
```diff
@@ -120,3 +122,19 @@
...
+
+export function useCancelLedgerAction(awaitingDeviceConnection: boolean) {
+  const canUserCancelAction = useActionCancellableByUser();
+
+  return !awaitingDeviceConnection && canUserCancelAction;
+}
```
[the remark this answers is not in the document]
Comment (pete-watters) [reply src/app/features/ledger/utils/generic-ledger-utils.ts]: Code should document itself. This comment is the same amount of lines as the actual function

[the remark this answers is not in the document]
Comment (pete-watters) [reply src/app/features/ledger/utils/generic-ledger-utils.ts]: This function needs to be a React hook as it needs to call another hook and hence it needs to be named `useCanCancelLedgerAction`

File: src/app/features/ledger/flows/request-bitcoin-keys/ledger-request-bitcoin-keys.tsx [hunk 12]
```diff
@@ -45,11 +48,13 @@ function LedgerRequestBitcoinKeys() {
           onRequestKey(index) {
             if (index <= 4) {
               ledgerNavigate.toDeviceBusyStep(
-                `Requesting Bitcoin Native Segwit address (${index + 1}…5)`
+                `Requesting Bitcoin Native Segwit address (${index + 1}…${defaultNumberOfKeysToPullFromLedgerDevice})`
```
Comment (pete-watters) [inline src/app/features/ledger/flows/request-bitcoin-keys/ledger-request-bitcoin-keys.tsx:52]: @kyranjamie : Something looks funny here. When I test this:

- We show `Requesting Bitcoin Native Segwit address` `X-10` but we only load 5 
- Then we show `Requesting Bitcoin Taproot address` `X-10` and again go up to just 5
- Finally we show `Requesting Bitcoin Taproot address` `X-10` and count from 1 - 10

I guess there is some UI bug here and that we should be loading 10 of each address type? It seems like we incorrectly loop twice for the native segwit addresses. 

I can investigate it 




https://github.com/leather-wallet/extension/assets/2938440/b00f2d07-971c-4904-a55f-5844a04895e4

Comment (pete-watters) [reply src/app/features/ledger/flows/request-bitcoin-keys/ledger-request-bitcoin-keys.tsx:52]: I figured this out and fixed it [here](https://github.com/leather-wallet/extension/pull/5353/commits/910a39d88f3ced20296203ec6709cc1e8eecc47e)

**Review by kyranjamie — APPROVED** [review]

**Review by alter-eggo — APPROVED** [review]

**Review by fbwoolf — APPROVED** [review]
