### PR TITLE
fix: bitcoin bugs on testnet

### LINKED ISSUE #3148: Error sending all tBTC
I attempted to "Send all" of the testnet bitcoin back to the faucet it came from, mohjSavDdQYHRYXcS3uS6ttaHP8amyvX78. When I pressed "Preview", nothing happens, but in the log I see an error:

```
browser.js:201 {time: 1676478247479, level: 50, msg: 'Error signing bitcoin transaction'}
LOG @ browser.js:201
error @ logger.ts:50
(anonymous) @ use-generate-bitcoin-raw-tx.ts:78
previewTransaction @ btc-crypto-currency-send-form.tsx:98
await in previewTransaction (async)
onSubmit @ btc-crypto-currency-send-form.tsx:112
(anonymous) @ formik.esm.js:942
(anonymous) @ formik.esm.js:1256
(anonymous) @ formik.esm.js:858
Promise.then (async)
(anonymous) @ formik.esm.js:834
(anonymous) @ formik.esm.js:1256
(anonymous) @ formik.esm.js:922
(anonymous) @ formik.esm.js:1256
onClick @ index.esm.js:200
Rb @ react-dom.production.min.js:52
Xb @ react-dom.production.min.js:52
Yb @ react-dom.production.min.js:53
Ze @ react-dom.production.min.js:100
se @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Jb @ react-dom.production.min.js:292
Nb @ react-dom.production.min.js:50
jd @ react-dom.production.min.js:105
yc @ react-dom.production.min.js:75
hd @ react-dom.production.min.js:74
exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Hb @ react-dom.production.min.js:292
gd @ react-dom.production.min.js:73
sentryWrapped @ helpers.js:90
browser.js:201 {time: 1676478247480, level: 50, msg: 'Attempted to generate raw tx, but no tx exists'}level: 50msg: "Attempted to generate raw tx, but no tx exists"time: 1676478247480[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
LOG @ browser.js:201
error @ logger.ts:50
previewTransaction @ btc-crypto-currency-send-form.tsx:99
await in previewTransaction (async)
onSubmit @ btc-crypto-currency-send-form.tsx:112
(anonymous) @ formik.esm.js:942
(anonymous) @ formik.esm.js:1256
(anonymous) @ formik.esm.js:858
Promise.then (async)
(anonymous) @ formik.esm.js:834
(anonymous) @ formik.esm.js:1256
(anonymous) @ formik.esm.js:922
(anonymous) @ formik.esm.js:1256
onClick @ index.esm.js:200
Rb @ react-dom.production.min.js:52
Xb @ react-dom.production.min.js:52
Yb @ react-dom.production.min.js:53
Ze @ react-dom.production.min.js:100
se @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Jb @ react-dom.production.min.js:292
Nb @ react-dom.production.min.js:50
jd @ react-dom.production.min.js:105
yc @ react-dom.production.min.js:75
hd @ react-dom.production.min.js:74
exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Hb @ react-dom.production.min.js:292
gd @ react-dom.production.min.js:73
sentryWrapped @ helpers.js:90
browser.js:201 {time: 1676478284264, level: 30, msg: 'Analytics page view: /send'}
browser.js:201 {time: 1676478286004, level: 30, msg: 'Analytics page view: /'}
browser.js:201 {time: 1676478289072, level: 30, msg: 'Analytics page view: /send'}
browser.js:201 {time: 1676478290037, level: 30, msg: 'Analytics page view: /send/btc'}
browser.js:201 {time: 1676478293565, level: 30, msg: 'Analytics event: select_maximum_amount_for_send'}
browser.js:201 {time: 1676478295427, level: 50, msg: 'Error signing bitcoin transaction'}
LOG @ browser.js:201
error @ logger.ts:50
(anonymous) @ use-generate-bitcoin-raw-tx.ts:78
previewTransaction @ btc-crypto-currency-send-form.tsx:98
await in previewTransaction (async)
onSubmit @ btc-crypto-currency-send-form.tsx:112
(anonymous) @ formik.esm.js:942
(anonymous) @ formik.esm.js:1256
(anonymous) @ formik.esm.js:858
Promise.then (async)
(anonymous) @ formik.esm.js:834
(anonymous) @ formik.esm.js:1256
(anonymous) @ formik.esm.js:922
(anonymous) @ formik.esm.js:1256
onClick @ index.esm.js:200
Rb @ react-dom.production.min.js:52
Xb @ react-dom.production.min.js:52
Yb @ react-dom.production.min.js:53
Ze @ react-dom.production.min.js:100
se @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Jb @ react-dom.production.min.js:292
Nb @ react-dom.production.min.js:50
jd @ react-dom.production.min.js:105
yc @ react-dom.production.min.js:75
hd @ react-dom.production.min.js:74
exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Hb @ react-dom.production.min.js:292
gd @ react-dom.production.min.js:73
sentryWrapped @ helpers.js:90
browser.js:201 {time: 1676478295428, level: 50, msg: 'Attempted to generate raw tx, but no tx exists'}
LOG @ browser.js:201
error @ logger.ts:50
previewTransaction @ btc-crypto-currency-send-form.tsx:99
await in previewTransaction (async)
onSubmit @ btc-crypto-currency-send-form.tsx:112
(anonymous) @ formik.esm.js:942
(anonymous) @ formik.esm.js:1256
(anonymous) @ formik.esm.js:858
Promise.then (async)
(anonymous) @ formik.esm.js:834
(anonymous) @ formik.esm.js:1256
(anonymous) @ formik.esm.js:922
(anonymous) @ formik.esm.js:1256
onClick @ index.esm.js:200
Rb @ react-dom.production.min.js:52
Xb @ react-dom.production.min.js:52
Yb @ react-dom.production.min.js:53
Ze @ react-dom.production.min.js:100
se @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Jb @ react-dom.production.min.js:292
Nb @ react-dom.production.min.js:50
jd @ react-dom.production.min.js:105
yc @ react-dom.production.min.js:75
hd @ react-dom.production.min.js:74
exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Hb @ react-dom.production.min.js:292
gd @ react-dom.production.min.js:73
sentryWrapped @ helpers.js:90
browser.js:201 {time: 1676478467942, level: 30, msg: 'Analytics page view: /send/btc/confirmation'}
trycatch.js:165          GET https://api1.binance.com/api/v3/ticker/price?symbol=BTCUSDT 451
(anonymous) @ trycatch.js:165
(anonymous) @ instrument.js:257
(anonymous) @ browser-ponyfill.js:518
fetch @ browser-ponyfill.js:455
fetchBinanceMarketData @ binance-market-data.query.ts:10
queryFn @ binance-market-data.query.ts:21
fetchFn @ query.mjs:252
run @ retryer.mjs:97
createRetryer @ retryer.mjs:145
fetch @ query.mjs:306
executeFetch @ queryObserver.mjs:168
onSubscribe @ queryObserver.mjs:28
subscribe @ subscribable.mjs:9
(anonymous) @ useBaseQuery.mjs:37
(anonymous) @ use-sync-external-store-shim.production.min.js:10
fk @ react-dom.production.min.js:262
exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Oj @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
V @ scheduler.production.min.js:16
F.port1.onmessage @ scheduler.production.min.js:12
browser.js:201 {time: 1676478468051, level: 50, msg: 'Cannot load binance data'}
LOG @ browser.js:201
error @ logger.ts:50
logAndThrow @ utils.ts:320
fetchBinanceMarketData @ binance-market-data.query.ts:11
await in fetchBinanceMarketData (async)
queryFn @ binance-market-data.query.ts:21
fetchFn @ query.mjs:252
run @ retryer.mjs:97
createRetryer @ retryer.mjs:145
fetch @ query.mjs:306
executeFetch @ queryObserver.mjs:168
onSubscribe @ queryObserver.mjs:28
subscribe @ subscribable.mjs:9
(anonymous) @ useBaseQuery.mjs:37
(anonymous) @ use-sync-external-store-shim.production.min.js:10
fk @ react-dom.production.min.js:262
exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Oj @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
V @ scheduler.production.min.js:16
F.port1.onmessage @ scheduler.production.min.js:12
trycatch.js:165          GET https://api1.binance.com/api/v3/ticker/price?symbol=BTCUSDT 451
(anonymous) @ trycatch.js:165
(anonymous) @ instrument.js:257
(anonymous) @ browser-ponyfill.js:518
fetch @ browser-ponyfill.js:455
fetchBinanceMarketData @ binance-market-data.query.ts:10
queryFn @ binance-market-data.query.ts:21
fetchFn @ query.mjs:252
run @ retryer.mjs:97
(anonymous) @ retryer.mjs:137
Promise.then (async)
(anonymous) @ retryer.mjs:133
Promise.catch (async)
run @ retryer.mjs:102
createRetryer @ retryer.mjs:145
fetch @ query.mjs:306
executeFetch @ queryObserver.mjs:168
onSubscribe @ queryObserver.mjs:28
subscribe @ subscribable.mjs:9
(anonymous) @ useBaseQuery.mjs:37
(anonymous) @ use-sync-external-store-shim.production.min.js:10
fk @ react-dom.production.min.js:262
exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Oj @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
V @ scheduler.production.min.js:16
F.port1.onmessage @ scheduler.production.min.js:12
browser.js:201 {time: 1676478469072, level: 50, msg: 'Cannot load binance data'}
LOG @ browser.js:201
error @ logger.ts:50
logAndThrow @ utils.ts:320
fetchBinanceMarketData @ binance-market-data.query.ts:11
await in fetchBinanceMarketData (async)
queryFn @ binance-market-data.query.ts:21
fetchFn @ query.mjs:252
run @ retryer.mjs:97
(anonymous) @ retryer.mjs:137
Promise.then (async)
(anonymous) @ retryer.mjs:133
Promise.catch (async)
run @ retryer.mjs:102
createRetryer @ retryer.mjs:145
fetch @ query.mjs:306
executeFetch @ queryObserver.mjs:168
onSubscribe @ queryObserver.mjs:28
subscribe @ subscribable.mjs:9
(anonymous) @ useBaseQuery.mjs:37
(anonymous) @ use-sync-external-store-shim.production.min.js:10
fk @ react-dom.production.min.js:262
exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Oj @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
V @ scheduler.production.min.js:16
F.port1.onmessage @ scheduler.production.min.js:12
trycatch.js:165          GET https://api1.binance.com/api/v3/ticker/price?symbol=BTCUSDT 451
(anonymous) @ trycatch.js:165
(anonymous) @ instrument.js:257
(anonymous) @ browser-ponyfill.js:518
fetch @ browser-ponyfill.js:455
fetchBinanceMarketData @ binance-market-data.query.ts:10
queryFn @ binance-market-data.query.ts:21
fetchFn @ query.mjs:252
run @ retryer.mjs:97
(anonymous) @ retryer.mjs:137
Promise.then (async)
(anonymous) @ retryer.mjs:133
Promise.catch (async)
run @ retryer.mjs:102
(anonymous) @ retryer.mjs:137
Promise.then (async)
(anonymous) @ retryer.mjs:133
Promise.catch (async)
run @ retryer.mjs:102
createRetryer @ retryer.mjs:145
fetch @ query.mjs:306
executeFetch @ queryObserver.mjs:168
onSubscribe @ queryObserver.mjs:28
subscribe @ subscribable.mjs:9
(anonymous) @ useBaseQuery.mjs:37
(anonymous) @ use-sync-external-store-shim.production.min.js:10
fk @ react-dom.production.min.js:262
exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Oj @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
V @ scheduler.production.min.js:16
F.port1.onmessage @ scheduler.production.min.js:12
browser.js:201 {time: 1676478471095, level: 50, msg: 'Cannot load binance data'}
LOG @ browser.js:201
error @ logger.ts:50
logAndThrow @ utils.ts:320
fetchBinanceMarketData @ binance-market-data.query.ts:11
await in fetchBinanceMarketData (async)
queryFn @ binance-market-data.query.ts:21
fetchFn @ query.mjs:252
run @ retryer.mjs:97
(anonymous) @ retryer.mjs:137
Promise.then (async)
(anonymous) @ retryer.mjs:133
Promise.catch (async)
run @ retryer.mjs:102
(anonymous) @ retryer.mjs:137
Promise.then (async)
(anonymous) @ retryer.mjs:133
Promise.catch (async)
run @ retryer.mjs:102
createRetryer @ retryer.mjs:145
fetch @ query.mjs:306
executeFetch @ queryObserver.mjs:168
onSubscribe @ queryObserver.mjs:28
subscribe @ subscribable.mjs:9
(anonymous) @ useBaseQuery.mjs:37
(anonymous) @ use-sync-external-store-shim.production.min.js:10
fk @ react-dom.production.min.js:262
exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Oj @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
V @ scheduler.production.min.js:16
F.port1.onmessage @ scheduler.production.min.js:12
browser.js:201 {time: 1676478471406, level: 30, msg: 'Analytics page view: /send'}
browser.js:201 {time: 1676478489483, level: 30, msg: 'Analytics page view: /send/btc'}
browser.js:201 {time: 1676478499094, level: 30, msg: 'Analytics event: select_maximum_amount_for_send'}
```

### LINKED ISSUE #3152: Mainnet fund-wallet-button reveals (testnet) bitcoin address.
image

It shouldn't do that yet during testnet phase. Fara is fixing this.

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/4189918875).

This PR fixes a couple of bugs found while testing btc on testnet. I removed the send all button for now bc we aren't properly calculating it, and we aren't showing an insufficient balance warning. That appears to be the error I was running into as well. I believe @kyranjamie added the insufficient balance warning to bitcoin? If not, we need to make an issue for it.

Bitcoin mainnet address was shown from the Fund page when clicking on receive tile, so I routed that properly to the stx only modal for now.

I am also reverting a small change I made here to our env variable `BRANCH_NAME`. I want to fix it for dev builds properly and needs more testing.

### CODE REVIEW

**Comment by fbwoolf** [comment]
I also realized tonight that when I added copying the btc address to the account header, the address copied was actually the Stacks address. I cleaned up those components here to reuse one `AccountAddress` component ...used for the bns name as well.

**Comment by kyranjamie** [comment]
> I believe @kyranjamie added the insufficient balance warning to bitcoin? If not, we need to make an issue for it.

Nope, https://github.com/hirosystems/stacks-wallet-web/issues/3156

File: src/app/pages/send/send-crypto-asset-form/components/amount-field.tsx [hunk 1]
```diff
@@ -102,7 +102,7 @@ export function AmountField({ balance, bottomInputOverlay }: AmountFieldProps) {
           {meta.error}
         </ErrorLabel>
       )}
-      {bottomInputOverlay}
+      {bottomInputOverlay ?? <Box size="36px" />}
```
Comment (kyranjamie) [inline src/app/pages/send/send-crypto-asset-form/components/amount-field.tsx:105]: Don't understand this change?

**Review by kyranjamie — APPROVED** [review]
Thx @fbwoolf—merging to work with these changes

File: src/app/pages/send/send-crypto-asset-form/components/amount-field.tsx (hunk 1 above)
Comment (fbwoolf) [reply src/app/pages/send/send-crypto-asset-form/components/amount-field.tsx:105]: If it didn't have the `Send all` button then the space in the UI collapsed and didn't look correct.
