### PR TITLE
fix: replace by fee cache bug

### LINKED ISSUE #1975: Replace-by-fee tx on dev moves back into `Submitted`
I am seeing this behavior on dev so I wanted to create an issue for it. Hoping to confirm others are seeing it?

When I do a `replace-be-fee` the tx moves from the tx list back into the `Submitted` list and won't clear from local storage unless I do it manually.

cc @Eshwari007 

Screen Shot 2021-11-22 at 8 32 52 AM

### PR DESCRIPTION
**Pull request by kyranjamie**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/1494761658).

This issue's rather confused me, to be honest. It isn't clear how my refactor would've broken it, nor how it ever worked in the first place lol.

There's code to "clean up" the cache, called from the `<LocalTxIdListItem />` component. 

https://github.com/hirosystems/stacks-wallet-web/blob/99a619bdd471bdd8b4e94c1cd5011520c883ce0c/src/store/accounts/account-activity.ts#L93

But this works implicitly based on whether there's a duplicate id, which there isn't in the case of replace by fee, the id changes.

This PR adds the behaviour where, on successful replace by fee of a given tx, the previous txid is removed from the cache.

### CODE REVIEW

File: src/features/local-transaction-activity/local-tx-list.tsx [hunk 1]
```diff
@@ -9,11 +9,7 @@ import { Box, color, Stack, Text } from '@stacks/ui';
 const LocalTxListItem = ({ txid }: { txid: string }) => {
   const localTx = useCurrentAccountLocalStacksTransaction(txid);
   const cleanup = useCleanupLocalTxsCallback();
-  useEffect(() => {
-    return () => {
-      cleanup();
-    };
-  }, [cleanup]);
+  useEffect(() => () => cleanup(), [cleanup]);
```
Comment (beguene) [inline src/features/local-transaction-activity/local-tx-list.tsx:12]: This could be simplified further
```javascript
useEffect(() => cleanup, [cleanup]);
```

File: src/features/increase-fee-drawer/components/increase-fee-form.tsx [hunk 2]
```diff
@@ -61,9 +63,12 @@ export function IncreaseFeeForm(): JSX.Element | null {
       const feeRate = newFeeRate.toNumber();
       setFeeRate(feeRate);
       setFee(stxToMicroStx(values.txFee).toNumber());
-      await handleSubmit(values);
+      await replaceByFee(values);
+      if (tx?.tx_id) {
```
Comment (beguene) [inline src/features/increase-fee-drawer/components/increase-fee-form.tsx:67]: We could maybe add the check in removeLocallySubmittedTx.

File: src/store/accounts/account-activity.ts [hunk 3]
```diff
@@ -110,3 +111,20 @@ export const cleanupLocalTxs = atom(null, (get, set) => {
     set(anAtom, newLocalTxs);
   }
 });
+
+export const removeLocalSubmittedTxById = atom(null, (get, set, txIdToRemove: string) => {
```
Comment (beguene) [inline src/store/accounts/account-activity.ts:115]: Can't we just have a hook that return a function instead of an atom ?

Comment (kyranjamie) [reply src/store/accounts/account-activity.ts:115]: There is: https://github.com/hirosystems/stacks-wallet-web/blob/99a619bdd471bdd8b4e94c1cd5011520c883ce0c/src/store/accounts/account-activity.hooks.ts#L72-L74

File: src/features/increase-fee-drawer/components/increase-fee-form.tsx (hunk 2 above)
Comment (kyranjamie) [reply src/features/increase-fee-drawer/components/increase-fee-form.tsx:67]: Not sure I understand, `tx` is in the component's scope, and it wouldn't be a good idea to extend `removeLocallySubmittedTx`  to accept `string | undefined`?

File: src/features/local-transaction-activity/local-tx-list.tsx (hunk 1 above)
Comment (kyranjamie) [reply src/features/local-transaction-activity/local-tx-list.tsx:12]: Could do this here, and sometimes passing fn by ref is okay, but there are risks, too, when using map etc https://jakearchibald.com/2021/function-callback-risks/, there are readability tradeoffs as well

File: src/features/increase-fee-drawer/components/increase-fee-form.tsx (hunk 2 above)
Comment (beguene) [reply src/features/increase-fee-drawer/components/increase-fee-form.tsx:67]: That's fair,  keeping the argument purely 'string' makes sense

**Review by beguene — APPROVED** [review]

**Review by fbwoolf — APPROVED** [review]
