### PR TITLE
fix: tx req fee error

### LINKED ISSUE #4231: When STX fee exceeds wallet balance, confirm button does nothing when trying to confirm a contract call
I believe this may be a related issue: https://github.com/leather-wallet/extension/issues/4128 although I have not been able to confirm. 

Steps to reproduce
1. Go to app.alexlab.co (you can also use an other dapp
2. Go to swap and input any amount of tokens you have availble to some other token
3. Confirm on the dapp
4. See the Leather confirm modal appear
5. Set a STX fee that is higher than the wallet balance
6. See issue:

https://github.com/leather-wallet/extension/assets/33360391/8f7dac70-68ae-41bd-8f88-a0135a40a601

Note this is different for a normal STX transfer, then an error is thrown "insufficient funds" (but only for "STX to transfer"). I think we need an error to appear when the fee exceeds the balance too. And perhaps even better if we make it clear that together these two (amount to transfer + fee) exceed the balance?

image

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of Leather — [download extension builds](https://github.com/leather-wallet/extension/actions/runs/6646153230).

Now shows error if the fee is set higher than available STX... the fee form needed to wrap the error components so it was available to use. I'm not sure why `transaction.fee` was used originally, but our form handles the fee. And, the conversion here was wrong bc the amount is in microstacks.

Screen Shot 2023-10-25 at 3 36 46 PM

Screen Shot 2023-10-25 at 3 37 33 PM

### CODE REVIEW

File: src/app/features/stacks-transaction-request/stacks-transaction-signer.tsx [hunk 1]
```diff
@@ -111,6 +103,15 @@ export function StacksTransactionSigner({
       >
         {() => (
           <>
+            <PageTop />
```
Comment (pete-watters) [inline src/app/features/stacks-transaction-request/stacks-transaction-signer.tsx:106]: Maybe we can extract these components into another file so we can include that in `stacks-transaction-signer.tsx` and `transaction-request.tsx` instead of repeating these lines

**Review by pete-watters — APPROVED** [review]

**Review by kyranjamie — APPROVED** [review]

File: src/app/features/stacks-transaction-request/stacks-transaction-signer.tsx (hunk 1 above)
Comment (fbwoolf) [reply src/app/features/stacks-transaction-request/stacks-transaction-signer.tsx:106]: Yeah, we need to refactor our transaction flows for sure, agree lots of duplicate code. I created a code health issue for it here: https://github.com/leather-wallet/extension/issues/3594
