### PR TITLE
fix: error boundary

### LINKED ISSUE #2921: Fix error boundary to correctly handle and log errors
The app's error boundary isn't set up to properly handle errors, they are just re-thrown and no usefull message is shown to users.

handler declared here,
https://github.com/hirosystems/stacks-wallet-web/blob/8788e010b9504f1cfa5c8f2c619af19da240dbc8/src/app/features/errors/error-boundary.tsx#L154-L159
passed as arg here (TS accepts the different fn signature)
https://github.com/hirosystems/stacks-wallet-web/blob/8788e010b9504f1cfa5c8f2c619af19da240dbc8/src/app/features/errors/app-error-boundary.tsx#L52-L65
called here,
https://github.com/hirosystems/stacks-wallet-web/blob/8788e010b9504f1cfa5c8f2c619af19da240dbc8/src/app/features/errors/error-boundary.tsx#L94-L96

### LINKED ISSUE #3986: Add global app error screen
eg https://github.com/hirosystems/wallet/issues/3897

### PR DESCRIPTION
**Pull request by alter-eggo**
> Try out Leather build 91c981b — [Extension build](https://github.com/leather-wallet/extension/actions/runs/9256155358), [Test report](https://leather-wallet.github.io/playwright-reports/fix-error-boundary), [Storybook](https://fix-error-boundary--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=fix-error-boundary)

I seems current app's error boundary doesn't work. I decided not to try fix that legacy code, and just added new component for this. I believe it's ok for now, still way better than default error screen:

Screenshot 2024-02-28 at 23 45 58

## Summary by CodeRabbit

- **New Features**
  - Introduced a new `RouterErrorBoundary` for enhanced error handling in routes.
  - Revamped error display UI with new components and functionalities like error copying and reloading.

- **Improvements**
  - Updated error handling in the app to provide more detailed messages and enhanced user options.
  - Modified `CodeBlock` component in contract deploy details to include a new color prop.

- **Removals**
  - Removed `AppErrorBoundary` from the rendering hierarchy.
  - Eliminated unused `useErrorStackTraceState` function and `errorStackTraceState` constant to simplify state management.

- **Style**
  - Updated color property in the `theme` constant from `'#fff'` to `'unset'`.

These changes aim to improve error handling, enhance the user interface, and streamline the codebase.

### CODE REVIEW

**Comment by alter-eggo** [comment]
added stack trace 
Screenshot 2024-02-29 at 01 16 45

**Review by fbwoolf — APPROVED** [review]
@pete-watters just checking if you touched this at all with your work? Is there an open issue to revisit this? I'll check.

**Comment by fbwoolf** [comment]
There is this issue, outdated and can be closed here? https://github.com/leather-wallet/extension/issues/2921

**Comment by pete-watters** [comment]
Thanks for fixing this @alter-eggo . Can you please check if we have an issue before doing stuff like this? We shouldn't have PRs with no issue. 

There is a task for this, with a design in the `Establish UI Library` project so I assigned it to you now. Please check that this implementation matches the design.

File: src/app/features/errors/app-error-boundary.tsx [hunk 1]
```diff
@@ -7,9 +11,73 @@ import { Header } from '@app/components/header';
...
 import { Title } from '@app/ui/components/typography/title';
 
+export function RouterErrorBoundary() {
+  const error = useRouteError() as Error;
+
+  const title = 'Something went wrong';
+  const body = 'An error occurred in the app.';
+  const errorPayload = error.message;
+
+  return (
```
Comment (pete-watters) [inline src/app/features/errors/app-error-boundary.tsx:18]: Can you please refactor this so it's a dumb component, receiving some props it needs and located in the `ui/components` folder? 

We should also add a storybook story for it so we can see how it looks

**Review by pete-watters — CHANGES_REQUESTED** [review]
Please check https://github.com/leather-wallet/extension/issues/3986 to make sure we solve this fully

**Review by pete-watters — COMMENTED** [review]
I'm changing this from Request changes as we checked with design and it's pending their response.

**Review by pete-watters — APPROVED** [review]

File: src/app/features/errors/app-error-boundary.tsx [hunk 2]
```diff
@@ -1,58 +1,103 @@
...
-    </Stack>
-  );
-}
+export function RouterErrorBoundary() {
+  const error = useRouteError() as Error;
+  const errorObj = JSON.parse(JSON.stringify(error, Object.getOwnPropertyNames(error)));
+
+  const body =
+    'Your funds remain securely in your wallet. If you are stuck with this error, you can safely share the logs below with our';
+  const title = 'Something went wrong';
```
Comment (edgarkhanzadian) [inline src/app/features/errors/app-error-boundary.tsx]: Could be a const outside of the component

File: src/app/features/errors/app-error-boundary.tsx [hunk 3]
```diff
@@ -1,58 +1,103 @@
...
+      </styled.span>
+
+      {errorPayload && (
+        <CodeBlock
+          bg="ink.background-secondary"
+          borderRadius="sm"
+          my="space.05"
+          mx="space.05"
+          p="space.04"
+          prism={Prism as any}
```
Comment (edgarkhanzadian) [inline src/app/features/errors/app-error-boundary.tsx]: Can we fix the `any` here?

**Review by edgarkhanzadian — APPROVED** [review]
Great work! Left some optional comments here and there

File: src/app/features/errors/app-error-boundary.tsx [hunk 4]
```diff
@@ -1,58 +1,103 @@
...
-        >
-          Report issue on GitHub
-        </styled.button>
-      </Stack>
-    </Stack>
-  );
-}
+export function RouterErrorBoundary() {
+  const error = useRouteError() as Error;
+  const errorObj = JSON.parse(JSON.stringify(error, Object.getOwnPropertyNames(error)));
```
Comment (kyranjamie) [inline src/app/features/errors/app-error-boundary.tsx]: This looks sketchy. Let's do some runtime checking. 

Something like?
`if (!isError) return children;` or nav home?

And why the stringify/parse? I have no idea why this is happening, and nor might the next person reading this code.

File: src/app/features/errors/app-error-boundary.tsx (hunk 2 above)
Comment (kyranjamie) [reply src/app/features/errors/app-error-boundary.tsx]: +1, or just put in the JSX? It's weird that the sentence fini....

Also unsafe read of object here that has been cast to Error. How can we do this safely?

```
function getErrorText(error: unknown) {
  if (!isError(error)) return '';
  if ('stack' in error) return error.stack;
}
```

or something like this?

File: src/app/features/errors/app-error-boundary.tsx [hunk 5]
```diff
@@ -1,58 +1,103 @@
...
+
+  const body =
+    'Your funds remain securely in your wallet. If you are stuck with this error, you can safely share the logs below with our';
```
Comment (kyranjamie) [inline src/app/features/errors/app-error-boundary.tsx]: Suggest something more like

`Leather has crashed. If this problem persists, contact our support team`

File: src/app/features/errors/app-error-boundary.tsx (hunk 4 above)
Comment (alter-eggo) [reply src/app/features/errors/app-error-boundary.tsx]: hm, I added this a while ago, not recall now why. removed

Comment (alter-eggo) [reply src/app/features/errors/app-error-boundary.tsx]: not sure if there could be `!isError` as it's error boundary. but even if it could -> better to show at least "Unknown error" msg. 
if we nav home and error happened on home screen - there will be just blank screen
