### PR TITLE
fix: SIP010 token transfer not going through

### LINKED ISSUE #1915: SIP010 token transfer gets stuck and doesnt post
- Click send
- Select a sip010 token
- Set an amount
- Provide a recipient
- Provide a memo (optional)
- Click preview
- The screen will simply disappear and the transaction will not post

### PR DESCRIPTION
**Pull request by beguene**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/1448056740).

Fixed by handling the case the argument is a buffer and not a string

closes #1915
FYI this issue was introduced by https://github.com/hirosystems/stacks-wallet-web/pull/1853/commits/31ecb2b67d0cef66924d8b4402f3f6eeb4869e79

cc/ @kyranjamie @fbwoolf

### CODE REVIEW

File: src/common/utils.ts [hunk 1]
```diff
@@ -169,7 +169,7 @@ function isHex(hex: string): boolean {
 }
 
 function cleanHex(hexWithMaybePrefix: string): string {
-  return hexWithMaybePrefix.startsWith('0x')
+  return typeof hexWithMaybePrefix === 'string' && hexWithMaybePrefix.startsWith('0x')
```
Comment (kyranjamie) [inline src/common/utils.ts]: This shouldn't ever be necessary with TypeScript; we're already declaring the type. 

The problem lies with why a buffer is being passed to `cleanHex`, and not causing a compile-time type error in the first place.

**Comment by kyranjamie** [comment]
I've pushed a commit which moves this handling to where we generate the fn. This is a high priority, so let's merge asap.

We need to follow up with fixing these types asap

**Review by kyranjamie — APPROVED** [review]

**Comment by kyranjamie** [comment]
How the hell does this change break the tests 🤦🏼 .  Opened up issue to unskip these two tests: https://github.com/hirosystems/stacks-wallet-web/issues/1920
