### PR TITLE
fix: brc-20 pending transactions

### LINKED ISSUE #4990: Brc-20 endless pending transactions
Ordinals bot returns unprocessed error if brc-20 order not found
307778579-89d3452a-405f-4fcb-aef2-21dcbc19efbf
307778587-5ed8a941-cd4f-411d-8928-f162a145adaf

### PR DESCRIPTION
**Pull request by alter-eggo**
> Try out this version of Leather — [Extension build](https://github.com/leather-wallet/extension/actions/runs/8132729599), [Test report](https://leather-wallet.github.io/playwright-reports/fix/brc-20-pending)

I have endless brc-20 transactions in my wallet, bc of unprocessed error response from ordinals bot, wonder how we want to fix it, just remove tx from state here?
Screenshot 2024-02-26 at 15 44 44
Screenshot 2024-02-26 at 15 58 56

### CODE REVIEW

**Review by kyranjamie — APPROVED** [review]
Another approach here might be to reject the promise if the `status !== 'success'` so it never makes it to the `onSuccess` if it isn't successful.

But this LGTM, should it be in review status?

**Comment by alter-eggo** [comment]
@kyranjamie wonder here if we need to remove order from redux state if it is not found?

**Comment by kyranjamie** [comment]
> @kyranjamie wonder here if we need to remove order from redux state if it is not found?

Yes, I think so. I recall having concerns about stale data when we built it, but we never got around to addressing. If API says it isn't there, we should indeed remove.

File: src/app/query/bitcoin/ordinals/brc20/use-check-order-status.ts [hunk 1]
```diff
@@ -22,6 +23,13 @@ export function useCheckOrderStatuses(ids: string[]) {
       queryKey: ['check-order-status', id],
       queryFn: async () => ordinalsbotClient.orderStatus(id),
       async onSuccess({ data }: Awaited<ReturnType<typeof ordinalsbotClient.orderStatus>>) {
+        if (data.status === 'error') {
+          if (data.error.includes('no such order')) {
+            dispatch(inscriptionSent({ inscriptionId: id }));
```
Comment (kyranjamie) [inline src/app/query/bitcoin/ordinals/brc20/use-check-order-status.ts]: `dispatch(orderNotFound())`

?

Comment (alter-eggo) [reply src/app/query/bitcoin/ordinals/brc20/use-check-order-status.ts]: fixed
