### PR TITLE
fix: collectible hover, closes #4971

### LINKED ISSUE #4971: Fix collectible hover button
When hovering the callout button that appears on top of the collectible preview, the button becomes transparent. Instead we'd like the button to stay opaque while applying the hover effect as an overlay.

Image

Solution suggestion: At this point this is a one-off case for collectibles. Hence we suggest to solve this locally vs. systematically. For example, we could simply wrap the button in a container with bg background-primary, with the button staying transparent and using the transparent hover effect via the corresponding component background hover token (as is applied now).

_PS: New icon is assuming new icon library is in place_

### PR DESCRIPTION
**Pull request by fbwoolf**
This fixes the collectible hover `IconButton` disappearing issue.

Screenshot 2024-07-04 at 8 42 36 AM

Screenshot 2024-07-04 at 8 42 41 AM

## Summary by CodeRabbit

- **New Features**
	- Updated the `CollectibleHover` component to use `ExternalLinkIcon` instead of `ArrowUpIcon` for better visual representation.
	- Improved the structure and styling of the `IconButton` component within the `CollectibleHover` component.

### CODE REVIEW

**Comment by fbwoolf** [comment]
Fix was just to add a bg color to a div wrapping the `IconButton` and applying the hover bg color to the icon button. The icon itself passed to the `IconButton` doesn't need to change color (from what I see in Figma).

**Review by kyranjamie — APPROVED** [review]

File: src/app/features/collectibles/components/collectible-hover.tsx [hunk 1]
```diff
@@ -38,34 +38,19 @@ export function CollectibleHover({
...
-            onClickCallToAction();
-          }}
-          position="absolute"
-          right="12px"
-          top="12px"
-          type="button"
-          width="30px"
-          zIndex={999}
-        />
+        <Box bg="ink.background-primary" position="absolute" right="12px" top="12px" zIndex={999}>
```
Comment (pete-watters) [inline src/app/features/collectibles/components/collectible-hover.tsx:41]: Thanks @fbwoolf :clap: 

I tested this and its working perfectly. I'm not sure how I didn't get this myself, maybe as I was using `div` as a wrapper and not `Box`?

Anyway, glad you could solve it. Thanks!

**Review by pete-watters — APPROVED** [review]
🚀
