### PR TITLE
fix: issue with broken summary page, closes #6152

### LINKED ISSUE #6152: `txid` / success not returned for successfully broadcast transactions.
**Reproduce:**

1. Use https://connect-hirosystems.vercel.app/iframe?id=connect-connect--default&viewMode=story
2. Use SIP-030 stx_callContract with
  - Contract `SP2VCQJGH7PHP2DJK7Z0V48AGBHQAW3R3ZW1QF4N.borrow-helper-v2-0-0`
  - Function `supply`
  - Args `'SP2VCQJGH7PHP2DJK7Z0V48AGBHQAW3R3ZW1QF4N.zsbtc-v2-0, 'SP2VCQJGH7PHP2DJK7Z0V48AGBHQAW3R3ZW1QF4N.pool-0-reserve-v2-0, 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token, u1214861, 'SP39DC776TVRWSPSXNXCCM80APY6EBV4J1Y3HAZYJ, none`
  - Submit
3. Response is an error, but looking into Leather the tx was broadcast

### PR DESCRIPTION
**Pull request by kyranjamie**
> Try out Leather build 1c84a5a — [Extension build](https://github.com/leather-io/extension/actions/runs/13607007923), [Test report](https://leather-io.github.io/playwright-reports/fix/broken-summary-page), [Storybook](https://fix/broken-summary-page--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=fix/broken-summary-page)

This is very much a workaround, but deals with the broadcast feature that couples way too much unrelated behaviours.

### CODE REVIEW

**Review by fbwoolf — APPROVED** [review]

**Comment by fbwoolf** [comment]
You want me to make an issue to refactor `useStacksBroadcastTransaction`? It is pretty awful atm.

File: src/app/common/rpc/use-rpc-sip30-broadcast-transaction.ts [hunk 1]
```diff
@@ -50,7 +50,10 @@ export function useRpcSip30BroadcastTransaction(method: RpcMethodNames) {
   const { origin, requestId, tabId } = useRpcRequestParams();
   const txPayload = useLegacyTxPayloadFromRpcRequest();
   const stacksTransaction = useUnsignedStacksTransaction(txPayload);
-  const { stacksBroadcastTransaction } = useStacksBroadcastTransaction({ token: '' });
+  const { stacksBroadcastTransaction } = useStacksBroadcastTransaction({
+    token: '',
+    showSummaryPage: false,
```
Comment (fbwoolf) [inline src/app/common/rpc/use-rpc-sip30-broadcast-transaction.ts:55]: I had originally added `rpc-request` as an actionType to work with the hook, but somehow I removed passing it here. I removed it's use in the component now in favor of this, or we could keep ...neither are what we want, but I was following the already present `isCancelTransaction` and `isIncreaseFeeTransaction` in the hook.
