### PR TITLE
fix: error wording, removed fallback

### LINKED ISSUE #3342: Improve error message when user's UTXO doesn't have enough sats to pay fees
A user has reported they're unable to send this inscription:

https://ordinals.com/inscription/35d5530afafc02f7c0ec8e0a4c7bd5a300f9d8c1229566f5e806c7c85452b8f7i0

However, it seems pretty normal in that:

1. Offset is 0
2. Doesn't share UTXO with other inscriptions
3. UTXO has 2821 sats, over minimum of 1500

What could be causing this error to appear?

Image

### PR DESCRIPTION
**Pull request by kyranjamie**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/4323524060).

Closes #3342

### CODE REVIEW

File: src/app/pages/send/ordinal-inscription/send-inscription-form.tsx [hunk 1]
```diff
@@ -49,41 +50,39 @@ export function SendInscriptionForm() {
...
-      setIsLoading(false);
+    try {
+      const numInscriptionsOnUtxo = await getNumberOfInscriptionOnUtxo(utxo.txid, utxo.vout);
+      if (numInscriptionsOnUtxo !== 1) {
+        setShowError('Sending inscription from utxo with multiple inscriptions is unsupported');
+        return;
+      }
+    } catch (error) {
+      void analytics.track('ordinals_dot_com_unavailable', { error });
+      setShowError('Unable to establish if utxo has multiple inscriptions.');
```
Comment (fbwoolf) [inline src/app/pages/send/ordinal-inscription/send-inscription-form.tsx:79]: For consistency, remove `.` here?

**Review by fbwoolf — APPROVED** [review]

File: src/app/pages/send/ordinal-inscription/send-inscription-form.tsx (hunk 1 above)
Comment (kyranjamie) [reply src/app/pages/send/ordinal-inscription/send-inscription-form.tsx:79]: removed elsewhere
