### PR TITLE
fix: activity item click area too small

### LINKED ISSUE #1685: Fix activity item clicks
On v2.16.0 none of the activity items open to the Explorer upon click in either Chrome or Firefox for me:

image

### PR DESCRIPTION
**Pull request by beguene**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/blockstack/ux/actions/runs/1220303224).

extends the click area of activity transaction item.

cc/ @aulneau @kyranjamie @fbwoolf

### CODE REVIEW

File: src/components/popup/tx-item.tsx [hunk 1]
```diff
@@ -155,10 +155,10 @@ export const TxItem: React.FC<TxItemProps & BoxProps> = ({ transaction, ...rest
 
   return (
     <Box position="relative" cursor="pointer" {...bind} {...rest}>
-      <Stack alignItems="center" spacing="base-loose" isInline position="relative" zIndex={2}>
+      <Stack alignItems="center" spacing="base-loose" isInline position="relative" zIndex={2}  onClick={() => handleOpenTxLink(transaction.tx_id)}>
```
Comment (aulneau) [inline src/components/popup/tx-item.tsx]: This will not work -- this is what it was before. With the addition of the "increase fee" button, with the onClick at this level (a component that wraps the button), when a user hits the increase fee button, they will activate that drawer, while also leaving the wallet to view the explorer link.

**Review by aulneau — DISMISSED** [review]

File: src/components/popup/tx-item.tsx (hunk 1 above)
Comment (beguene) [reply src/components/popup/tx-item.tsx]: Oh yes indeed ! Then we should keep it like before.

Comment (kyranjamie) [reply src/components/popup/tx-item.tsx]: ~~Don't we need to use `e.stopPropagation()` to solve this event bubbling issue?~~ nvm sorry thought this was relating to the missing activity item action

Comment (aulneau) [reply src/components/popup/tx-item.tsx]: yeah it's more of a zIndex issue. It can likely be solved with `pointer-events` and `z-index` css changes.

Comment (beguene) [reply src/components/popup/tx-item.tsx]: Fixed with a e.stopPropagation().

**Comment by beguene** [comment]
@kyranjamie can you please review ?

**Review by kyranjamie — APPROVED** [review]
Ah cool, it did need stopPropagation
