### PR TITLE
fix: serialize sip10 form memo before displaying it

### LINKED ISSUE #4340: Memo when sending SIP010 tokens is stored/displayed in hex instead of ascii
The original report from a fellow Stx Fan:

image

Here is an example when adding a memo sending SIP010 tokens this is what the confirm modal in the wallet will show:
image

In the explorer
image

According to Kyran
> It's hex in the tx payload, but yes not sure why it isn't decoded here

### PR DESCRIPTION
**Pull request by edgarkhanzadian**
> Try out this version of Leather — [Extension build](https://github.com/leather-wallet/extension/actions/runs/7206724308), [Test report](https://leather-wallet.github.io/playwright-reports/fix/sip10-form-memo)

fixes #4340

Serialize sip10 form memo before displaying it

https://github.com/leather-wallet/extension/assets/22010816/d51531a5-02a3-4230-85ac-8af136760588

### CODE REVIEW

**Review by pete-watters — APPROVED** [review]
👍

File: src/app/pages/send/send-crypto-asset-form/family/stacks/hooks/use-stacks-transaction-summary.ts [hunk 1]
```diff
@@ -74,8 +77,9 @@ export function useStacksTransactionSummary(token: CryptoCurrencies) {
     const payload = tx.payload as ContractCallPayload;
     const fee = tx.auth.spendingCondition.fee;
     const txValue = Number((payload.functionArgs[0] as IntCV).value);
-    const memo = cvToString(payload.functionArgs[3]);
-    const memoDisplayText = memo === 'none' ? 'No memo' : memo;
+    const isSome = payload.functionArgs[3].type === ClarityType.OptionalSome;
```
Comment (kyranjamie) [inline src/app/pages/send/send-crypto-asset-form/family/stacks/hooks/use-stacks-transaction-summary.ts:80]: Isn't the ClarityType always some for memos?
