### PR TITLE
fix: inconsistent balances

### LINKED ISSUE #1488: Balance different between balances tab and send screen if tokens locked
Caught this today while making a transfer in `v2.12.0` from an account that's pooling STX.

On the balances screen, I see my unlocked balance:

image

On the Send screen, I see the total balance:

image

The send `Max` button does nothing when I click on it, but the real kicker is that after I enter `5 STX` into the field, I get an error after clicking preview:

image

I tried this by following the same process without clicking max, switching accounts, and after logging out and back in with my secret key.

One thing I noticed, the negative balance might point to a math issue? The available balance shown is similar to `(total - available) - available`

- error `-65.609031 STX`
- available: `134.723 STX`
- total: `335.054851 STX`

Nothing to report in the console.

### LINKED ISSUE #1506: STX stuck after failed transaction
After a failed transaction the amount of STX seems to be stuck. I cant send it to another wallet though it is shown correct in the balance.
Stacks Wallet v2.12.4
adress: SPFPH52MQP00S4880WFBP72GCHMKBQVRE5QYSTFG
current balance: 138 STX
max amount sendable: 18 STX

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/blockstack/ux/actions/runs/1113952644).

This PR fixes inconsistent balances shown when a user has locked STX. In addition, it fixes a validation error shown when using the `Max` button to send STX.

Issue #1488 

image

image

image

Testing:
- Test with an account that has locked STX
- Make sure the STX balance is consistent everywhere
- It should show the available balance with locked STX subtracted out
- Make sure the `Max` button in the send form uses the correct available balance
- Make sure the validation warning shows the correct available balance

cc/ @aulneau @kyranjamie @fbwoolf

### CODE REVIEW

File: src/pages/send-tokens/hooks/use-send-form.ts [hunk 1]
```diff
@@ -8,31 +9,30 @@ import { microStxToStx } from '@common/stacks-utils';
...
 import { removeCommas } from '@common/token-utils';
 import { STX_TRANSFER_TX_SIZE_BYTES } from '@common/constants';
-import BigNumber from 'bignumber.js';
+import { stxTokenState } from '@store/assets/tokens';
 
 export function useSendAmountFieldActions({
   setFieldValue,
 }: Pick<FormikProps<FormValues>, 'setFieldValue'>) {
-  const balances = useFetchBalances();
+  const stxToken = useAtomValue(stxTokenState);
```
Comment (aulneau) [inline src/pages/send-tokens/hooks/use-send-form.ts]: you can create a hook for this, `useStxToken`, as i see you have the `useAtomValue` in multiple places. This is useful if the implementation behind this ever changes, you don't need to find and replace many atoms, etc.

File: src/components/asset-item.tsx [hunk 2]
```diff
@@ -58,10 +58,10 @@ export const AssetItem = memo(
                 <Box>
                   <Tooltip
                     placement="left-start"
-                    label={formatted.isAbbreviated ? amount : undefined}
+                    label={formatted?.isAbbreviated ? amount : undefined}
                   >
                     <Text fontVariantNumeric="tabular-nums" textAlign="right">
-                      {formatted.value}
+                      {formatted?.value}
```
Comment (aulneau) [inline src/components/asset-item.tsx]: what caused this to be potentially undefined? this should probably just never render if the value is null/undefined

**Review by aulneau — CHANGES_REQUESTED** [review]
This looks good -- however I'd like to request a general change to how this was done. Rather than changing all instances of a given balance value to be potentially undefined, eg `if(!stxToken) return undefined`, we should try and just prevent components from rendering if the balance is not defined.

Additionally, we should probably update this: https://github.com/blockstack/stacks-wallet-web/blob/02ccb46035f00f9ce0dc1e3f32cd0dbbaf49c134/src/store/assets/tokens.ts#L75 to still return even if the balance is 0

File: src/pages/send-tokens/hooks/use-send-form.ts (hunk 1 above)
Comment (fbwoolf) [reply src/pages/send-tokens/hooks/use-send-form.ts]: I see this already exists now in `use-assets`. There is a `useStxTokenState`.

File: src/components/asset-item.tsx (hunk 2 above)
Comment (fbwoolf) [reply src/components/asset-item.tsx]: This comes from the `stxTokenState` possibly being `undefined` but I'll look at fixing it.

**Comment by fbwoolf** [comment]
@aulneau maybe circle back and take a look at this again when you get a chance? Thx!

File: src/common/hooks/use-selected-asset.ts [hunk 3]
```diff
@@ -29,12 +31,13 @@ export function useSelectedAsset() {
 
   const balance = useMemo<string | undefined>(() => {
     if (!selectedAsset) return;
-    if (selectedAsset.type === 'stx')
-      return stacksValue({ value: selectedAsset.balance, withTicker: false });
+    if (selectedAsset.type === 'stx') {
+      return stacksValue({ value: stxToken.balance, withTicker: false });
+    }
```
Comment (aulneau) [inline src/common/hooks/use-selected-asset.ts]:
```suggestion
    if (selectedAsset.type === 'stx') return stacksValue({ value: stxToken.balance, withTicker: false });   
```

File: src/common/hooks/use-selected-asset.ts [hunk 4]
```diff
@@ -29,12 +31,13 @@ export function useSelectedAsset() {
...
     if (selectedAsset?.meta?.decimals)
       return ftDecimals(selectedAsset.balance, selectedAsset.meta?.decimals);
     return new BigNumber(selectedAsset.balance).toFormat();
-  }, [selectedAsset]);
+  }, [selectedAsset, stxToken]);
```
Comment (aulneau) [inline src/common/hooks/use-selected-asset.ts]:
```suggestion
  }, [selectedAsset, stxToken.balance]);
```

File: src/pages/send-tokens/hooks/use-send-form-validation.ts [hunk 5]
```diff
@@ -50,24 +49,20 @@ export const useSendFormValidation = ({ setAssetError }: UseSendFormValidationAr
...
-            .minus(lockedBalance)
-            .minus(microStxToStx(STX_TRANSFER_TX_SIZE_BYTES));
-          if (availableBalance.lt(amountBN)) {
-            errors.amount = `${
-              SendFormErrorMessages.InsufficientBalance
-            } ${availableBalance.toString()} STX`;
-          }
+      if (isStx && stxToken.balance) {
+        const curBalance = microStxToStx(stxToken.balance);
+        console.log(selectedAsset.meta?.symbol);
```
Comment (aulneau) [inline src/pages/send-tokens/hooks/use-send-form-validation.ts]:
```suggestion

```

File: src/store/assets/tokens.ts [hunk 6]
```diff
@@ -72,11 +72,10 @@ export const nonFungibleTokensState = atom(get => {
 });
 export const stxTokenState = atom(get => {
   const balances = get(accountBalancesState);
-  if (!balances || balances.stx.balance === '0') return;
   return {
     type: 'stx',
     contractAddress: '',
-    balance: balances.stx.balance,
+    balance: balances?.stx.balance,
```
Comment (aulneau) [inline src/store/assets/tokens.ts]:
```suggestion
    balance: balances?.stx.balance || 0,
```

**Comment by fbwoolf** [comment]
I found one more place the balance is inconsistent. On the `Choose an account` page the STX balance does not consider locked STX. I believe we want that to subtract out the locked STX as well?

**Comment by aulneau** [comment]
I think we should default to a calculated available balance which shows what is not locked (stacked or vesting tokens) throughout the application. Perhaps we need a new `availableStxBalance` atom

**Comment by fbwoolf** [comment]
> I think we should default to a calculated available balance which shows what is not locked (stacked or vesting tokens) throughout the application. Perhaps we need a new `availableStxBalance` atom

Yep, I agree, I will add it to this work.

**Comment by fbwoolf** [comment]
> I think we should default to a calculated available balance which shows what is not locked (stacked or vesting tokens) throughout the application. Perhaps we need a new `availableStxBalance` atom

I ended up creating an `accountAvailableStxBalanceState` atomFamily and a `currentAccountAvailableStxBalanceState` atom bc I needed to use the address as a param before an account is selected. If that isn't right, let me know.

File: src/store/accounts/index.ts [hunk 7]
```diff
@@ -129,6 +132,17 @@ export const accountDataState = atomFamily<string, AllAccountData | undefined>(a
...
 );
 
+export const accountAvailableStxBalanceState = atomFamily<string, string | undefined>(address =>
+  atom(get => {
+    const accountData = get(accountDataState(address));
+    if (!accountData) return;
+    const stx = new BigNumber(accountData.balances.stx.balance);
+    const lockedStx = new BigNumber(accountData.balances.stx.locked);
+    const curBalance = stx.minus(lockedStx);
+    return curBalance.toString();
```
Comment (kyranjamie) [inline src/store/accounts/index.ts]: Why return the string, rather than the BigNumber object?

File: src/store/accounts/index.ts [hunk 8]
```diff
@@ -137,6 +151,15 @@ export const currentAccountDataState = atom(get => {
   return get(accountDataResponseState([address, network.url]));
 });
 
+export const currentAccountAvailableStxBalanceState = atom(get => {
+  const currentAccountData = get(currentAccountDataState);
+  if (!currentAccountData) return;
+  const stx = new BigNumber(currentAccountData.balances.stx.balance);
+  const lockedStx = new BigNumber(currentAccountData.balances.stx.locked);
+  const curBalance = stx.minus(lockedStx);
+  return curBalance.toString();
```
Comment (kyranjamie) [inline src/store/accounts/index.ts]: Same here, better to call toString() when consumed, than have to reinitialise another BigNumber

Comment (fbwoolf) [reply src/store/accounts/index.ts]: Ok, yep, I debated about which was better. I will change it, thx for the feedback!

**Comment by aulneau** [comment]
Feel free to rebase off main and the CI should pass

**Comment by fbwoolf** [comment]
> Feel free to rebase off main and the CI should pass

Thanks, I did, hope all passes now!

**Comment by fbwoolf** [comment]
@aulneau can you circle back and approve this at some point? The merge is being blocked.

File: src/common/hooks/use-selected-asset.ts [hunk 9]
```diff
@@ -30,11 +32,11 @@ export function useSelectedAsset() {
   const balance = useMemo<string | undefined>(() => {
     if (!selectedAsset) return;
     if (selectedAsset.type === 'stx')
-      return stacksValue({ value: selectedAsset.balance, withTicker: false });
+      return stacksValue({ value: availableStxBalance?.toString() || 0, withTicker: false });
```
Comment (aulneau) [inline src/common/hooks/use-selected-asset.ts]:
```suggestion
      return stacksValue({ value: availableStxBalance || 0, withTicker: false });
```

File: src/components/asset-row.tsx [hunk 10]
```diff
@@ -21,7 +22,7 @@ export const AssetRow = React.forwardRef<HTMLDivElement, AssetRowProps>((props,
     type === 'ft'
       ? ftDecimals(balance, meta?.decimals || 0)
       : type === 'stx'
-      ? stacksValue({ value: balance, withTicker: false })
+      ? stacksValue({ value: availableStxBalance?.toString() || 0, withTicker: false })
```
Comment (aulneau) [inline src/components/asset-row.tsx]:
```suggestion
      ? stacksValue({ value: availableStxBalance || 0, withTicker: false })
```

File: src/components/popup/token-assets.tsx [hunk 11]
```diff
@@ -57,20 +57,20 @@ function NoAssets(props: StackProps) {
...
+    stxToken.balance.isEqualTo(0) &&
     Object.keys(balances.fungible_tokens).length === 0 &&
     Object.keys(balances.non_fungible_tokens).length === 0;
 
   return noAssets ? (
     <NoAssets {...props} />
   ) : (
     <Stack pb="extra-loose" spacing="extra-loose" {...props}>
-      {stxTokens && <AssetRow asset={stxTokens} />}
+      {stxToken.balance.isGreaterThanOrEqualTo(0) && <AssetRow asset={stxToken} />}
```
Comment (aulneau) [inline src/components/popup/token-assets.tsx]:
```suggestion
      {stxToken.balance.isGreaterThan(0) && <AssetRow asset={stxToken} />}
```

File: src/features/account-balance-caption.tsx [hunk 12]
```diff
@@ -1,18 +1,18 @@
...
+import { useAccountAvailableStxBalance } from '@common/hooks/use-available-stx-balance';
 
 export const AccountBalanceCaption = ({ address }: { address: string }) => {
-  const accountData = useAtomValue(accountDataState(address));
-  if (!accountData) return null;
+  const availableStxBalance = useAccountAvailableStxBalance(address);
+
   const balance = stacksValue({
-    value: parseInt(accountData?.balances.stx.balance),
+    value: availableStxBalance?.toString() || 0,
```
Comment (aulneau) [inline src/features/account-balance-caption.tsx]:
```suggestion
    value: availableStxBalance || 0,
```

File: src/pages/send-tokens/hooks/use-send-form-validation.ts [hunk 13]
```diff
@@ -50,24 +49,19 @@ export const useSendFormValidation = ({ setAssetError }: UseSendFormValidationAr
...
-          const availableBalance = curBalance
-            .minus(lockedBalance)
-            .minus(microStxToStx(STX_TRANSFER_TX_SIZE_BYTES));
-          if (availableBalance.lt(amountBN)) {
-            errors.amount = `${
-              SendFormErrorMessages.InsufficientBalance
-            } ${availableBalance.toString()} STX`;
-          }
+      if (isStx && availableStxBalance) {
+        const curBalance = microStxToStx(availableStxBalance.toString());
```
Comment (aulneau) [inline src/pages/send-tokens/hooks/use-send-form-validation.ts]:
```suggestion
        const curBalance = microStxToStx(availableStxBalance);
```

File: src/pages/send-tokens/hooks/use-send-form.ts [hunk 14]
```diff
@@ -1,38 +1,37 @@
...
     (fee: number) => {
-      if (!selectedAsset || !balances || !balance) return;
+      if (!selectedAsset || !balance) return;
       if (isStx) {
-        const availableBalance = new BigNumber(balances.stx.balance).minus(balances.stx.locked);
         const txFee = microStxToStx(
           new BigNumber(fee ?? 1).multipliedBy(STX_TRANSFER_TX_SIZE_BYTES).toString()
         );
-        const stx = microStxToStx(availableBalance.toString()).minus(txFee);
+        const stx = microStxToStx(availableStxBalance?.toString() || 0).minus(txFee);
```
Comment (aulneau) [inline src/pages/send-tokens/hooks/use-send-form.ts]:
```suggestion
        const stx = microStxToStx(availableStxBalance || 0).minus(txFee);
```

File: src/pages/transaction-signing/components/transaction-errors.tsx [hunk 15]
```diff
@@ -53,9 +53,9 @@ export const StxTransferInsufficientFundsErrorMessage = memo(props => {
             <SpaceBetween>
               <Caption>Current balance</Caption>
               <Caption>
-                {balances?.stx?.balance
+                {availableStxBalance
                   ? stacksValue({
-                      value: balances?.stx?.balance,
+                      value: availableStxBalance.toString(),
```
Comment (aulneau) [inline src/pages/transaction-signing/components/transaction-errors.tsx]:
```suggestion
                      value: availableStxBalance,
```

File: src/pages/transaction-signing/hooks/use-transaction-error.ts [hunk 16]
```diff
@@ -39,8 +39,8 @@ export function useTransactionError() {
     }
     if (broadcastError) return TransactionErrorReason.BroadcastError;
 
-    if (balances) {
-      const stxBalance = new BigNumber(balances.stx.balance);
+    if (availableStxBalance) {
+      const stxBalance = new BigNumber(availableStxBalance);
```
Comment (aulneau) [inline src/pages/transaction-signing/hooks/use-transaction-error.ts]: Isn't this already a bignumber?

File: src/store/assets/tokens.ts [hunk 17]
```diff
@@ -73,11 +73,10 @@ export const nonFungibleTokensState = atom(get => {
 });
 export const stxTokenState = atom(get => {
   const balances = get(accountBalancesState);
-  if (!balances || balances.stx.balance.isEqualTo(0)) return;
   return {
     type: 'stx',
     contractAddress: '',
-    balance: new BigNumber(balances.stx.balance),
+    balance: balances?.stx.balance ? new BigNumber(balances?.stx.balance) : 0,
```
Comment (aulneau) [inline src/store/assets/tokens.ts]: This should probably be the `currentAccountAvailableStxBalanceState`, right?

**Review by aulneau — CHANGES_REQUESTED** [review]
Went through once more, just one question, and then some suggestions -- most of the methods can take a bignumber, no need to convert it to string, just to be converted back.

File: src/common/hooks/use-selected-asset.ts (hunk 9 above)
Comment (fbwoolf) [reply src/common/hooks/use-selected-asset.ts]: Ok, I see this now with the changes Kyran made adding the `BigNumber` type to value. I'm just getting familiar with using BigNumber. Will go thru and makes these changes.

File: src/pages/transaction-signing/hooks/use-transaction-error.ts (hunk 16 above)
Comment (fbwoolf) [reply src/pages/transaction-signing/hooks/use-transaction-error.ts]: Yep, missed taking that out, thx!

File: src/store/assets/tokens.ts (hunk 17 above)
Comment (fbwoolf) [reply src/store/assets/tokens.ts]: Yep, that is probably what we want here. I will update it.

File: src/store/assets/tokens.ts [hunk 18]
```diff
@@ -73,11 +72,10 @@ export const nonFungibleTokensState = atom(get => {
 });
 export const stxTokenState = atom(get => {
   const balances = get(accountBalancesState);
-  if (!balances || balances.stx.balance.isEqualTo(0)) return;
   return {
     type: 'stx',
     contractAddress: '',
-    balance: new BigNumber(balances.stx.balance),
+    balance: balances?.stx.balance || 0,
```
Comment (aulneau) [inline src/store/assets/tokens.ts]: this is still meant to be a BigNumber, yeah? i though we spoke about this being the same as available balance?

Comment (kyranjamie) [reply src/store/assets/tokens.ts]: I guess this'll need to be changed when rebased on `feat/microblocks`

Comment (aulneau) [reply src/store/assets/tokens.ts]: this will likely be merged before that, so it will be the other way around

Comment (fbwoolf) [reply src/store/assets/tokens.ts]: `balances?.stx.balance` here is already `BigNumber`.

Comment (fbwoolf) [reply src/store/assets/tokens.ts]: I think Kyran's work just made this change in the `accountBalancesState`:
```
balance: new BigNumber(stxBalance || balances.stx.balance),
```

Comment (beguene) [reply src/store/assets/tokens.ts]: > this is still meant to be a BigNumber, yeah? i though we spoke about this being the same as available balance?

That's what I did in my microblock branch after rebasing with main: both balances (anchored and unanchored) are BigNumber now.

Comment (aulneau) [reply src/store/assets/tokens.ts]: > I think Kyran's work just made this change in the `accountBalancesState`:
> 
> ```
> balance: new BigNumber(stxBalance || balances.stx.balance),
> ```

oh okay, perfect. What about it being the `currentAccountAvailableBalance`?

Comment (fbwoolf) [reply src/store/assets/tokens.ts]: When I switched to that it broke the integration test, not really sure why. I can do some more digging but I'm not sure what the difference is b/w the `accountBalancesState` balance and `currentAccountAvailableBalance`. The former seems to use an `accountInfoState` that I am unfamiliar with at this point.

Comment (aulneau) [reply src/store/assets/tokens.ts]: my understanding is that if we use just `accountBalanceState` it will not take into consideration the locked balance, which is what you changed in this PR, right?

Comment (fbwoolf) [reply src/store/assets/tokens.ts]: `stxBalance` in `accountBalanceState` does take into account the locked STX, so when I add that `or` condition to the `currentAccountAvailableStxBalanceState` all tests pass and everything is good to go. I will push it up.

Comment (fbwoolf) [reply src/store/assets/tokens.ts]: I have retested this everywhere and it seems to be behaving correctly in the UI and all tests are passing.

File: src/store/accounts/index.ts [hunk 19]
```diff
@@ -154,11 +154,12 @@ export const currentAccountDataState = atom(get => {
 
 export const currentAccountAvailableStxBalanceState = atom(get => {
   const currentAccountData = get(currentAccountDataState);
+  const stxBalance = get(accountInfoState)?.balance.toString(10);
   if (!currentAccountData) return;
   const stx = new BigNumber(currentAccountData.balances.stx.balance);
   const lockedStx = new BigNumber(currentAccountData.balances.stx.locked);
   const curBalance = stx.minus(lockedStx);
-  return curBalance;
+  return (stxBalance && new BigNumber(stxBalance)) || curBalance;
```
Comment (aulneau) [inline src/store/accounts/index.ts]: @fbwoolf shouldn't this be the inverse?
```suggestion
  return curBalance || (stxBalance && new BigNumber(stxBalance));
```

**Review by aulneau — APPROVED** [review]

**Comment by aulneau** [comment]
once all green, shippit!!
