### PR TITLE
fix(app): critical bug when trying to create new key, fixes #381

### LINKED ISSUE #381: [Connect] Bug reading authRequest param when creating new SK
Kapture 2020-05-13 at 15 16 58

**To replicate**
1. Sign in
2. Create a Secret Key

### PR DESCRIPTION
**Pull request by kyranjamie**
This change ensures the _Create a Secret Key_ functionality works.

Wondering how we can make this more robust. @hstove are we looking for a particular search param here, or just all of them?

### CODE REVIEW

File: packages/app/src/components/routes.tsx [hunk 1]
```diff
@@ -39,24 +39,22 @@ export const Routes: React.FC = () => {
   const isSignedIn = !isOnboardingInProgress && identities.length;
 
   const getSignUpElement = () => {
+    const { search } = new URL(location.href);
```
Comment (hstove) [inline packages/app/src/components/routes.tsx]: Shouldn't this not work? Since the query params are technically part of the hash?

**Comment by hstove** [comment]
> Wondering how we can make this more robust. @hstove are we looking for a particular search param here, or just all of them?

TBH I'm having a brain fart this morning trying to remember exactly why we need them. I think, ideally, we shouldn't have to pass around query params like this. It might be due to a kind of 'race condition' when trying to parse the `authRequest`.

**Review by hstove — APPROVED** [review]
Thanks! Confirmed that this works.
