### PR TITLE
test: send btc tx and UI fixes

### LINKED ISSUE #2890: [Bitcoin] Test sending a bitcoin transaction

### LINKED ISSUE #3166: [Bitcoin] Content can escape bounds of containing box
image

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/4203505073).

This PR adds a test for sending btc. I didn't get far, but we can add more to it quickly once I know what we want to validate, and have the fees and success pages setup.

I also tried to catch/fix minor UI bugs here:
- Fixed send form width 100% not working
- Fixed send form container not being reponsive
- Fixed the btc for recipient field not having `lastChild` to round border corners on error and focus
- Fixed account addresses in header in popup wrapping
- Renamed some forgotten components with the move away from `CryptoCurrency` in names
- Truncated the btc recipient address on the preview (I confirmed CashApp and Coinbase do the same)

### CODE REVIEW

File: src/app/pages/send/send-crypto-asset-form/form/btc/btc-send-form-confirmation-details.tsx [hunk 1]
```diff
@@ -33,7 +34,7 @@ export function BtcSendFormConfirmationDetails(props: BtcSendFormConfirmationDet
   return (
     <ConfirmationDetailsLayout amount={amount}>
       <ConfirmationDetail detail="Token" value="Bitcoin" />
-      <ConfirmationDetail detail="To" value={recipient} />
+      <ConfirmationDetail detail="To" value={truncateMiddle(recipient, 4)} />
```
Comment (kyranjamie) [inline src/app/pages/send/send-crypto-asset-form/form/btc/btc-send-form-confirmation-details.tsx:37]: Not so sure we want to do this. Users should be able to verify they're sending to the correct address.

cc/ @mica000 should consider this in designs as addresses can be long. Maybe we can reuse this component some how 

image

**Review by kyranjamie — APPROVED** [review]

File: src/app/pages/send/send-crypto-asset-form/form/btc/btc-send-form-confirmation-details.tsx (hunk 1 above)
Comment (kyranjamie) [reply src/app/pages/send/send-crypto-asset-form/form/btc/btc-send-form-confirmation-details.tsx:37]: https://bitcoin.design/guide/glossary/address/#visual-formatting

**Comment by kyranjamie** [comment]
Rebased, which removed a commit which I think is in dev already?
