### PR TITLE
Fix/validate contract address

### LINKED ISSUE #1464: [2.12.2] Bug: Error when trying to delegate to pool
**Getting this error when trying to delegate to a pool**

error1

An error occurred while using Stacks Wallet for Web (`2.12.2`).

#### Stack trace
```bash
Error: Not a c32-encoded string
    at Object.c32decode (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:85504:15)
    at Object.c32checkDecode (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:85390:30)
    at c32addressDecode (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:85205:23)
    at createAddress (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:25841:93)
    at createContractCallPayload (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:25196:90)
    at makeUnsignedContractCall (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:23578:98)
    at makeContractCall (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:23634:35)
    at generateContractCallTx (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:48213:90)
    at _callee2$ (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:48387:151)
    at tryCatch (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:141521:40)
```

### PR DESCRIPTION
**Pull request by aulneau**
> Try out this version of the Stacks Wallet - download [extension builds](https://github.com/blockstack/ux/actions/runs/1052839113).

fixes: https://github.com/blockstack/stacks-wallet-web/issues/1464

cc/ @aulneau @kyranjamie @fbwoolf

### CODE REVIEW

File: src/store/transactions/index.ts [hunk 1]
```diff
@@ -36,17 +36,23 @@ export const signedStacksTransactionState = atom(get => {
...
-    serialized,
-    isSponsored: signedTransaction?.auth?.authType === AuthType.Sponsored,
-    nonce: signedTransaction?.auth.spendingCondition?.nonce.toNumber(),
-    fee: signedTransaction?.auth.spendingCondition?.fee?.toNumber(),
-    txRaw,
-  };
+  try {
+    const signedTransaction = get(signedStacksTransactionState);
+    if (!signedTransaction) return;
+    const serialized = signedTransaction.serialize();
```
Comment (beguene) [inline src/store/transactions/index.ts:42]: I suspect only this serialize and stacksTransactionToHex which calls serialize might raise an exception. Would it be better to try catch only those statements ?

**Review by fbwoolf — APPROVED** [review]

File: src/store/transactions/index.ts (hunk 1 above)
Comment (aulneau) [reply src/store/transactions/index.ts:42]: if anything in this block throws, we want to return undefined
