### PR TITLE
fix: allow virtuoso to resize dynamically, ref #5242

### LINKED ISSUE #5242: Can't scroll to last couple of accounts on the account selection screen
I can reproduce this sometimes the last 5 accounts are not displayed. when scrolling the select account screen. 

See the issue after clicking account 1 (or any)
to open the account selection page
then add account
switch account again scroll up then down
try this on an wallet with 50 or more accounts (that is what the user was testing with, and I saw it on a wallet with 500 accounts too).

 

https://github.com/leather-wallet/extension/assets/33360391/4d9347cb-7015-4b4f-875d-ca434d5efe75

### LINKED ISSUE #5310: Unable to scroll and select last accounts
I was able to reproduce this issue after adding 15 accounts. Unable to scroll and select past account 9. 

Reported using 6.35.1 - Chrome browser.
https://discord.com/channels/621759717756370964/745197302255321108/1232730207807344755

image1
image2
image3

### PR DESCRIPTION
**Pull request by pete-watters**
> Try out Leather build 6f242c3 — [Extension build](https://github.com/leather-wallet/extension/actions/runs/8801377751), [Test report](https://leather-wallet.github.io/playwright-reports/fix/5242/virtuoso-dynamic-height), [Storybook](https://fix-5242-virtuoso-dynamic-height--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=fix/5242/virtuoso-dynamic-height)

This PR ensures that account lists grow appropriately and that users with many accounts can access all of them. 

https://github.com/leather-wallet/extension/issues/5242

### CODE REVIEW

File: src/app/pages/choose-account/choose-account.tsx [hunk 1]
```diff
@@ -34,12 +37,16 @@ export const ChooseAccount = memo(() => {
           {url && <RequesterFlag requester={url.toString()} />}
           <LogomarkIcon width="248px" height="58px" />
           <Stack gap="space.04">
-            <styled.h1 textStyle="heading.05">Choose an account to connect</styled.h1>
+            <styled.h1 textStyle="heading.05">
```
Comment (pete-watters) [inline src/app/pages/choose-account/choose-account.tsx:40]: I added this code as if you only have BTC connected on Ledger and then try to sign in to something it was just showing the logo and an empty screen

Now it shows:
Screenshot 2024-04-23 at 11 14 46

File: src/app/ui/components/virtuoso.tsx [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+export function VirtuosoWrapper({ children, hasFooter, isPopup }: VirtuosoWrapper) {
+  const [key, setKey] = useState(0);
+  const isAtLeastMd = useViewportMinWidth('md');
+  const virtualHeight = isAtLeastMd ? '70vh' : '100vh';
+  const headerHeight = isPopup ? 230 : 80;
+  const footerHeight = hasFooter ? 95 : 0;
+  const heightOffset = headerHeight + footerHeight;
+  const height = vhToPixels(virtualHeight) - heightOffset;
+
+  const onResize = () => {
```
Comment (pete-watters) [inline src/app/ui/components/virtuoso.tsx:28]: I tried to be more precise and update to the exact height we wanted on re-size but it was buggy. 

Instead, here I force a re-render on re-size by changing the `key`. This means the wrapper height can adjust properly according to the parents `vh`

File: src/app/ui/components/virtuoso.tsx [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+import { useOnResizeListener } from '@app/common/hooks/use-on-resize-listener';
+
+interface VirtuosoWrapper {
+  children: ReactNode;
+  hasFooter?: boolean;
+  isPopup?: boolean;
+}
+
+function vhToPixels(vh: string) {
+  const numericHeight = +vh.replace('vh', '');
```
Comment (pete-watters) [inline src/app/ui/components/virtuoso.tsx:15]: This is converting `vh` to pixels so that it's a numeric value and we can compute the height of the wrapper, taking into account offsets needed for headers + footers

File: src/app/ui/components/virtuoso.tsx [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+  return (numericHeight * window.innerHeight) / 100;
+}
+
+export function VirtuosoWrapper({ children, hasFooter, isPopup }: VirtuosoWrapper) {
```
Comment (pete-watters) [inline src/app/ui/components/virtuoso.tsx:19]: I should improve this more by:

- accepting the height as a prop
- using tokens for footer / header height
    - I couldn't get them working using `token('size`
    - When importing and using `token.size.X.value` it was giving type errors 

I can improve this further but I think this needs to get released sooner

File: src/app/ui/components/containers/dialog/dialog.tsx [hunk 5]
```diff
@@ -68,16 +76,20 @@ export function Dialog({ children, footer, header, onClose, isShowing }: RadixDi
...
-              style={{
-                height: '100%',
-                maxHeight: contentMaxHeight,
-                marginBottom: footer ? token('sizes.footerHeight') : token('spacing.space.04'),
-                overflowY: 'auto',
-              }}
-            >
-              {children}
-            </Box>
+            {wrapChildren ? (
```
Comment (pete-watters) [inline src/app/ui/components/containers/dialog/dialog.tsx:79]: All other dialogs have this `Box` to help them size dynamically but ones containing `Virtuoso` lists now bypass that.

File: src/app/pages/send/send-crypto-asset-form/components/recipient-accounts-dialog/recipient-accounts-dialog.tsx [hunk 6]
```diff
@@ -23,27 +23,31 @@ export function RecipientAccountsDialog() {
...
-        )}
-        totalCount={stacksAddressesNum || btcAddressesNum}
-      />
+    <Dialog
+      header={<Header variant="dialog" title="My accounts" />}
+      isShowing
+      onClose={onGoBack}
+      wrapChildren={false}
+    >
+      <VirtuosoWrapper>
```
Comment (pete-watters) [inline src/app/pages/send/send-crypto-asset-form/components/recipient-accounts-dialog/recipient-accounts-dialog.tsx:34]: `Virtuoso` height is now set to `100%` and the actual height is controlled by a wrapping container

File: src/app/pages/home/home.tsx [hunk 7]
```diff
@@ -22,9 +21,9 @@ import { AccountActions } from './components/account-actions';
 import { HomeTabs } from './components/home-tabs';
 
 export function Home() {
-  const [isShowingSwitchAccount, setIsShowingSwitchAccount] = useState(false);
   const { decodedAuthRequest } = useOnboardingState();
-
+  const { isShowingSwitchAccount, setIsShowingSwitchAccount } =
```
Comment (pete-watters) [inline src/app/pages/home/home.tsx:25]: I was investigating why we were re-rendering `SwitchAccount` and I found this mistake. 

We were rendering it both inside of the main `<Container` and also inside of `AccountCard`. 

Now it stays at `Container` level only and `OutletContext` is used to show / hide it. 

It needs to stay at that level so the settings menu can also trigger it

File: src/app/features/message-signer/message-preview-box.tsx [hunk 8]
```diff
@@ -17,8 +17,8 @@ export function MessagePreviewBox({ message, hash }: MessageBoxProps) {
         py="space.05"
         overflowX="auto"
       >
-        {message.split(/\r?\n/).map(line => (
-          <styled.span key={line} textStyle="label.01">
+        {message.split(/\r?\n/).map((line, index) => (
```
Comment (pete-watters) [inline src/app/features/message-signer/message-preview-box.tsx:20]: This was throwing a duplicate keys error

File: src/app/features/container/container.tsx [hunk 9]
```diff
@@ -97,10 +97,12 @@ export function Container() {
   const isLogoClickable = variant !== 'home' && !isRpcRoute(pathname);
   return (
     <>
-      <SwitchAccountDialog
-        isShowing={isShowingSwitchAccount}
-        onClose={() => setIsShowingSwitchAccount(false)}
-      />
+      {isShowingSwitchAccount && (
```
Comment (pete-watters) [inline src/app/features/container/container.tsx:100]: There was a mistake here in that `<SwitchAccountDialog` shouldn't be in the DOM unless showing

File: src/app/common/hooks/use-media-query.ts [hunk 10]
```diff
@@ -0,0 +1,23 @@
+import { useEffect, useState } from 'react';
```
Comment (pete-watters) [inline src/app/common/hooks/use-media-query.ts:1]: Re-adding this which I naively removed as I thought we didn't need it, however it's important as it alters the breakpoint on re-size

File: src/app/common/hooks/use-media-query.ts [hunk 11]
```diff
@@ -0,0 +1,23 @@
...
+import { BreakpointToken, token } from 'leather-styles/tokens';
+
+function useMediaQuery(query: string) {
+  const [matches, setMatches] = useState(false);
+
+  useEffect(() => {
+    const media = window.matchMedia(query);
+    if (media.matches !== matches) {
+      setMatches(media.matches);
+    }
```
Comment (alter-eggo) [inline src/app/common/hooks/use-media-query.ts:12]: maybe just setMatches(media.matches);? do we really need this `if` check?

File: src/app/features/container/container.tsx (hunk 9 above)
Comment (alter-eggo) [reply src/app/features/container/container.tsx:100]: nice catch! I believe problem with requests not being cancelled on close in `SwitchAccountDialog` is here

File: src/app/pages/choose-account/choose-account.tsx (hunk 1 above)
Comment (alter-eggo) [reply src/app/pages/choose-account/choose-account.tsx:40]: I believe we prob need some more explanation of what's going on for users?
something like 'you are connected with ledger in bitcoin mode only, please connect stacks account as well to use this feature' or smth like that

**Review by alter-eggo — APPROVED** [review]
great work 💪

File: src/app/common/hooks/use-media-query.ts (hunk 11 above)
Comment (pete-watters) [reply src/app/common/hooks/use-media-query.ts:12]: Let me check if this will work. I just restored this file as I had deleted it in [this PR ](https://github.com/leather-wallet/extension/pull/4655)

File: src/app/pages/choose-account/choose-account.tsx (hunk 1 above)
Comment (pete-watters) [reply src/app/pages/choose-account/choose-account.tsx:40]: @mica000 @markmhendrickson @fabric-8 : 

Do you have any input on what copy to use on this screen? 

Right now :
- AS A USER signed in with ledger
- AND only have BTC connected 
- WHEN you try and sign in to a site e.g. Gamma
- THEN you see an empty screen below the leather logo like this 

Screenshot 2024-04-24 at 11 23 15

I've just made a small change so that in these cases we say `No connected accounts found` instead of `Choose an account to connect`

File: src/app/common/hooks/use-media-query.ts (hunk 11 above)
Comment (pete-watters) [reply src/app/common/hooks/use-media-query.ts:12]: I'll do this in a follow up.

File: src/app/pages/choose-account/choose-account.tsx (hunk 1 above)
Comment (markmhendrickson) [reply src/app/pages/choose-account/choose-account.tsx:40]: Following up here a bit late:

Ideally the user should be able to connect their wallet to any site with a Ledger account, regardless of whether they've connected with Ledger for BTC or STX.

It seems that our legacy endpoint for connecting (used by Gamma and others) is _not_ behaving this way. However, because it's legacy (and deprecated), we don't need to update it per se.

I also assume that our newer endpoint (`getAddresses`) _does_ behave this way, though I haven't tested per se. And as we implement this endpoint for mobile, we should retain this agnostic behavior, allowing users to connect regardless of Ledger connectivity by token.

Comment (pete-watters) [reply src/app/pages/choose-account/choose-account.tsx:40]: Thanks for following up anyway 👍
