### PR TITLE
fix: edit nonce to zero

### LINKED ISSUE #2677: Edit nonce form does not accept 0
User reported a missing `0` nonce but the edit form overrides the input of `0` and replaces with the api suggested next nonce.

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/3160675560).

This PR fixes an edge case where a user skips the zero nonce tx and tries to go back and edit the nonce to zero. There was a bug happening when generating the unsigned tx the next suggested nonce was replacing the input value. Also, a nonce detail was added to the confirmation modal so the user can see the nonce they are signing.

Screen Shot 2022-09-29 at 7 10 55 PM

EDIT: Maybe nonce should be listed here first? @markmhx 

cc/ @kyranjamie @fbwoolf

### CODE REVIEW

File: src/app/pages/send-tokens/components/send-tokens-confirm-drawer/send-tokens-confirm-drawer.tsx [hunk 1]
```diff
@@ -40,22 +41,27 @@ export function SendTokensSoftwareConfirmDrawer(props: SendTokensSoftwareConfirm
       onClose={onClose}
       pauseOnClickOutside={showEditNonce}
     >
-      <Stack pb="extra-loose" px="loose" spacing="loose">
+      <Stack pb="extra-loose" px="loose" spacing="base">
         <SendTokensConfirmDetails
           amount={values.amount}
```
Comment (fbwoolf) [inline src/app/pages/send-tokens/components/send-tokens-confirm-drawer/send-tokens-confirm-drawer.tsx:46]: I would argue here we need to use the values from the generated unsigned tx not the form values. The form values are used to generate the unsigned tx but there are conditionals present. I attempted to change these but there were errors telling me that `amount` did not exist on `unsignedTransaction.payload` which I don't understand bc that should exist on `StacksTransaction`? Any thoughts?

Comment (kyranjamie) [reply src/app/pages/send-tokens/components/send-tokens-confirm-drawer/send-tokens-confirm-drawer.tsx:46]: Yeah makes sense. If we can use the current unsigned tx as a source of truth, let's

**Review by kyranjamie — APPROVED** [review]
