### PR TITLE
fix: search and select asset

### LINKED ISSUE #2335: searching for token and selecting it, selects stx
Wallet v.3.5.1 - Chrome 99.0.4844.83 (Official Build) (arm64), MacOS 12.0.1

When trying to send MIA I noticed that when I type in MIA and miami coin comes up, after selecting it the form is filled out for Stacks instead of MIA. If I scroll down and select MIA instead of selecting it via search, it works.

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/2073789471).

This PR fixes the asset search input where no matter what was selected by the user it would select the first item in the asset list (STX). There is a lot of code around this search, so I fixed the bug but there is a lot more that can be done to clean this up at some point.

cc/ @kyranjamie @fbwoolf @beguene @He1DAr

### CODE REVIEW

File: src/app/pages/send-tokens/components/asset-search/asset-search.tsx [hunk 1]
```diff
@@ -142,6 +136,9 @@ const AssetSearchField = memo(
             onChange={(e: FormEvent<HTMLInputElement>) => {
               const { value } = e.currentTarget;
               setSearchInput(value);
+              setAssetItems(
+                assets.filter(asset => asset.name.toLowerCase().includes(value.toLowerCase()))
```
Comment (kyranjamie) [inline src/app/pages/send-tokens/components/asset-search/asset-search.tsx]: Could this logic be extracted to a fn with descriptive name?

**Review by kyranjamie — COMMENTED** [review]
Why doesn't this make use of the `onInputValueChange` prop of the combo box https://www.downshift-js.com/use-combobox

**Comment by fbwoolf** [comment]
> Why doesn't this make use of the `onInputValueChange` prop of the combo box https://www.downshift-js.com/use-combobox

I don't know, my VSCode extension says you wrote this code originally but possibly not? I can try `onInputValueChange` but just saw the `onChange` to the input was happening here. As I mentioned in the description, a lot of the code around the search should be refactored more thoroughly.

File: src/app/pages/send-tokens/components/asset-search/asset-search.tsx (hunk 1 above)
Comment (fbwoolf) [reply src/app/pages/send-tokens/components/asset-search/asset-search.tsx]: Yep, I can.

**Comment by fbwoolf** [comment]
Tbh, I tried `onInputValueChange` first and don't believe it worked but will try again.

**Comment by fbwoolf** [comment]
I think this didn't work originally bc I overlooked moving the input `onChange` entirely ...not sure why it was put there but I moved it to `onInputValueChange`. Definitely feel like a lot more can be done here and I'm happy to do it, but felt like we would want to get this bug fixed. Should I do a larger refactor now to clean this up? These files are messy.

**Review by kyranjamie — APPROVED** [review]
> Should I do a larger refactor now to clean this up? These files are messy.

Besides my comments, everything else looks okay. Though I don't see this as having any particular urgency (at least compared to other bugs we often come across 😅 ). So if there's more you'd like to refactor tidy up, I'd highly encourage it.

**Comment by fbwoolf** [comment]
> So if there's more you'd like to refactor tidy up, I'd highly encourage it.

Looking into why we are using atoms to manage this search input ...will refactor them out if can.

File: src/app/pages/send-tokens/components/asset-search/asset-search.tsx [hunk 2]
```diff
@@ -1,176 +1,56 @@
...
-
-    const labelRef = useRef(null);
-    const comboRef = useRef(null);
-
-    if (!assets) return null;
+      return () => onClearSearch();
+      // eslint-disable-next-line react-hooks/exhaustive-deps
+    }, []);
+
+    const onClearSearch = () => {
```
Comment (fbwoolf) [inline src/app/pages/send-tokens/components/asset-search/asset-search.tsx:36]: @kyranjamie I did more work to separate out these components and clean things up. What is your opinion on these functions here, do they need `useCallback`? I feel like we over use useCallback?  Was referencing this: https://kentcdodds.com/blog/usememo-and-usecallback

**Comment by fbwoolf** [comment]
@kyranjamie I refactored this a bit more ...if you want to review again please do or I'll move it to QA.

File: src/app/pages/send-tokens/components/asset-search/asset-search.tsx (hunk 2 above)
Comment (kyranjamie) [reply src/app/pages/send-tokens/components/asset-search/asset-search.tsx:36]: Thanks for sharing. Indeed, in components it's not so helpful, I've probably overused myself. 

Though I would push referential equality point, and go as far as saying that inside hooks we should _always_ use `useCallback` or `useMemo`. You never know when/where it'll be consumed, and new references on every render can cause hard to debug infinite render loops that freeze the app.

Comment (fbwoolf) [reply src/app/pages/send-tokens/components/asset-search/asset-search.tsx:36]: Thanks for feedback. 👍
