### PR TITLE
Reset to mainnet on signout

### LINKED ISSUE #5239: Cannot connect Ledger in Testnet
There is a bug where if you:
- login to a wallet without ledger
- change the network to testnet
- logout
- you cannot login with ledger as it has persisted the network as testnet

You will see this error:
Screenshot 2024-04-16 at 16 23 19

Then if you try and sign in with a key you can see its on `Testnet`:
Screenshot 2024-04-16 at 16 23 29

We used to let users change the network from the header but we deprecated this. 

I think a good fix would be to reset the wallet to mainnet on sign out

### PR DESCRIPTION
**Pull request by pete-watters**
> Try out Leather build af1d8bc — [Extension build](https://github.com/leather-wallet/extension/actions/runs/8818872416), [Test report](https://leather-wallet.github.io/playwright-reports/fix/5239/reset-to-mainnet-on-signout), [Storybook](https://fix-5239-reset-to-mainnet-on-signout--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=fix/5239/reset-to-mainnet-on-signout)

This PR adds a fix that re-sets the network to `mainnet` on sign out. 

I also added another fix to how we are adding some dialogs to the VDOM. 

I noticed that we were calling hooks in the settings menu dialogs whenever the parent is rendered and even if they aren't visible. This is a bad problem as was adding to our API requests to `network` un-necessarily.

### CODE REVIEW

File: src/app/common/hooks/use-key-actions.ts [hunk 1]
```diff
@@ -55,6 +57,8 @@ export function useKeyActions() {
 
       async signOut() {
         await clearWalletSession();
+        networksActions.changeNetwork('mainnet');
+        void analytics.track('change_network', { id: 'mainnet' });
```
Comment (kyranjamie) [inline src/app/common/hooks/use-key-actions.ts]: I don't think we want an analytics event here. The user isn't actually changing network, and this makes it seem as so.

File: src/app/common/hooks/use-key-actions.ts [hunk 2]
```diff
@@ -55,6 +57,8 @@ export function useKeyActions() {
 
       async signOut() {
         await clearWalletSession();
+        networksActions.changeNetwork('mainnet');
```
Comment (kyranjamie) [inline src/app/common/hooks/use-key-actions.ts]: Wonder if we should handle this at the reducer-layer, the same way we do for bitcoinKeysSlice on L63?

File: src/app/features/settings/settings.tsx [hunk 3]
```diff
@@ -200,15 +200,11 @@ export function Settings({ triggerButton, toggleSwitchAccount }: SettingsProps)
...
-      />
-      <NetworkDialog
-        isShowing={showChangeNetwork}
-        onClose={() => setShowChangeNetwork(!showChangeNetwork)}
-      />
+      {showSignOut && <SignOut onClose={() => setShowSignOut(!showSignOut)} />}
+      {showChangeTheme && <ThemeDialog onClose={() => setShowChangeTheme(!showChangeTheme)} />}
+      {showChangeNetwork && (
+        <NetworkDialog onClose={() => setShowChangeNetwork(!showChangeNetwork)} />
+      )}
```
Comment (kyranjamie) [inline src/app/features/settings/settings.tsx:207]: 👌🏼

File: src/app/common/hooks/use-key-actions.ts (hunk 1 above)
Comment (pete-watters) [reply src/app/common/hooks/use-key-actions.ts]: OK cool, I can remove it.

File: src/app/common/hooks/use-key-actions.ts (hunk 2 above)
Comment (pete-watters) [reply src/app/common/hooks/use-key-actions.ts]: OK. Should I setup a new slice for network, or just use `dispatch`?

Comment (kyranjamie) [reply src/app/common/hooks/use-key-actions.ts]: We already have a network slice, just saying that in that slice, we could either make a new signout action, or even use the same signout event to reset the state.

Comment (pete-watters) [reply src/app/common/hooks/use-key-actions.ts]: Thanks. I've refactored this to use the network slice

**Review by fbwoolf — APPROVED** [review]

**Review by kyranjamie — APPROVED** [review]
