### PR TITLE
fix: prevent auto-zoom of sign in field, fixes #510

### LINKED ISSUE #510: Prevent automatic screen zoom upon selection of Secret Key textarea on moible
# Behavior

27071347-8D6D-42D1-8E0E-0BB3208F1702_1_105_c

# Expectation

IMG_2530

### PR DESCRIPTION
**Pull request by hstove**

### CODE REVIEW

File: packages/app/src/pages/sign-in/initial.tsx [hunk 1]
```diff
@@ -82,7 +82,8 @@ export const SignIn: React.FC<SignInProps> = props => {
               placeholder="12-word Secret Key"
               as="textarea"
               value={seed}
-              autoCapitalize="false"
+              fontSize={['16px', '14px']}
```
Comment (kyranjamie) [inline packages/app/src/pages/sign-in/initial.tsx]: Won't this still zoom if you're on an iPad? Can we do 16px everywhere?

**Review by kyranjamie — APPROVED** [review]

File: packages/app/src/pages/sign-in/initial.tsx (hunk 1 above)
Comment (hstove) [reply packages/app/src/pages/sign-in/initial.tsx]: Yep, changed to just 16px
