### PR TITLE
fix: add hiro api key

### LINKED ISSUE #4518: Add API key to all network requests to Hiro API
https://forum.stacks.org/t/upcoming-change-to-rate-limits-for-hiro-apis/15693

### PR DESCRIPTION
**Pull request by kyranjamie**
> Try out this version of Leather — [download extension builds](https://github.com/leather-wallet/extension/actions/runs/6878129070).

Closes #4518

Adds Hiro API key to Hiro requests. [See musing on axios/fetch here.](https://trustmachines.slack.com/archives/C05LAP952E7/p1700051834469919). Foremost, we should be consistent in our approach.

### CODE REVIEW

File: src/app/query/bitcoin/contract/send-accepted-bitcoin-contract-offer.ts [hunk 1]
```diff
@@ -2,6 +2,8 @@ export async function sendAcceptedBitcoinContractOfferToProtocolWallet(
   acceptedBitcoinContractOffer: string,
   counterpartyWalletURL: string
 ) {
+  // TODO: refactor to use `axios`
```
Comment (pete-watters) [inline src/app/query/bitcoin/contract/send-accepted-bitcoin-contract-offer.ts:5]: Usually I'd make an issue and then add the issue in the comment here 
`#1234 TODO: .... `

**Review by pete-watters — APPROVED** [review]
👍

File: src/app/query/bitcoin/contract/send-accepted-bitcoin-contract-offer.ts (hunk 1 above)
Comment (kyranjamie) [reply src/app/query/bitcoin/contract/send-accepted-bitcoin-contract-offer.ts:5]: done 👍🏼
